[net] cfg80211: fix CFG80211_EXTRA_REGDB_KEYDIR typo
Message-id: <1533910507-4884-6-git-send-email-sgruszka@redhat.com>
Patchwork-id: 226607
O-Subject: [RHEL7.6 PATCH 05/18] cfg80211: fix CFG80211_EXTRA_REGDB_KEYDIR typo
Bugzilla: 1591601
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1591601

Backport of:
commit 88230ef1f31bf2d8fcf42c20e5743ff4b3618a29
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Oct 13 14:04:31 2017 +0200

    cfg80211: fix CFG80211_EXTRA_REGDB_KEYDIR typo

    The missing CONFIG_ prefix means this macro is never defined,
    leading to a possible Kbuild warning:

    net/wireless/reg.c:666:20: error: 'load_keys_from_buffer' defined but not used [-Werror=unused-function]
     static void __init load_keys_from_buffer(const u8 *p, unsigned int buflen)

    When we use the correct symbol, the warning also goes away.

    Fixes: 90a53e4432b1 ("cfg80211: implement regdb signature checking")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Brew:
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17692053

Testing:
Tested by Intel and Dell.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>