[tools] perf record: Throttle user defined frequencies to the maximum allowed
Message-id: <20190211232742.16489-57-jolsa@redhat.com>
Patchwork-id: 241451
O-Subject: [PATCH RHEL7 BZ1672651 056/271] perf record: Throttle user defined frequencies to the maximum allowed
Bugzilla: 1672651
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1672651
https://bugzilla.redhat.com/show_bug.cgi?id=1672651

upstream
========
commit b09c2364a4dc2a67e640c2b839d936302815693f
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Mar 1 14:52:50 2018 -0300

description
===========
  # perf record -F 200000 sleep 1
  warning: Maximum frequency rate (15,000 Hz) exceeded, throttling from 200,000 Hz to 15,000 Hz.
           The limit can be raised via /proc/sys/kernel/perf_event_max_sample_rate.
           The kernel will lower it when perf's interrupts take too long.
	   Use --strict-freq to disable this throttling, refusing to record.
  [ perf record: Woken up 1 times to write data ]
  [ perf record: Captured and wrote 0.019 MB perf.data (15 samples) ]
  # perf evlist -v
  cycles:ppp: size: 112, { sample_period, sample_freq }: 15000, sample_type: IP|TID|TIME|PERIOD, disabled: 1, inherit: 1, mmap: 1, comm: 1, freq: 1, enable_on_exec: 1, task: 1, precise_ip: 3, sample_id_all: 1, exclude_guest: 1, mmap2: 1, comm_exec: 1

For those wanting that it fails if the desired frequency can't be used:

  # perf record --strict-freq -F 200000 sleep 1
  error: Maximum frequency rate (15,000 Hz) exceeded.
         Please use -F freq option with a lower value or consider
         tweaking /proc/sys/kernel/perf_event_max_sample_rate.
  #

RHEL7
=====
Small context conflict with already taken sample_id via:
  f4a1fe7f1d10 [tools] perf record: Fix crash in pipe mode

Signed-off-by: Jan Stancek <jstancek@redhat.com>