[vhost] fix vhost ioctl signature to build with clang
Message-id: <1525310130-5405-1-git-send-email-haliu@redhat.com>
Patchwork-id: 212183
O-Subject: [PATCH RHEL7.6 net 4/8] vhost: fix vhost ioctl signature to build with clang
Bugzilla: 1551292
RH-Acked-by: Jason Wang <jasowang@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1551292
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=15956547
Upstream Status: net.git commit 26b36604523f

commit 26b36604523f4a681a86e6cbc970ea72a2e9fb8a
Author: Sonny Rao <sonnyrao@chromium.org>
Date:   Wed Mar 14 10:05:06 2018 -0700

    vhost: fix vhost ioctl signature to build with clang

    Clang is particularly anal about signed vs unsigned comparisons and
    doesn't like the fact that some ioctl numbers set the MSB, so we get
    this error when trying to build vhost on aarch64:

    drivers/vhost/vhost.c:1400:7: error: overflow converting case value to
     switch condition type (3221794578 to 18446744072636378898)
     [-Werror, -Wswitch]
            case VHOST_GET_VRING_BASE:

    3221794578 is 0xC008AF12 in hex
    18446744072636378898 is 0xFFFFFFFFC008AF12 in hex

    Fix this by using unsigned ints in the function signature for
    vhost_vring_ioctl().

    Signed-off-by: Sonny Rao <sonnyrao@chromium.org>
    Reviewed-by: Darren Kenny <darren.kenny@oracle.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

Signed-off-by: Hangbin Liu <haliu@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>