[net] ipv6: Return error for RTA_VIA attribute
Message-id: <3f213039a62b889f5371825c438a18f86ff6d04f.1567553257.git.sbrivio@redhat.com>
Patchwork-id: 270603
O-Subject: [RHEL7.8 net] ipv6: Return error for RTA_VIA attribute
Bugzilla: 1725992
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Guillaume Nault <gnault@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1725992
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23333106
Tested: with steps from commit message

Backport Notes: current RHEL7 iproute2 can pass the RTA_VIA attribute,
	the kernel would just discard that. Add its value to the
	enumeration: a stub was added by RHEL7 commit 44058011a70e
	("[net] ipv6: allow routes to be configured with expire"), and
	we are now introducing its first usage (namely, to check that
	it's not passed where it shouldn't be).

commit e3818541b49fb88650ba339d33cc53e4095da5b3
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Feb 26 09:00:03 2019 -0800

    ipv6: Return error for RTA_VIA attribute

    IPv6 currently does not support nexthops outside of the AF_INET6 family.
    Specifically, it does not handle RTA_VIA attribute. If it is passed
    in a route add request, the actual route added only uses the device
    which is clearly not what the user intended:

      $ ip -6 ro add 2001:db8:2::/64 via inet 172.16.1.1 dev eth0
      $ ip ro ls
      ...
      2001:db8:2::/64 dev eth0 metric 1024 pref medium

    Catch this and fail the route add:
      $ ip -6 ro add 2001:db8:2::/64 via inet 172.16.1.1 dev eth0
      Error: IPv6 does not support RTA_VIA attribute.

    Fixes: 03c0566542f4c ("mpls: Netlink commands to add, remove, and dump routes")
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>