[netdrv] mlx5: Eliminate query xsrq dead code
Message-id: <1549457075-6314-116-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240074
O-Subject: [RHEL7.7 BZ 1642498 115/729] net/mlx5: Eliminate query xsrq dead code
Bugzilla: 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Upstream: v4.17-rc1

commit b2d3907c234618c20239127f2c234b4e92adf5ef
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Tue Feb 13 17:07:02 2018 -0800

    net/mlx5: Eliminate query xsrq dead code

    1. This function is not used anywhere in mlx5 driver
    2. It has a memcpy statement that makes no sense and produces build
    warning with gcc8

    drivers/net/ethernet/mellanox/mlx5/core/transobj.c: In function 'mlx5_core_query_xsrq':
    drivers/net/ethernet/mellanox/mlx5/core/transobj.c:347:3: error: 'memcpy' source argument is the same as destination [-Werror=restrict]

    Fixes: 01949d0109ee ("net/mlx5_core: Enable XRCs and SRQs when using ISSI > 0")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>