[kernel] device property: Define type of PROPERTY_ENRTY_*() macros
Message-id: <20180724115140.5837-2-prarit@redhat.com>
Patchwork-id: 225323
O-Subject: [RHEL7.6 BZ 1597102 1/4] device property: Define type of PROPERTY_ENRTY_*() macros
Bugzilla: 1597102
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Jaroslav Kysela <jkysela@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1597102

commit c505cbd45f6e9c539d57dd171d95ec7e5e9f9cd0
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Jan 22 18:01:42 2018 +0200

    device property: Define type of PROPERTY_ENRTY_*() macros

    Some of the drivers may use the macro at runtime flow, like

      struct property_entry p[10];
    ...
      p[index++] = PROPERTY_ENTRY_U8("u8 property", u8_data);

    In that case and absence of the data type compiler fails the build:

    drivers/char/ipmi/ipmi_dmi.c:79:29: error: Expected ; at end of statement
    drivers/char/ipmi/ipmi_dmi.c:79:29: error: got {

    Acked-by: Corey Minyard <cminyard@mvista.com>
    Cc: Corey Minyard <minyard@acm.org>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Cc: Jaroslav Kysela <jkysela@redhat.com>
Cc: Prarit Bhargava <prarit@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>