[kernel] trace/bpf_trace.c: work around gcc-4.4.4 anon union initialization bug
Message-id: <20180613214317.28803-65-jolsa@redhat.com>
Patchwork-id: 221635
O-Subject: [PATCH RHEL7.6 BZ1311586 064/386] kernel/trace/bpf_trace.c: work around gcc-4.4.4 anon union initialization bug
Bugzilla: 1311586
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit 183fc1537ec39be242dc8b619f71fc11b393d295
Author: Andrew Morton <akpm@linux-foundation.org>
Date: Mon Jul 18 15:50:58 2016 -0700

description
===========
kernel/trace/bpf_trace.c: In function 'bpf_event_output':
kernel/trace/bpf_trace.c:312: error: unknown field 'next' specified in initializer
kernel/trace/bpf_trace.c:312: warning: missing braces around initializer
kernel/trace/bpf_trace.c:312: warning: (near initialization for 'raw.frag.<anonymous>')

Fixes: 555c8a8623a3a87 ("bpf: avoid stack copy and use skb ctx for event output")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>