[infiniband] ib/uverbs: Add missing braces in anonymous union initializers
Message-id: <20181129133352.19421-130-kheib@redhat.com>
Patchwork-id: 234109
O-Subject: [PATCH RHEL-7.7 129/141] IB/uverbs: Add missing braces in anonymous union initializers
Bugzilla: 1641363
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1641363

commit e33514f2e930ad800fa52db19e889bb0fba25419
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon Apr 9 16:52:47 2018 +0200

    IB/uverbs: Add missing braces in anonymous union initializers

    With gcc-4.1.2:

        drivers/infiniband/core/uverbs_std_types_flow_action.c:366: error: unknown field ptr specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:367: error: unknown field type specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:367: warning: missing braces around initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:367: warning: (near initialization for uverbs_flow_action_esp_keymat[0].<anonymous>.<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: error: unknown field min_len specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: warning: (near initialization for uverbs_flow_action_esp_keymat[0].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: error: unknown field len specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:368: warning: (near initialization for uverbs_flow_action_esp_keymat[0].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:369: error: unknown field flags specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:369: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:369: warning: (near initialization for uverbs_flow_action_esp_keymat[0].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:376: error: unknown field ptr specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:377: error: unknown field type specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:377: warning: missing braces around initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:377: warning: (near initialization for uverbs_flow_action_esp_replay[0].<anonymous>.<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:379: error: unknown field len specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:379: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:379: warning: (near initialization for uverbs_flow_action_esp_replay[0].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:383: error: unknown field ptr specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:384: error: unknown field type specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: error: unknown field min_len specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: warning: (near initialization for uverbs_flow_action_esp_replay[1].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: error: unknown field len specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:385: warning: (near initialization for uverbs_flow_action_esp_replay[1].<anonymous>)
        drivers/infiniband/core/uverbs_std_types_flow_action.c:386: error: unknown field flags specified in initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:386: warning: excess elements in union initializer
        drivers/infiniband/core/uverbs_std_types_flow_action.c:386: warning: (near initialization for uverbs_flow_action_esp_replay[1].<anonymous>)

    Add the missing braces to fix this.

    Fixes: 2eb9beaee5d7 ("IB/uverbs: Add flow_action create and destroy verbs")
    Fixes: 7d12f8d5a164 ("IB/uverbs: Add modify ESP flow_action")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>