[kernel] bpf: fix implicit declaration of bpf_prog_add
Message-id: <20180613214317.28803-69-jolsa@redhat.com>
Patchwork-id: 221514
O-Subject: [PATCH RHEL7.6 BZ1311586 068/386] bpf: fix implicit declaration of bpf_prog_add
Bugzilla: 1311586
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit cc2e0b3fbcdd9667d7b7ecdf36d7b4d3647681d6
Author: Brenden Blanco <bblanco@plumgrid.com>
Date: Wed Jul 20 07:55:52 2016 -0700

description
===========
For the ifndef case of CONFIG_BPF_SYSCALL, an inline version of
bpf_prog_add needs to exist otherwise the build breaks on some configs.

 drivers/net/ethernet/mellanox/mlx4/en_netdev.c:2544:10: error: implicit declaration of function 'bpf_prog_add'
       prog = bpf_prog_add(prog, priv->rx_ring_num - 1);

The function is introduced in
59d3656d5bf50 ("bpf: add bpf_prog_add api for bulk prog refcnt")
and first used in
47f1afdba2b87 ("net/mlx4_en: add support for fast rx drop bpf program").

Fixes: 47f1afdba2b87 ("net/mlx4_en: add support for fast rx drop bpf program")

RHEL7
=====
Removing current bpf_prog_add stub.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>