[netdrv] nfp: don't depend on compiler constant propagation
Message-id: <e85087582f238b6c9b9487d5ebc2dbba993b1479.1517426360.git.linville@redhat.com>
Patchwork-id: 204600
O-Subject: [RHEL7 PATCH 1/6] nfp: don't depend on compiler constant propagation
Bugzilla: 1519199
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

BZ:   https://bugzilla.redhat.com/show_bug.cgi?id=1519199
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15148909

Matthias reports:

  nfp_eth_set_bit_config() is marked as __always_inline to allow gcc to
  identify the 'mask' parameter as known to be constant at compile time,
  which is required to use the FIELD_GET() macro.

  The forced inlining does the trick for gcc, but for kernel builds with
  clang it results in undefined symbols:

  drivers/net/ethernet/netronome/nfp/nfpcore/nfp_nsp_eth.o: In function
    `__nfp_eth_set_aneg':

drivers/net/ethernet/netronome/nfp/nfpcore/nfp_nsp_eth.c:(.text+0x787):
    undefined reference to `__compiletime_assert_492'

drivers/net/ethernet/netronome/nfp/nfpcore/nfp_nsp_eth.c:(.text+0x7b1):
    undefined reference to `__compiletime_assert_496'

  These __compiletime_assert_xyx() calls would have been optimized away
if
  the compiler had seen 'mask' as a constant.

Add a macro to extract the mask and shift and pass those to
nfp_eth_set_bit_config() separately.

Reported-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
Tested-by: Dirk van der Merwe <dirk.vandermerwe@netronome.com>
Signed-off-by: Simon Horman <simon.horman@netronome.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 4e59532541c865c85c92d42be4edf2ba6aa4af64)
Signed-off-by: John W. Linville <linville@redhat.com>
---
This patch by itself has no real functionality, but it allows
a later patch in the series to compile without changes...

Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>