[target] pscsi: Fix TYPE_TAPE + TYPE_MEDIMUM_CHANGER export
Message-id: <1527857684-16350-55-git-send-email-mlombard@redhat.com>
Patchwork-id: 219470
O-Subject: [RHEL7.6 e-stor PATCH 054/151] target/pscsi: Fix TYPE_TAPE + TYPE_MEDIMUM_CHANGER export
Bugzilla: 1585081
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The following fixes a divide by zero OOPs with TYPE_TAPE
due to pscsi_tape_read_blocksize() failing causing a zero
sd->sector_size being propigated up via dev_attrib.hw_block_size.

It also fixes another long-standing bug where TYPE_TAPE and
TYPE_MEDIMUM_CHANGER where using pscsi_create_type_other(),
which does not call scsi_device_get() to take the device
reference.  Instead, rename pscsi_create_type_rom() to
pscsi_create_type_nondisk() and use it for all cases.

Finally, also drop a dump_stack() in pscsi_get_blocks() for
non TYPE_DISK, which in modern target-core can get invoked
via target_sense_desc_format() during CHECK_CONDITION.

Reported-by: Malcolm Haak <insanemal@gmail.com>
Cc: <stable@vger.kernel.org>
Signed-off-by: Nicholas Bellinger <nab@linux-iscsi.org>
(cherry picked from commit a04e54f2c35823ca32d56afcd5cea5b783e2f51a)
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>

Conflicts:
	drivers/target/target_core_pscsi.c
	(pscsi_create_type_other(): small difference in a pr_debug())

pscsi_add_device_to_list(): fix warning when calling min_not_zero()

In function 'pscsi_add_device_to_list':
include/linux/kernel.h:784:17: error: comparison of distinct pointer types lacks a cast [-Werror]
  (void) (&_min1 == &_min2);