[infiniband] rdma/bnxt_re: use BIT_ULL() for 64-bit bit masks
Message-id: <1523437443-19278-24-git-send-email-sxavier@redhat.com>
Patchwork-id: 208886
O-Subject: [RHEL 7.6 PATCH BZ 1550629 23/24] RDMA/bnxt_re: use BIT_ULL() for 64-bit bit masks
Bugzilla: 1550629
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1550629
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15718765
Upstream Status: commit bd8602ca42f6d8b25392a8f2a0e7be34e1206618
Test info: https://bugzilla.redhat.com/show_bug.cgi?id=1550629 for
details

commit bd8602ca42f6d8b25392a8f2a0e7be34e1206618
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 20 21:56:27 2018 +0100

    infiniband: bnxt_re: use BIT_ULL() for 64-bit bit masks

    On 32-bit targets, we otherwise get a warning about an impossible constant
    integer expression:

    In file included from include/linux/kernel.h:11,
                     from include/linux/interrupt.h:6,
                     from drivers/infiniband/hw/bnxt_re/ib_verbs.c:39:
    drivers/infiniband/hw/bnxt_re/ib_verbs.c: In function 'bnxt_re_query_device':
    include/linux/bitops.h:7:24: error: left shift count >= width of type [-Werror=shift-count-overflow]
     #define BIT(nr)   (1UL << (nr))
                            ^~
    drivers/infiniband/hw/bnxt_re/bnxt_re.h:61:34: note: in expansion of macro 'BIT'
     #define BNXT_RE_MAX_MR_SIZE_HIGH BIT(39)
                                      ^~~
    drivers/infiniband/hw/bnxt_re/bnxt_re.h:62:30: note: in expansion of macro 'BNXT_RE_MAX_MR_SIZE_HIGH'
     #define BNXT_RE_MAX_MR_SIZE  BNXT_RE_MAX_MR_SIZE_HIGH
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
    drivers/infiniband/hw/bnxt_re/ib_verbs.c:149:25: note: in expansion of macro 'BNXT_RE_MAX_MR_SIZE'
      ib_attr->max_mr_size = BNXT_RE_MAX_MR_SIZE;
                             ^~~~~~~~~~~~~~~~~~~

    Fixes: 872f3578241d ("RDMA/bnxt_re: Add support for MRs with Huge pages")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Selvin Xavier <sxavier@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>