[tools] perf tools: Add tools/include/uapi/asm-generic/fcntl.h to the MANIFEST
Message-id: <20180419185703.28105-121-jolsa@redhat.com>
Patchwork-id: 209990
O-Subject: [PATCH RHEL7.6 BZ1540862 120/245] perf tools: Add tools/include/uapi/asm-generic/fcntl.h to the MANIFEST
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 62e6039f02888efdd824e8c596c4927616a97ce3
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Jul 25 14:14:27 2017 -0300

description
===========
This file was copied from the kernel so that we could build tools/perf/
on older systems where some newer defines, such as these are available:

    CC       trace/beauty/fcntl.o
  trace/beauty/fcntl.c: In function syscall_arg__scnprintf_fcntl_arg:
  trace/beauty/fcntl.c:93:13: error: F_OFD_SETLK undeclared (first use in this function)
        cmd == F_OFD_SETLK || cmd == F_OFD_SETLKW || cmd == F_OFD_GETLK ||
               ^
  trace/beauty/fcntl.c:93:13: note: each undeclared identifier is reported only once for each function it appears in
  trace/beauty/fcntl.c:93:35: error: F_OFD_SETLKW undeclared (first use in this function)
        cmd == F_OFD_SETLK || cmd == F_OFD_SETLKW || cmd == F_OFD_GETLK ||
                                     ^
  trace/beauty/fcntl.c:93:58: error: F_OFD_GETLK undeclared (first use in this function)
        cmd == F_OFD_SETLK || cmd == F_OFD_SETLKW || cmd == F_OFD_GETLK ||
                                                            ^
  mv: cannot stat trace/beauty/.fcntl.o.tmp: No such file or directory
  make[4]: *** [trace/beauty/fcntl.o] Error 1
  make[3]: *** [trace/beauty] Error 2
  make[3]: *** Waiting for unfinished jobs....
    CC       tests/llvm.o

But we need to make sure that it is also in the tools/perf/MANIFEST file, that
is used to build a tarball for detached (from the kernel sources) compilation,
which was failing, with the above message, on a RHEL7.4 system, fix it.

Fixes: 84d1d8a12df3 ("tools include uapi asm-generic: Grab a copy of fcntl.h")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>