[netdrv] bnxt_en: take coredump_record structure off stack
Message-id: <b2ee7113d1c37f4aadf58dd596963303523fc688.1549483148.git.jtoppins@redhat.com>
Patchwork-id: 240817
O-Subject: [RHEL7.7 PATCH 052/133] bnxt_en: take coredump_record structure off stack
Bugzilla: 1643317
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

The bnxt_coredump_record structure is very long, causing a warning
about possible stack overflow on 32-bit architectures:

drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c: In function 'bnxt_get_coredump':
drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:2989:1: error: the frame size of 1188 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

I could not see any reason to operate on an on-stack copy of the
structure before copying it back into the caller-provided buffer, which
also simplifies the code here.

Fixes: 6c5657d085ae ("bnxt_en: Add support for ethtool get dump.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 1bbf3aed25e0fc256e825da1f5c45d7b4daa828e)
Bugzilla: 1643317
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20065938
Tested: basic boot test as well as partner testing
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>