[netdrv] mlxsw: spectrum: Add extack for VLAN enslavements
Message-id: <20180601184800.22484-50-ivecera@redhat.com>
Patchwork-id: 220008
O-Subject: [RHEL7.6 PATCH 048/224] mlxsw: spectrum: Add extack for VLAN enslavements
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Backport note:
- Using dev_err() instead of NL_SET_ERR_MSG() due to absence of extack
  support in RHEL

Upstream commit(s):
commit c1f2c6d025d365d961dcdf555ecf0f60066f38a3
Author: Ido Schimmel <idosch@mellanox.com>
Date:   Sun Oct 8 11:57:55 2017 +0200

    mlxsw: spectrum: Add extack for VLAN enslavements

    Similar to physical ports, enslavement of VLAN devices can also fail.
    Use extack to indicate why the enslavement failed.

    $ ip link add link enp1s0np1 name enp1s0np1.10 type vlan id 10
    $ ip link add name bond0 type bond mode 802.3ad
    $ ip link set dev enp1s0np1.10 master bond0
    Error: spectrum: VLAN devices only support bridge and VRF uppers.

    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Acked-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>