[usb] select USB_COMMON for usb role switch config
Message-id: <1552707357-18587-115-git-send-email-torez@redhat.com>
Patchwork-id: 246562
O-Subject: [RHEL7.7 PATCH BZ1657401 V2 114/378] usb: select USB_COMMON for usb role switch config
Bugzilla: 1657401
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1657401
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20451897
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20625676
Testing: on Dell Whitehaven Precision 7730, HP ZBook 15 G3/80D5 and
         ThinkCentre M910z All-in-One

commit 602f4fb71d2b4aa5a447d4ed25a58fd098df9058
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 4 14:21:53 2018 +0200

    usb: select USB_COMMON for usb role switch config

    The new axp288 extcon driver has no dependency on USB itself but
    calls the usb role switch helper functions. This causes a link error
    when USB_COMMON is disabled, as that subdirectory never gets entered:

    drivers/extcon/extcon-axp288.o: In function `axp288_usb_role_work':
    extcon-axp288.c:(.text+0x47b): undefined reference to `usb_role_switch_set_role'
    extcon-axp288.c:(.text+0x498): undefined reference to `usb_role_switch_get_role'
    drivers/extcon/extcon-axp288.o: In function `axp288_extcon_probe':
    extcon-axp288.c:(.text+0x675): undefined reference to `usb_role_switch_get'
    extcon-axp288.c:(.text+0x6d1): undefined reference to `usb_role_switch_put'
    drivers/extcon/extcon-axp288.o: In function `axp288_put_role_sw':
    extcon-axp288.c:(.text+0x1c): undefined reference to `usb_role_switch_put'

    There are multiple ways of fixing this, I chose to 'select USB_COMMON',
    since that is how we solved the same problem for other helpers like
    USB_LED_TRIG or PHY drivers.

    Fixes: d54f063cdbe4 ("extcon: axp288: Set USB role where necessary")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>