[fs] xfs: fix len comparison in xfs_extent_busy_trim
Message-id: <20180521171030.115571-60-bfoster@redhat.com>
Patchwork-id: 216624
O-Subject: [RHEL7.6 PATCH 059/136] xfs: fix len comparison in xfs_extent_busy_trim
Bugzilla: 1579873
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

commit 353fe445f5efd58dfec6e06bf4747a9c28374adc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 14 18:16:50 2017 -0800

    xfs: fix len comparison in xfs_extent_busy_trim

    The length is now passed by reference, so the assertion has to be updated
    to match the other changes, as pointed out by this W=1 warning:

    fs/xfs/xfs_extent_busy.c: In function 'xfs_extent_busy_trim':
    fs/xfs/xfs_extent_busy.c:356:13: error: ordered comparison of pointer with integer zero [-Werror=extra]

    Fixes: ebf55872616c ("xfs: improve handling of busy extents in the low-level allocator")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>