[uapi] mlx5e: Add clock info page to mlx5 core devices
Message-id: <1525797923-26277-128-git-send-email-ahleihel@redhat.com>
Patchwork-id: 213328
O-Subject: [RHEL7.6 BZ 1520297 v2 127/181] net/mlx5e: Add clock info page to mlx5 core devices
Bugzilla: 1520297
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1520297

Backport notes:
- Defined smp_store_mb in "drivers/net/ethernet/mellanox/mlx5/core/lib/clock.c"
  to fix compilation error in RHEL7:
  error: implicit declaration of function smp_store_mb

commit 24d33d2c8e92abffe1f0653d42fc65b8f164a6d9
Author: Feras Daoud <ferasda@mellanox.com>
Date:   Tue Jan 16 20:08:40 2018 +0200

    net/mlx5e: Add clock info page to mlx5 core devices

    Adds a new page to mlx5 core containing clock info data that allows
    user level applications to translate between cqe timestamp to
    nanoseconds. The information stored into this page is represented
    through mlx5_ib_clock_info.

    In order to synchronize between kernel and user space a sequence
    number is incremented at the beginning and end of each update.
    An odd number means the data is being updated while an even means
    the access was already done. To guarantee that the data structure
    was accessed atomically user will:

    repeat:
            seq1 = <read sequence>
            goto <repeate> while odd
            <read data structure>
            seq2 = <read sequence>
            if seq1 != seq2 goto repeat

    Reviewed-by: Yishai Hadas <yishaih@mellanox.com>
    Reviewed-by: Jason Gunthorpe <jgg@mellanox.com>
    Reviewed-by: Alex Vesker <valex@mellanox.com>
    Signed-off-by: Feras Daoud <ferasda@mellanox.com>
    Signed-off-by: Eitan Rabin <rabin@mellanox.com>
    Signed-off-by: Leon Romanovsky <leon@kernel.org>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>