[infiniband] ib/mlx4: fix sprintf format warning
Message-id: <20171116210913.11180-348-ddutile@redhat.com>
Patchwork-id: 198772
O-Subject: [PATCH RHEL-7.5 347/372] IB/mlx4: fix sprintf format warning
Bugzilla: 1499364 1456692
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit d0dbf771309fecd73f4ac1566c1400cb12807ee2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 13 16:28:26 2017 -0700

    IB/mlx4: fix sprintf format warning

    gcc-7 points out that a negative port_num value would overflow the
    string buffer:

      drivers/infiniband/hw/mlx4/sysfs.c: In function 'mlx4_ib_device_register_sysfs':
      drivers/infiniband/hw/mlx4/sysfs.c:251:16: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
      drivers/infiniband/hw/mlx4/sysfs.c:251:2: note: 'sprintf' output between 2 and 11 bytes into a destination of size 10
      drivers/infiniband/hw/mlx4/sysfs.c:303:17: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
      drivers/infiniband/hw/mlx4/sysfs.c:303:3: note: 'sprintf' output between 2 and 11 bytes into a destination of size 10

    While we should be able to assume that port_num is positive here, making
    the buffer one byte longer has no downsides and avoids the warning.

    Fixes: c1e7e466120b ("IB/mlx4: Add iov directory in sysfs under the ib device")
    Link: http://lkml.kernel.org/r/20170714120720.906842-23-arnd@arndb.de
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456692

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>