[net] openvswitch: use __u32 from linux/types.h
Message-id: <a89d3d4639ab75c82f7b697cec2007105e832c85.1509980539.git.jbenc@redhat.com>
Patchwork-id: 195902
O-Subject: [RHEL7.5 net 42/91] include/uapi/linux/openvswitch.h: use __u32 from linux/types.h
Bugzilla: 1497774
RH-Acked-by: Flavio Leitner <fbl@redhat.com>
RH-Acked-by: Eric Garver <egarver@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1497774

commit a1d1f65ff5ac27276a585b41a619d30995bb92fe
Author: Mikko Rapeli <mikko.rapeli@iki.fi>
Date:   Mon Aug 22 20:33:19 2016 +0200

    include/uapi/linux/openvswitch.h: use __u32 from linux/types.h

    Kernel uapi header are supposed to use them. Fixes userspace compile error:

    linux/openvswitch.h:583:2: error: unknown type name 'uint32_t'

    Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>