[scsi] cxgb4i: silence overflow warning in t4_uld_rx_handler()
Message-id: <1525268908-23554-3-git-send-email-avynipad@redhat.com>
Patchwork-id: 212166
O-Subject: [RHEL7.6 PATCH BZ 1523190 2/2] scsi: cxgb4i: silence overflow warning in t4_uld_rx_handler()
Bugzilla: 1523190
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1523190

commit ccc495efb326d17be3e7790b5aa49b25e239ead7
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Tue Apr 3 11:52:22 2018 +0300

    scsi: cxgb4i: silence overflow warning in t4_uld_rx_handler()

    Smatch marks skb->data as untrusted so it complains that there is a
    potential overflow here:

    	drivers/scsi/cxgbi/cxgb4i/cxgb4i.c:2111 t4_uld_rx_handler()
    	error: buffer overflow 'cxgb4i_cplhandlers' 239 <= 255.

    In this case, skb->data comes from the hardware or firmware so it's not
    going to overflow unless there is a firmware bug.

    [mkp: fixed braces]

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Cc: David Milburn <dmilburn@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>