[infiniband] rdma: Fix building with CONFIG_MMU=n
Message-id: <20190123083944.14645-106-kheib@redhat.com>
Patchwork-id: 237990
O-Subject: [PATCH RHEL-7.7 V2 105/151] RDMA: Fix building with CONFIG_MMU=n
Bugzilla: 1655923
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Ken Cox <jkc@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1655923

commit 914e5d7d4697fb9815fa237a4d42bfb952bf48d6
Author: Jason Gunthorpe <jgg@mellanox.com>
Date:   Fri Sep 28 15:20:23 2018 -0600

    RDMA: Fix building with CONFIG_MMU=n

    The zap_vma_ptes() is declared but not defined on NOMMU kernels, causing a
    link error for the newly added uverbs code:

    drivers/infiniband/core/uverbs_main.o: In function `uverbs_user_mmap_disassociate':
    uverbs_main.c:(.text+0x114c): undefined reference to `zap_vma_ptes'
    drivers/infiniband/core/uverbs_main.o: In function `rdma_umap_open':
    uverbs_main.c:(.text+0x53c): undefined reference to `zap_vma_ptes'

    Since all user access for all of our drivers depend on remapping pages to
    user space disable USER_ACCESS when there is no mmu.

    Fixes: 5f9794dc94f5 ("RDMA/ucontext: Add a core API for mmaping driver IO memory")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>