[edac] EDAC, skx: Fix randconfig builds
Message-id: <20190807011241.3682-6-jmoyer@redhat.com>
Patchwork-id: 268377
O-Subject: [RHEL7.8 PATCH 5/6] EDAC, skx: Fix randconfig builds
Bugzilla: 1471701
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Aristeu S. Rozanski F. <arozansk@redhat.com>

From: Borislav Petkov <bp@suse.de>

BZ: 1471701
Brew: 20166714

commit a324e9396ca3d00e1101476ba067b412e0aba232
Author: Borislav Petkov <bp@suse.de>
Date:   Wed Oct 31 19:20:20 2018 +0100

    EDAC, skx: Fix randconfig builds

    The driver depends on the ADXL component glue and selects it. However,
    ADXL itself implicitly depends on ACPI and in nonsensical randconfig
    builds like this:

      # CONFIG_ACPI is not set
      CONFIG_ACPI_ADXL=y

    where ACPI is not enabled, the build fails with:

      drivers/edac/skx_edac.o: In function `skx_mce_check_error':
      skx_edac.c:(.text+0xab): undefined reference to `adxl_decode'
      drivers/edac/skx_edac.o: In function `skx_init':
      skx_edac.c:(.init.text+0x8bf): undefined reference to `adxl_get_component_names'
      make: *** [vmlinux] Error 1

    Add stubs for that case so that the build succeeds. CONFIG_ACPI=n
    doesn't make any sense for real configurations but this fix will at
    least silence randconfig builds.

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Acked-by: Tony Luck <tony.luck@intel.com>
    Cc: "Rafael J. Wysocki" <rafael@kernel.org>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>