[infiniband] rdma: Fix dependencies for rdma_user_mmap_io
Message-id: <1549457075-6314-466-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240434
O-Subject: [RHEL7.7 BZ 1642498 465/729] RDMA: Fix dependencies for rdma_user_mmap_io
Bugzilla: 1641912 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Bugzilla: http://bugzilla.redhat.com/1641912
Upstream: v4.20-rc1
Backport notes:
 - Drop hns hunks as this module does not exist in RHEL-7 kernel.

commit 46bdf777685677c1cc6b3da9220aace9da690731
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 26 21:36:52 2018 +0200

    RDMA: Fix dependencies for rdma_user_mmap_io

    The mlx4 driver produces a link error when it is configured
    as built-in while CONFIG_INFINIBAND_USER_ACCESS is set to =m:

    drivers/infiniband/hw/mlx4/main.o: In function `mlx4_ib_mmap':
    main.c:(.text+0x1af4): undefined reference to `rdma_user_mmap_io'

    The same function is called from mlx5, which already has a
    dependency to ensure we can call it, and from hns, which
    appears to suffer from the same problem.

    This adds the same dependency that mlx5 uses to the other two.

    Fixes: 6745d356ab39 ("RDMA/hns: Use rdma_user_mmap_io")
    Fixes: c282da4109e4 ("RDMA/mlx4: Use rdma_user_mmap_io")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Don Dutile <ddutile@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>