[netdrv] mlx5: Fix compilation warning in eq.c
Message-id: <20190417135957.11804-10-ahleihel@redhat.com>
Patchwork-id: 250256
O-Subject: [RHEL7.7 BZ 1695493 09/31] net/mlx5: Fix compilation warning in eq.c
Bugzilla: 1695493
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1695493
Upstream: net-next/master

commit 092ead48290b43afe5d548797c73b179dbaf6523
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Thu Mar 21 15:51:31 2019 -0700

    net/mlx5: Fix compilation warning in eq.c

    mlx5_eq_table_get_rmap is being used only when CONFIG_RFS_ACCEL is
    enabled, this patch fixes the below warning when CONFIG_RFS_ACCEL is
    disabled.

    drivers/.../mlx5/core/eq.c:903:18: [-Werror=missing-prototypes]
    error: no previous prototype for mlx5_eq_table_get_rmap

    Fixes: f2f3df550139 ("net/mlx5: EQ, Privatize eq_table and friends")
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>