[netdrv] nfp: bpf: improve handling for disabled BPF syscall
Message-id: <7e2986dcca0c64239180054d4962ca0011ea43cb.1510687151.git.linville@redhat.com>
Patchwork-id: 197912
O-Subject: [RHEL7 PATCH 008/206] nfp: bpf: improve handling for disabled BPF syscall
Bugzilla: 1454760 1454745
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1454745
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1454760

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14544377

I stumbled over a new warning during randconfig testing,
with CONFIG_BPF_SYSCALL disabled:

drivers/net/ethernet/netronome/nfp/nfp_net_offload.c: In function 'nfp_net_bpf_offload':
drivers/net/ethernet/netronome/nfp/nfp_net_offload.c:263:3: error: '*((void *)&res+4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/net/ethernet/netronome/nfp/nfp_net_offload.c:263:3: error: 'res.n_instr' may be used uninitialized in this function [-Werror=maybe-uninitialized]

As far as I can tell, this is a false positive caused by the compiler
getting confused about a function that is partially inlined, but it's
easy to avoid while improving the code:

The nfp_bpf_jit() stub helper for that configuration is unusual as it
is defined in a header file but not marked 'static inline'. By moving
the compile-time check into the caller using the IS_ENABLED() macro,
we can remove that stub and simplify the nfp_net_bpf_offload_prepare()
function enough to unconfuse the compiler.

Fixes: 7533fdc0f77f ("nfp: bpf: add hardware bpf offload")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b47c62c5de2bc43a26bcaca8d7a93bf9dee66ffe)
Signed-off-by: John W. Linville <linville@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>