[kernel] bpf: bpf_stackmap_copy depends on CONFIG_PERF_EVENTS
Message-id: <20180613214317.28803-18-jolsa@redhat.com>
Patchwork-id: 221537
O-Subject: [PATCH RHEL7.6 BZ1311586 017/386] bpf: bpf_stackmap_copy depends on CONFIG_PERF_EVENTS
Bugzilla: 1311586
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit b8cdc05173f05d212627b7aba7ec47fa334a79f2
Author: Alexei Starovoitov <ast@fb.com>
Date: Wed Mar 9 18:56:49 2016 -0800

description
===========
0-day bot reported build error:
kernel/built-in.o: In function `map_lookup_elem':
>> kernel/bpf/.tmp_syscall.o:(.text+0x329b3c): undefined reference to `bpf_stackmap_copy'
when CONFIG_BPF_SYSCALL is set and CONFIG_PERF_EVENTS is not.
Add weak definition to resolve it.
This code path in map_lookup_elem() is never taken
when CONFIG_PERF_EVENTS is not set.

Fixes: 557c0c6e7df8 ("bpf: convert stackmap to pre-allocation")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>