[scsi] scsi: qla2xxx: check for kstrtol() failure
Message-id: <20190801155618.12650-29-hmadhani@redhat.com>
Patchwork-id: 267806
O-Subject: [RHEL 7.8 e-stor PATCH 028/118] scsi: qla2xxx: check for kstrtol() failure
Bugzilla: 1729270
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Dan Carpenter <dan.carpenter@oracle.com>

Bugzilla 1729270

The error handling was unintentionally left out so it introduces a Smatch
static checker warning:

    drivers/scsi/qla2xxx/qla_attr.c:1655 qla2x00_port_speed_store()
    error: uninitialized symbol 'type'.

Fixes: a7b9ca7fc87a ("scsi: qla2xxx: Add support for setting port speed")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit b8870ec63676aba1d823f0b36c5f7e9929e57d23)
Signed-off-by: Himanshu Madhani <hmadhani@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>