[crypto] chelsio - select CRYPTO_GF128MUL
Message-id: <1524483887-17096-10-git-send-email-avynipad@redhat.com>
Patchwork-id: 210898
O-Subject: [RHEL7.6 PATCH BZ 1523191 09/27] crypto: chelsio - select CRYPTO_GF128MUL
Bugzilla: 1523191
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1523191
Conflicts: Minor conflict in Kconfig due to previously
backported upstream patch:
"02038fd crypto: Added Chelsio Menu to the Kconfig file"

commit d042566d8c704e1ecec370300545d4a409222e39
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 5 11:10:26 2017 +0100

    crypto: chelsio - select CRYPTO_GF128MUL

    Without the gf128mul library support, we can run into a link
    error:

    drivers/crypto/chelsio/chcr_algo.o: In function `chcr_update_tweak':
    chcr_algo.c:(.text+0x7e0): undefined reference to `gf128mul_x8_ble'

    This adds a Kconfig select statement for it, next to the ones we
    already have.

    Cc: <stable@vger.kernel.org>
    Fixes: b8fd1f4170e7 ("crypto: chcr - Add ctr mode and process large sg entries for cipher")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Herbert Xu <herbert.xu@redhat.com>
Cc: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>