[netdrv] mlx5e: Use the inner headers to determine tc/pedit offload limitation on decap flows
Message-id: <20190307094057.24725-3-ahleihel@redhat.com>
Patchwork-id: 245356
O-Subject: [RHEL7.7 BZ 1683975 02/17] net/mlx5e: Use the inner headers to determine tc/pedit offload limitation on decap flows
Bugzilla: 1683975
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1683975
Upstream: v5.0-rc6
Backport notes:
 - Had this compilation failure:
      drivers/net/ethernet/mellanox/mlx5/core/en_tc.c: In function modify_header_match_supported:
      drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:2187:12: error: actions redeclared as different kind of symbol
        LIST_HEAD(actions);
                  ^
      include/linux/list.h:22:19: note: in definition of macro LIST_HEAD
        struct list_head name = LIST_HEAD_INIT(name)
                         ^
      drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:2182:12: note: previous definition of actions was here
              u32 actions,
                  ^
      drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:2193:14: error: invalid operands to binary & (have struct list_head and int)
        if (actions & MLX5_FLOW_CONTEXT_ACTION_DECAP)

   This happened since the following commit was not backported yet to RHEL-7:
   2534f14a94c1 ("net/mlx5e: drop useless LIST_HEAD")
   Also we cannot backport this commit yet, since it requires this commit:
   244cd96adb5f ("net_sched: remove list_head from tc_action")

   So, instead we fix the compilation issue by renaming the new parameter to 'actions2'.

commit 1651925d403e077e3fc86f961905e27c6810e132
Author: Guy Shattah <sguy@mellanox.com>
Date:   Mon Jan 28 13:58:07 2019 +0000

    net/mlx5e: Use the inner headers to determine tc/pedit offload limitation on decap flows

    In packets that need to be decaped the internal headers
    have to be checked, not the external ones.

    Fixes: bdd66ac0aeed ("net/mlx5e: Disallow TC offloading of unsupported match/action combinations")
    Signed-off-by: Guy Shattah <sguy@mellanox.com>
    Reviewed-by: Or Gerlitz <ogerlitz@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>