[tools] perf tests: Fix compile when libunwind's unwind.h is available
Message-id: <20180419185703.28105-223-jolsa@redhat.com>
Patchwork-id: 210044
O-Subject: [PATCH RHEL7.6 BZ1540862 222/245] perf tests: Fix compile when libunwind's unwind.h is available
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit df90cc41d662ad5f700afc042df43e57ce1ed0a4
Author: Milian Wolff <milian.wolff@kdab.com>
Date: Wed Sep 6 17:02:09 2017 +0200

description
===========
When cross compiling perf and I want to link against a self-compiled
libunwind, I usually make the custom path where the libunwind headers
exist visible by adding the libunwind prefix to the include path when
compiling perf, i.e.:

~~~~~
$ ls $HOME/projects/compiled/other/include/
libunwind-coredump.h  libunwind.h         libunwind-x86_64.h
libunwind-common.h  libunwind-dynamic.h   libunwind-ptrace.h
unwind.h
$ make EXTRA_CFLAGS="-I$HOME/projects/compiled/other/include/
~~~~~~

Note the `unwind.h` header from libunwind which leads to compile
errors when compiling tests/dwarf-unwind.c, since it shadows perf's
util/unwind.h:

~~~~~
tests/dwarf-unwind.c:41:32: error: struct unwind_entry declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 static int unwind_entry(struct unwind_entry *entry, void *arg)
                                ^~~~~~~~~~~~
tests/dwarf-unwind.c: In function unwind_entry:
tests/dwarf-unwind.c:44:22: error: dereferencing pointer to incomplete type struct unwind_entry
  char *symbol = entry->sym ? entry->sym->name : NULL;
                      ^~
tests/dwarf-unwind.c: In function unwind_thread:
tests/dwarf-unwind.c:92:8: error: implicit declaration of function unwind__get_entries; did you mean unwind_entry? [-Werror=implicit-function-declaration]
  err = unwind__get_entries(unwind_entry, &cnt, thread,
        ^~~~~~~~~~~~~~~~~~~
        unwind_entry
tests/dwarf-unwind.c:92:8: error: nested extern declaration of unwind__get_entries [-Werror=nested-externs]
~~~~~~

Fix this compile error by specificing an explicit include of perf's
unwind.h in the util folder.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>