[tools] objtool, perf: Fix GCC 8 -Wrestrict error
Message-id: <20180620110202.6887-5-yauheni.kaliuta@redhat.com>
Patchwork-id: 222576
O-Subject: [PATCH RHEL7 RFC 4/4] objtool, perf: Fix GCC 8 -Wrestrict error
Bugzilla: 1593432
RH-Acked-by: Bruno Eduardo de Oliveira Meneguele <bmeneg@redhat.com>
RH-Acked-by: Josh Poimboeuf <jpoimboe@redhat.com>

From: Josh Poimboeuf <jpoimboe@redhat.com>

Starting with recent GCC 8 builds, objtool and perf fail to build with
the following error:

  ../str_error_r.c: In function 'str_error_r':
  ../str_error_r.c:25:3: error: passing argument 1 to restrict-qualified parameter aliases with argument 5 [-Werror=restrict]
     snprintf(buf, buflen, "INTERNAL ERROR: strerror_r(%d, %p, %zd)=%d", errnum, buf, buflen, err);

The code seems harmless, but there's probably no benefit in printing the
'buf' pointer in this situation anyway, so just remove it to make GCC
happy.

Reported-by: Laura Abbott <labbott@redhat.com>
Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
Tested-by: Laura Abbott <labbott@redhat.com>
Cc: Adrian Hunter <adrian.hunter@intel.com>
Cc: Jiri Olsa <jolsa@kernel.org>
Cc: Namhyung Kim <namhyung@kernel.org>
Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/r/20180316031154.juk2uncs7baffctp@treble
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 854e55ad289ef8888e7991f0ada85d5846f5afb9)
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>