[fs] NFSv4.1: work around -Wmaybe-uninitialized warning
Message-id: <0b0ff945340dff5eda99e0ebc7a2167a786f4005.1529399449.git.bcodding@redhat.com>
Patchwork-id: 222398
O-Subject: [RHEL7 fs PATCH 06/41] NFSv4.1: work around -Wmaybe-uninitialized warning
Bugzilla: 1418807
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Steve Dickson <SteveD@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

https://bugzilla.redhat.com/show_bug.cgi?id=1418807

commit 68a564006a21ae59c7c51b4359e2e8efa42ae4af
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 18 00:05:35 2016 +0200

    NFSv4.1: work around -Wmaybe-uninitialized warning

    A bugfix introduced a harmless gcc warning in nfs4_slot_seqid_in_use
    if we enable -Wmaybe-uninitialized again:

    fs/nfs/nfs4session.c:203:54: error: 'cur_seq' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    gcc is not smart enough to conclude that the IS_ERR/PTR_ERR pair
    results in a nonzero return value here. Using PTR_ERR_OR_ZERO()
    instead makes this clear to the compiler.

    The warning originally did not appear in v4.8 as it was globally
    disabled, but the bugfix that introduced the warning got backported
    to stable kernels which again enable it, and this is now the only
    warning in the v4.7 builds.

    Fixes: e09c978aae5b ("NFSv4.1: Fix Oopsable condition in server callback races")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Trond Myklebust <trond.myklebust@primarydata.com>
    Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>