[fs] xfs: fix xfs_mode_to_ftype() prototype
Message-id: <20180521171030.115571-39-bfoster@redhat.com>
Patchwork-id: 216612
O-Subject: [RHEL7.6 PATCH 038/136] xfs: fix xfs_mode_to_ftype() prototype
Bugzilla: 1579873
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

commit fd29f7af75b7adf250beccffa63746c6a88e2b74
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 18 12:39:21 2017 -0800

    xfs: fix xfs_mode_to_ftype() prototype

    A harmless warning just got introduced:

    fs/xfs/libxfs/xfs_dir2.h:40:8: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]

    Removing the 'const' modifier avoids the warning and has no
    other effect.

    Fixes: 1fc4d33fed12 ("xfs: replace xfs_mode_to_ftype table with switch statement")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>