[netdrv] bnxt_en: use SWITCHDEV_SET_OPS() for setting vf_rep_switchdev_ops
Message-id: <8a987708355faa33b2ea62c3e85d4bfa16a2ecfc.1510964611.git.jtoppins@redhat.com>
Patchwork-id: 199159
O-Subject: [RHEL7.5 061/105] bnxt_en: use SWITCHDEV_SET_OPS() for setting vf_rep_switchdev_ops
Bugzilla: 1459659
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

This fixes the build error:
struct net_device has no member named switchdev_ops

Reported-by: kbuild test robot <lkp@intel.com>
Fixes: c124a62ff2dd ("bnxt_en: add support for port_attr_get and and get_phys_port_name")
Signed-off-by: Sathya Perla <sathya.perla@broadcom.com>
Signed-off-by: Michael Chan <michael.chan@broadcom.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e408ebdc41aa53f0aa552132384daaa5f5c6301d)
Bugzilla: 1459659
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14573628
Tested: basic testing further testing being done by Broadcom and myself
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>