[usb] net1080: Remove unused function nc_dump_ttl()
Message-id: <1526649550-17190-217-git-send-email-torez@redhat.com>
Patchwork-id: 216014
O-Subject: [RHEL7.6 PATCH BZ1540721 216/681] net1080: Remove unused function nc_dump_ttl()
Bugzilla: 1540721
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1540721
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16352184
Testing: on local desktop and Dell Precision 5510 laptop

commit ce064e68a7e1ae525cd525fac3a6901591ddae3c
Author: Matthias Kaehlcke <mka@chromium.org>
Date:   Thu May 18 10:57:19 2017 -0700

    net1080: Remove unused function nc_dump_ttl()

    The function is not used, removing it fixes the following warning when
    building with clang:

    drivers/net/usb/net1080.c:271:20: error: unused function
        'nc_dump_ttl' [-Werror,-Wunused-function]

    Also remove the definition of TTL_THIS, which is only used in
    nc_dump_ttl()

    Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>