[hid] intel_ish-hid: fix potential uninitialized data usage
Message-id: <1510839526-11340-53-git-send-email-gtiwari@redhat.com>
Patchwork-id: 198302
O-Subject: [ PATCH BZ 1475903 52/59] HID: intel_ish-hid: fix potential uninitialized data usage
Bugzilla: 1475903
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1475903

commit 1260662fa3f293042fb0ae124c9a621f29f5bcab
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 18 22:21:40 2017 +0200

    HID: intel_ish-hid: fix potential uninitialized data usage

    gcc points out an uninialized pointer dereference that could happen
    if we ever get to recv_ishtp_cl_msg_dma() or recv_ishtp_cl_msg()
    with an empty &dev->read_list:

    drivers/hid/intel-ish-hid/ishtp/client.c: In function 'recv_ishtp_cl_msg_dma':
    drivers/hid/intel-ish-hid/ishtp/client.c:1049:3: error: 'cl' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    The warning only appeared in very few randconfig builds, as the
    spinlocks tend to prevent gcc from tracing the variables. I only
    saw it in configurations that had neither SMP nor LOCKDEP enabled.

    As we can see, we only enter the case if 'complete_rb' is non-NULL,
    and then 'cl' is known to point to complete_rb->cl. Adding another
    initialization to the same pointer is harmless here and makes it
    clear to the compiler that the behavior is well-defined.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>