[fs] NFSv4.x: hide array-bounds warning
Message-id: <2faeff6d1b996dfc5afdbc45343536e0b41800cb.1529399449.git.bcodding@redhat.com>
Patchwork-id: 222393
O-Subject: [RHEL7 fs PATCH 07/41] NFSv4.x: hide array-bounds warning
Bugzilla: 1418807
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>
RH-Acked-by: Steve Dickson <SteveD@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

https://bugzilla.redhat.com/show_bug.cgi?id=1418807

commit d55b352b01bc78fbc3d1bb650140668b87e58bf9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Nov 22 21:50:52 2016 +0100

    NFSv4.x: hide array-bounds warning

    A correct bugfix introduced a harmless warning that shows up with gcc-7:

    fs/nfs/callback.c: In function 'nfs_callback_up':
    fs/nfs/callback.c:214:14: error: array subscript is outside array bounds [-Werror=array-bounds]

    What happens here is that the 'minorversion == 0' check tells the
    compiler that we assume minorversion can be something other than 0,
    but when CONFIG_NFS_V4_1 is disabled that would be invalid and
    result in an out-of-bounds access.

    The added check for IS_ENABLED(CONFIG_NFS_V4_1) tells gcc that this
    really can't happen, which makes the code slightly smaller and also
    avoids the warning.

    The bugfix that introduced the warning is marked for stable backports,
    we want this one backported to the same releases.

    Fixes: 98b0f80c2396 ("NFSv4.x: Fix a refcount leak in nfs_callback_up_net")
    Cc: stable@vger.kernel.org # v3.7+
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>