[powerpc] pseries: Fix CONFIG_NUMA=n build
Message-id: <1533214317-22722-2-git-send-email-gduarte@redhat.com>
Patchwork-id: 225938
O-Subject: [RHEL7.6 PATCH BZ 1544437 8/6] powerpc/pseries: Fix CONFIG_NUMA=n build
Bugzilla: 1544437
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ 1544437
Upstream Status: 6c0a8f6b5a45ac892a763b6299bd3c5324fc5e02
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17517101
Tested: I boot tested on ppc64 lpar and ppc64le kvm guest.

commit 6c0a8f6b5a45ac892a763b6299bd3c5324fc5e02
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Tue May 8 14:59:56 2018 +1000

    powerpc/pseries: Fix CONFIG_NUMA=n build

    The build is failing with CONFIG_NUMA=n and some compiler versions:

      arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_online_cpu':
      hotplug-cpu.c:(.text+0x12c): undefined reference to `timed_topology_update'
      arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_cpu_remove':
      hotplug-cpu.c:(.text+0x400): undefined reference to `timed_topology_update'

    Fix it by moving the empty version of timed_topology_update() into the
    existing #ifdef block, which has the right guard of SPLPAR && NUMA.

    Fixes: cee5405da402 ("powerpc/hotplug: Improve responsiveness of hotplug change")
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>