[fs] gfs2/dir: avoid uninitialized variable warning
Message-id: <1511260817-1538-6-git-send-email-thuth@redhat.com>
Patchwork-id: 199678
O-Subject: [RHEL7.5 BZ 1500170 v2 PATCH 05/11] fs/gfs2/dir: avoid uninitialized variable warning
Bugzilla: 1500170
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>

Upstream Status: Based on 287980e49ffc0f6d911601e7e352a812ed27768e

There is a bogus warning about a potential uninitialized variable use in
fs/gfs2/dir.c when compiling with GCC 4.8 on s390x, because the compiler
does not figure out that the leaf number is never used if get_leaf_nr()
returns an error:

fs/gfs2/dir.c: In function 'get_first_leaf':
fs/gfs2/dir.c:809:9: error: 'leaf_no' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   error = get_leaf(dip, leaf_no, bh_out);
         ^
fs/gfs2/dir.c: In function 'dir_split_leaf.isra.18':
fs/gfs2/dir.c:1028:8: error: 'leaf_no' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  error = get_leaf(dip, leaf_no, &obh);
        ^

This patch fixes the issue by adapting the code according to the
following upstream patch:

    commit 287980e49ffc0f6d911601e7e352a812ed27768e
    Author: Arnd Bergmann <arnd@arndb.de>
    Date:   Fri May 27 23:23:25 2016 +0200
    Title: remove lots of IS_ERR_VALUE abuses

Unfortunately, the original patch was too big to include it here in
total, so I just picked the required hunk for this fix.

Signed-off-by: Thomas Huth <thuth@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>