[input] synaptics-rmi4 - select 'SERIO' when needed
Message-id: <20180417141301.4870-58-benjamin.tissoires@redhat.com>
Patchwork-id: 209699
O-Subject: [PATCH RHEL7.6 057/141] Input: synaptics-rmi4 - select 'SERIO' when needed
Bugzilla: 1554926
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Aristeu Rozanski <aris@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1554926
Upstream: since v4.10
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15808598
Test: by me on a t450s, X280 and the IT folks on the X1 Carbon 6 and T480

commit 413d37326700aaf708730b940b04192c36e13ef4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 7 09:59:21 2017 -0800

    Input: synaptics-rmi4 - select 'SERIO' when needed

    With CONFIG_SERIO=m, we get a build error for the rmi4-f03 driver,
    added in linux-4.10:

    warning: (HID_RMI) selects RMI4_F03 which has unmet direct dependencies (!UML && INPUT && RMI4_CORE && (SERIO=y || RMI4_CORE=SERIO))
    drivers/input/built-in.o: In function `rmi_f03_attention':
    rmi_f03.c:(.text+0xcfe0): undefined reference to `serio_interrupt'
    rmi_f03.c:(.text+0xd055): undefined reference to `serio_interrupt'
    drivers/input/built-in.o: In function `rmi_f03_remove':
    rmi_f03.c:(.text+0xd115): undefined reference to `serio_unregister_port'
    drivers/input/built-in.o: In function `rmi_f03_probe':
    rmi_f03.c:(.text+0xd209): undefined reference to `__serio_register_port'

    An earlier patch tried to fix this, but missed the HID_RMI driver that
    does a 'select' on the F03 backend.

    This adds a hidden Kconfig symbol that enforces 'serio' to be enabled
    when RMI4-F03 is, which covers all cases.

    Fixes: d7ddad0acc4a ("Input: synaptics-rmi4 - fix F03 build error when serio is module")
    Fixes: c5e8848fc98e ("Input: synaptics-rmi4 - add support for F03")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>