[netdrv] mlxsw: spectrum: Propagate extack further for bridge enslavements
Message-id: <20180601184800.22484-51-ivecera@redhat.com>
Patchwork-id: 220010
O-Subject: [RHEL7.6 PATCH 049/224] mlxsw: spectrum: Propagate extack further for bridge enslavements
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Backport note:
- Using dev_err() instead of NL_SET_ERR_MSG() due to absence of extack
  support in RHEL

Upstream commit(s):
commit 9b63ef88d3a16d67afbe7916625289650e9f30d9
Author: Ido Schimmel <idosch@mellanox.com>
Date:   Sun Oct 8 11:57:56 2017 +0200

    mlxsw: spectrum: Propagate extack further for bridge enslavements

    The code that actually takes care of bridge offload introduces a few
    more non-trivial constraints with regards to bridge enslavements.
    Propagate extack there to indicate the reason.

    $ ip link add link enp1s0np1 name enp1s0np1.10 type vlan id 10
    $ ip link add link enp1s0np1 name enp1s0np1.20 type vlan id 20
    $ ip link add name br0 type bridge
    $ ip link set dev enp1s0np1.10 master br0
    $ ip link set dev enp1s0np1.20 master br0
    Error: spectrum: Can not bridge VLAN uppers of the same port.

    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Acked-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>