[fs] xfs: fix string handling in label get/set functions
Message-id: <f835ccde-4288-42e2-6a8f-b3e6b93c2c10@redhat.com>
Patchwork-id: 221356
O-Subject: [RHEL7 PATCH 6/4] xfs: fix string handling in label get/set functions
Bugzilla: 1322930
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Brian Foster <bfoster@redhat.com>

Bug: 1322930 - [RFE] Allow xfs_admin to modify labels on mounted filesystem
Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16672479
Testing: local xfstests with (pending) online label test & updated xfs_io

Upstream commit:

commit 4bb8b65a04273c5acd6d1e08e08b757b4e6f4913
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jun 5 19:42:45 2018 -0700

    xfs: fix string handling in label get/set functions

    [sandeen: fix subject, avoid copy-out of uninit data in getlabel]

    gcc-8 reports two warnings for the newly added getlabel/setlabel code:

    fs/xfs/xfs_ioctl.c: In function 'xfs_ioc_getlabel':
    fs/xfs/xfs_ioctl.c:1822:38: error: argument to 'sizeof' in 'strncpy' call is the same expression as the source; did you mean
      strncpy(label, sbp->sb_fname, sizeof(sbp->sb_fname));
                                          ^
    In function 'strncpy',
        inlined from 'xfs_ioc_setlabel' at /git/arm-soc/fs/xfs/xfs_ioctl.c:1863:2,
        inlined from 'xfs_file_ioctl' at /git/arm-soc/fs/xfs/xfs_ioctl.c:1918:10:
    include/linux/string.h:254:9: error: '__builtin_strncpy' output may be truncated copying 12 bytes from a string of length 12
      return __builtin_strncpy(p, q, size);

    In both cases, part of the problem is that one of the strncpy()
    arguments is a fixed-length character array with zero-padding rather
    than a zero-terminated string. In the first one case, we also get an
    odd warning about sizeof-pointer-memaccess, which doesn't seem right
    (the sizeof is for an array that happens to be the same as the second
    strncpy argument).

    To work around the bogus warning, I use a plain 'XFSLABEL_MAX' for
    the strncpy() length when copying the label in getlabel. For setlabel(),
    using memcpy() with the correct length that is already known avoids
    the second warning and is slightly simpler.

    In a related issue, it appears that we accidentally skip the trailing
    \0 when copying a 12-character label back to user space in getlabel().
    Using the correct sizeof() argument here copies the extra character.

    Link: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85602
    Fixes: f7664b31975b ("xfs: implement online get/set fs label")
    Cc: Eric Sandeen <sandeen@redhat.com>
    Cc: Martin Sebor <msebor@gmail.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Eric Sandeen <sandeen@redhat.com>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>