[security] keys: Fix an error code in request_master_key()
Message-id: <150905513350.6336.17334090745911075990.stgit@warthog.procyon.org.uk>
Patchwork-id: 195165
O-Subject: [RHEL7.5 PATCH 01/55] KEYS: Fix an error code in request_master_key()
Bugzilla: 1466457
CVE: CVE-2015-8539 CVE-2017-7472
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>
RH-Acked-by: Bruno Eduardo de Oliveira Meneguele <brdeoliv@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>

Bugzilla: 1466457
Upstream Status: Linus
Build Info: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=14378351
Tested: keyutils testsuite and all LTP key and keyctl tests

commit 57cb17e764ba0aaa169d07796acce54ccfbc6cae
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date: Thu Feb 9 17:17:52 2017 +0000

    KEYS: Fix an error code in request_master_key()

    This function has two callers and neither are able to handle a NULL
    return.  Really, -EINVAL is the correct thing return here anyway.  This
    fixes some static checker warnings like:

	    security/keys/encrypted-keys/encrypted.c:709 encrypted_key_decrypt()
	    error: uninitialized symbol 'master_key'.

    Fixes: 7e70cb497850 ("keys: add new key-type encrypted")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Mimi Zohar <zohar@linux.vnet.ibm.com>
    Signed-off-by: James Morris <james.l.morris@oracle.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>