[infiniband] ib/uverbs: clean up INIT_UDATA_BUF_OR_NULL usage
Message-id: <20180412051314.17576-4-ddutile@redhat.com>
Patchwork-id: 208969
O-Subject: [PATCH RHEL-7.6 v2 003/318] IB/uverbs: clean up INIT_UDATA_BUF_OR_NULL usage
Bugzilla: 1549856
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1549856

commit 12f727721eee61b3d19dedb95cb893b2baa9fe41
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 6 23:34:25 2017 +0200

    IB/uverbs: clean up INIT_UDATA_BUF_OR_NULL usage

    We get a harmless warning about the fact that we use the result of a
    multiplication as a condition:

    drivers/infiniband/core/uverbs_main.c: In function 'ib_uverbs_write':
    drivers/infiniband/core/uverbs_main.c:787:40: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
    drivers/infiniband/core/uverbs_main.c:787:117: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
    drivers/infiniband/core/uverbs_main.c:790:50: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
    drivers/infiniband/core/uverbs_main.c:790:151: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]

    This avoids the problem by using an inline function in place of
    the macro.

    Fixes: a96e4e2ffe43 ("IB/uverbs: New macro to set pointers to NULL if length is 0 in INIT_UDATA()")
    Suggested-by: Christoph Hellwig <hch@infradead.org>
    Link: https://patchwork.kernel.org/patch/9940777/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>