[net] netfilter: ipset: The unnamed union initialization may lead to compilation error
Message-id: <401d9bb43dd6b2e4f51f1c6f5188bd3ffd05b059.1526056798.git.sbrivio@redhat.com>
Patchwork-id: 214545
O-Subject: [RHEL7.6 net 031/149] netfilter: ipset: The unnamed union initialization may lead to compilation error
Bugzilla: 1557599
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1557599
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16136344
Tested:
	- ipset 6.38 test suite with:
		- patch to get match_target tests running on RHEL,
		  http://patchwork.ozlabs.org/patch/910306/
		- RHEL7.5 iptables-1.4.21 patched to include commit 6d9ae2952a44
		  ("xtables: SET target: Add mapping of meta informations
		  (skbinfo ipset extension)"), RPMs available at:
			http://file.rdu.redhat.com/~sbrivio/iptables-1.4.21-ipset_skbinfo/
	- basic iptables functionality tests
	- network CI tests: https://beaker.engineering.redhat.com/jobs/2469259

commit 1a869205c75cb222263fa04f200485ffbe9eaadf
Author: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
Date:   Fri Oct 18 11:41:57 2013 +0200

    netfilter: ipset: The unnamed union initialization may lead to compilation error

    The unnamed union should be possible to be initialized directly, but
    unfortunately it's not so:

    /usr/src/ipset/kernel/net/netfilter/ipset/ip_set_hash_netnet.c: In
    function ?hash_netnet4_kadt?:
    /usr/src/ipset/kernel/net/netfilter/ipset/ip_set_hash_netnet.c:141:
    error: unknown field ?cidr? specified in initializer

    Reported-by: Husnu Demir <hdemir@metu.edu.tr>
    Signed-off-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>