[hwtracing] intel_th: INTEL_TH should depend on HAS_DMA
Message-id: <20190311092113.21814-45-jolsa@redhat.com>
Patchwork-id: 245644
O-Subject: [PATCH RHEL7 BZ1514700 044/125] intel_th: INTEL_TH should depend on HAS_DMA
Bugzilla: 1514700
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1514700
https://bugzilla.redhat.com/show_bug.cgi?id=1514700

upstream
========
commit 8d0439369d98aa23c8e20a49b69d90b1efab2797
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date: Tue Dec 22 17:25:16 2015 +0200

description
===========
If NO_DMA=y:

    ERROR: "dma_free_coherent" [drivers/hwtracing/intel_th/intel_th_msu.ko] undefined!
    ERROR: "dma_alloc_coherent" [drivers/hwtracing/intel_th/intel_th_msu.ko] undefined!
    ERROR: "dma_supported" [drivers/hwtracing/intel_th/intel_th.ko] undefined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Jan Stancek <jstancek@redhat.com>