[netdrv] uapi/linux/if_tunnel.h: include linux/if.h, linux/ip.h and linux/in6.h
Message-id: <20171013205835.26049-240-ivecera@redhat.com>
Patchwork-id: 193593
O-Subject: [RHEL7.5 PATCH 239/245] include/uapi/linux/if_tunnel.h: include linux/if.h, linux/ip.h and linux/in6.h
Bugzilla: 1486860
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1486860

Upstream commit(s):
commit 1fe8e0f074c77aa41aaa579345a9e675acbebfa9
Author: Mikko Rapeli <mikko.rapeli@iki.fi>
Date:   Mon Aug 22 20:32:39 2016 +0200

    include/uapi/linux/if_tunnel.h: include linux/if.h, linux/ip.h and linux/in6.h

    Fixes userspace compilation errors like:

    error: field iph has incomplete type
    error: field prefix has incomplete type

    Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>