[tools] perf strbuf: Match va_{add, copy} with va_end
Message-id: <20190311094227.31342-82-jolsa@redhat.com>
Patchwork-id: 245830
O-Subject: [PATCH RHEL7 BZ1680074 081/170] perf strbuf: Match va_{add, copy} with va_end
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit ce49d8436cffa9b7a6a5f110879d53e89dbc6746
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:10 2018 -0400

description
===========
Ensure that all code paths in strbuf_addv() call va_end() on the
ap_saved copy that was made.

Fixes the following coverity complaint:

  Error: VARARGS (CWE-237): [#def683]
  tools/perf/util/strbuf.c:106: missing_va_end: va_end was not called
  for "ap_saved".

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>