[usb] r8152: Remove unused function usb_ocp_read()
Message-id: <1526649550-17190-216-git-send-email-torez@redhat.com>
Patchwork-id: 215988
O-Subject: [RHEL7.6 PATCH BZ1540721 215/681] r8152: Remove unused function usb_ocp_read()
Bugzilla: 1540721
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1540721
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16352184
Testing: on local desktop and Dell Precision 5510 laptop

commit db646cc0aefbc5da0b9699ed40d4402e01245f57
Author: Matthias Kaehlcke <mka@chromium.org>
Date:   Thu May 18 10:45:33 2017 -0700

    r8152: Remove unused function usb_ocp_read()

    The function is not used, removing it fixes the following warning when
    building with clang:

    drivers/net/usb/r8152.c:825:5: error: unused function 'usb_ocp_read'
        [-Werror,-Wunused-function]

    Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>