[kernel] mlx5: Fix build break when CONFIG_SMP=n
Message-id: <1549457075-6314-160-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240118
O-Subject: [RHEL7.7 BZ 1642498 159/729] net/mlx5: Fix build break when CONFIG_SMP=n
Bugzilla: 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Upstream: v4.17-rc7
Backport notes:
 - Context conflict due to W/A previously added in commit
   ec188fe33ba9 ("[kernel] mlx5: Fix get vector affinity helper function")
 - Now that the call to function 'irq_to_desc' has been removed, we can also
   remove the W/A that was added to RHEL-7.

commit e3ca34880652250f524022ad89e516f8ba9a805b
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Mon May 14 15:38:10 2018 -0700

    net/mlx5: Fix build break when CONFIG_SMP=n

    Avoid using the kernel's irq_descriptor and return IRQ vector affinity
    directly from the driver.

    This fixes the following build break when CONFIG_SMP=n

    include/linux/mlx5/driver.h: In function mlx5_get_vector_affinity_hint:
    include/linux/mlx5/driver.h:1299:13: error:
            struct irq_desc has no member named affinity_hint

    Fixes: 6082d9c9c94a ("net/mlx5: Fix mlx5_get_vector_affinity function")
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    CC: Randy Dunlap <rdunlap@infradead.org>
    CC: Guenter Roeck <linux@roeck-us.net>
    CC: Thomas Gleixner <tglx@linutronix.de>
    Tested-by: Israel Rukshin <israelr@mellanox.com>
    Reported-by: kbuild test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Thomas Gleixner <tglx@linutronix.de>
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>