[netdrv] mlxsw: spectrum: Add extack messages for enslave failures
Message-id: <20180601184800.22484-49-ivecera@redhat.com>
Patchwork-id: 220005
O-Subject: [RHEL7.6 PATCH 047/224] mlxsw: spectrum: Add extack messages for enslave failures
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Backport note:
- Using dev_err() instead of NL_SET_ERR_MSG() due to absence of extack
  support in RHEL

Upstream commit(s):
commit e58376e1df2aaffbf12753959142a50f824c46ea
Author: David Ahern <dsahern@gmail.com>
Date:   Wed Oct 4 17:48:51 2017 -0700

    mlxsw: spectrum: Add extack messages for enslave failures

    mlxsw fails device enslavement for a number of reasons. Use the extack
    facility to return an error message to the user stating why the enslave
    is failing.

    Messages are prefixed with "spectrum" so users know it is a constraint
    imposed by the hardware driver. For example:
        $ ip li add br0.11 link br0 type vlan id 11
        $ ip li set swp11 master br0
        Error: spectrum: Enslaving a port to a device that already has an upper device is not supported.

    Signed-off-by: David Ahern <dsahern@gmail.com>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Tested-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>