[net] xfrm: checkpatch errors with foo * bar
Message-id: <20180104124823.10899-2-brdeoliv@redhat.com>
Patchwork-id: 203172
O-Subject: [RHEL7 net PATCH v2 1/5] xfrm: checkpatch errors with foo * bar
Bugzilla: 1460790
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1460790
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14867049
Test: https://beaker.engineering.redhat.com/jobs/2233184 and by Paul
    Wouters (BZ reporter)

From: Weilong Chen <chenweilong@huawei.com>
Date: Tue, 24 Dec 2013 09:43:47 +0800

    This patch clean up some checkpatch errors like this:
    ERROR: "foo * bar" should be "foo *bar"
    ERROR: "(foo*)" should be "(foo *)"

    Signed-off-by: Weilong Chen <chenweilong@huawei.com>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

(cherry picked from commit 3e94c2dcfd7ca297bd7e0a8d96be1e76dec711a3)
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>