[netdrv] cxgb4: avoid memcpy beyond end of source buffer
Message-id: <1524289424-31421-85-git-send-email-avynipad@redhat.com>
Patchwork-id: 210545
O-Subject: [RHEL7.6 PATCH v2 084/110] net: cxgb4: avoid memcpy beyond end of source buffer
Bugzilla: 1523151
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1523151

commit 1a91649fd35ff53a646981e212496f1ae92a8487
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 2 16:18:37 2018 +0100

    net: cxgb4: avoid memcpy beyond end of source buffer

    Building with link-time-optimizations revealed that the cxgb4 driver does
    a fixed-size memcpy() from a variable-length constant string into the
    network interface name:

    In function 'memcpy',
        inlined from 'cfg_queues_uld.constprop' at drivers/net/ethernet/chelsio/cxgb4/cxgb4_uld.c:335:2,
        inlined from 'cxgb4_register_uld.constprop' at drivers/net/ethernet/chelsio/cxgb4/cxgb4_uld.c:719:9:
    include/linux/string.h:350:3: error: call to '__read_overflow2' declared with attribute error: detected read beyond size of object passed as 2nd parameter
       __read_overflow2();
       ^

    I can see two equally workable solutions: either we use a strncpy() instead
    of the memcpy() to stop at the end of the input, or we make the source buffer
    fixed length as well. This implements the latter.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>