[infiniband] iw_cxgb4: add INFINIBAND_ADDR_TRANS dependency
Message-id: <1548854283-20896-8-git-send-email-avynipad@redhat.com>
Patchwork-id: 239467
O-Subject: [RHEL7.7 BZ 1642419 BZ 1597594 07/25] iw_cxgb4: add INFINIBAND_ADDR_TRANS dependency
Bugzilla: 1597594 1642419
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642419
Bugzilla: http://bugzilla.redhat.com/1597594

commit e4b1672ac0a54c7740cbc4ff39dfdc56182236cb
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 30 23:58:18 2018 +0200

    iw_cxgb4: add INFINIBAND_ADDR_TRANS dependency

    The newly added fill_res_ep_entry function fails to link if
    CONFIG_INFINIBAND_ADDR_TRANS is not set:

    drivers/infiniband/hw/cxgb4/restrack.o: In function `fill_res_ep_entry':
    restrack.c:(.text+0x3cc): undefined reference to `rdma_res_to_id'
    restrack.c:(.text+0x3d0): undefined reference to `rdma_iw_cm_id'

    This adds a Kconfig dependency for the driver.

    Fixes: 116aeb887371 ("iw_cxgb4: provide detailed provider-specific CM_ID information")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Greg Thelen <gthelen@google.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Cc: Kamal Heib <kheib@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>