[scsi] cxgb4i: fix thermal configuration dependencies
Message-id: <1548924676-13143-4-git-send-email-avynipad@redhat.com>
Patchwork-id: 239746
O-Subject: [RHEL7.7 BZ 1642436 v2 3/4] scsi: cxgb4i: fix thermal configuration dependencies
Bugzilla: 1642436
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642436

commit 8d0bb86e2cf6c96d88c3de56a2a29329872c454d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 2 16:35:23 2018 +0100

    scsi: cxgb4i: fix thermal configuration dependencies

    I fixed a bug by adding a dependency in the network driver, but that fix
    caused a related bug in the SCSI driver:

    WARNING: unmet direct dependencies detected for CHELSIO_T4
      Depends on [m]: NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_CHELSIO [=y] && PCI [=y] && (IPV6 [=y] || IPV6 [=y]=n) && (THERMAL [=m] || !THERMAL [=m])
      Selected by [y]:
      - SCSI_CXGB4_ISCSI [=y] && SCSI_LOWLEVEL [=y] && SCSI [=y] && PCI [=y] && INET [=y] && (IPV6 [=y] || IPV6 [=y]=n)
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.o: In function `cxgb4_thermal_init':
    cxgb4_thermal.c:(.text+0x158): undefined reference to `thermal_zone_device_register'
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.o: In function `cxgb4_thermal_remove':
    cxgb4_thermal.c:(.text+0x1d8): undefined reference to `thermal_zone_device_unregister'
    /git/arm-soc/Makefile:1042: recipe for target 'vmlinux' failed

    The same dependency needs to be propagated here to make it work correctly
    with CONFIG_THERMAL=m and SCSI_CXGB4_ISCSI=y. That change by itself causes
    another problem with a circular dependency, as we use 'select NETDEVICES'.
    This is something we really should not do anyway, as a driver symbol should
    never select another major subsystem, so let's turn that into a 'depends
    on'. I don't see any downsides of that, as NETDEVICES is only disabled in
    rather obscure cases that are not relevant to the users of cxgb4i.

    Fixes: e70a57fa59bb ("cxgb4: fix thermal configuration dependencies")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Ewan D. Milne <emilne@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: Maurizio Lombardi <mlombard@redhat.com>
Cc: Neil Horman <nhorman@redhat.com>
Cc: Rob Evers <revers@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>