[net] ipv4: avoid unused variable warning for sysctl
Message-id: <022c9d35bde0db10d84ceaa06bc4467300b98b55.1521735497.git.sdubroca@redhat.com>
Patchwork-id: 207265
O-Subject: [PATCH RHEL7.6 net 2/2] net: ipv4: avoid unused variable warning for sysctl
Bugzilla: 1541250
RH-Acked-by: Xin Long <lxin@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1541250
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=15584502
Tested: test setting net.ipv4.route.min_pmtu to different values

commit 773daa3caf5d3f87fdb1ab43e9c1b367a38fa394
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Feb 28 14:32:48 2018 +0100

    net: ipv4: avoid unused variable warning for sysctl

    The newly introudced ip_min_valid_pmtu variable is only used when
    CONFIG_SYSCTL is set:

    net/ipv4/route.c:135:12: error: 'ip_min_valid_pmtu' defined but not used [-Werror=unused-variable]

    This moves it to the other variables like it, to avoid the harmless
    warning.

    Fixes: c7272c2f1229 ("net: ipv4: don't allow setting net.ipv4.route.min_pmtu below 68")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Sabrina Dubroca <sd@queasysnail.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Sabrina Dubroca <sdubroca@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>