[crypto] keys: The RSA public key algorithm needs to select MPILIB
Message-id: <150905520032.6336.14582256849851525626.stgit@warthog.procyon.org.uk>
Patchwork-id: 195173
O-Subject: [RHEL7.5 PATCH 08/55] KEYS: The RSA public key algorithm needs to select MPILIB
Bugzilla: 1503242
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>
RH-Acked-by: Bruno Eduardo de Oliveira Meneguele <brdeoliv@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>

Bugzilla: 1503242
Upstream Status: Linus
Build Info: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=14378351
Tested: keyutils testsuite and all LTP key and keyctl tests

commit dbed71416332d24e4e9ba26dcf90cd86a93c06f1
Author: David Howells <dhowells@redhat.com>
Date:   Fri Nov 1 15:11:14 2013 +0000

    KEYS: The RSA public key algorithm needs to select MPILIB

    The RSA public key algorithm needs to select MPILIB directly in Kconfig as the
    'select' directive is not recursive and is thus MPILIB is not enabled by
    selecting MPILIB_EXTRA.

    Without this, the following errors can occur:

            crypto/built-in.o: In function `RSA_verify_signature':
            rsa.c:(.text+0x1d347): undefined reference to `mpi_get_nbits'
            rsa.c:(.text+0x1d354): undefined reference to `mpi_get_nbits'
            rsa.c:(.text+0x1d36e): undefined reference to `mpi_cmp_ui'
            rsa.c:(.text+0x1d382): undefined reference to `mpi_cmp'
            rsa.c:(.text+0x1d391): undefined reference to `mpi_alloc'
            rsa.c:(.text+0x1d3b0): undefined reference to `mpi_powm'
            rsa.c:(.text+0x1d3c3): undefined reference to `mpi_free'
            rsa.c:(.text+0x1d3d8): undefined reference to `mpi_get_buffer'
            rsa.c:(.text+0x1d4d4): undefined reference to `mpi_free'
            rsa.c:(.text+0x1d503): undefined reference to `mpi_get_nbits'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David Howells <dhowells@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>