[sound] alsa: hda/tegra: avoid build error without CONFIG_PM
Message-id: <15526609954549336-4-patchset-jkysela@redhat.com>
Patchwork-id: 246177
O-Subject: [RHEL 7.7 PATCH 03/10] ALSA: hda/tegra: avoid build error without CONFIG_PM
Bugzilla: 1517622
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

The #ifdef protection around the PM functions is wrong, leading to
a failed reference in some configurations:

sound/pci/hda/hda_tegra.c: In function 'hda_tegra_runtime_suspend':
sound/pci/hda/hda_tegra.c:273:2: error: implicit declaration of function 'hda_tegra_disable_clocks'; did you mean 'hda_tegra_enable_clocks'? [-Werror=implicit-function-declaration]

Better remove the #ifdefs entirely and rely on the compiler silently
dropping unused functions marked __maybe_unused.

Fixes: 707e0759f2f4 ("ALSA: hda/tegra: implement runtime suspend/resume")
Acked-by: Thierry Reding <treding@nvidia.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 7472946915aad1cc751cce3edfd8c1fd5c845834)
Bugzilla: 1517622
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>