[kernel] bpf: avoid -Wmaybe-uninitialized warning
Message-id: <20181023114647.12260-35-jolsa@redhat.com>
Patchwork-id: 231721
O-Subject: [PATCH RHEL7.7 BZ1640092 34/68] bpf: avoid -Wmaybe-uninitialized warning
Bugzilla: 1640092
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>

Bugzilla: 1640092
https://bugzilla.redhat.com/show_bug.cgi?id=1640092

upstream
========
commit dc3b8ae9d271897e09b27fa4e4e0000de98590d1
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri May 25 23:33:20 2018 +0200

description
===========
The stack_map_get_build_id_offset() function is too long for gcc to track
whether 'work' may or may not be initialized at the end of it, leading
to a false-positive warning:

kernel/bpf/stackmap.c: In function 'stack_map_get_build_id_offset':
kernel/bpf/stackmap.c:334:13: error: 'work' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This removes the 'in_nmi_ctx' flag and uses the state of that variable
itself to see if it got initialized.

Fixes: bae77c5eb5b2 ("bpf: enable stackmap with build_id in nmi context")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>