[fs] mm,fs,dax: mark dax_iomap_pmd_fault as const
Message-id: <1508380559-214859-5-git-send-email-sandeen@redhat.com>
Patchwork-id: 194535
O-Subject: [RHEL7.5 PATCH 04/14] mm,fs,dax: mark dax_iomap_pmd_fault as const
Bugzilla: 1492058
RH-Acked-by: Bill O'Donnell <billodo@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: 1492058
Upstream Status: Committed upstream
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=14297047
Tested: Locally with fstests

Backport of the following upstream commit:

commit 01cddfe99008da87dd4f6b8fbfa31e09257b9133
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 27 14:26:44 2017 -0800

    mm,fs,dax: mark dax_iomap_pmd_fault as const

    The two alternative implementations of dax_iomap_fault have different
    prototypes, and one of them is obviously wrong as seen from this build
    warning:

      fs/dax.c: In function 'dax_iomap_fault':
      fs/dax.c:1462:35: error: passing argument 2 of 'dax_iomap_pmd_fault' discards 'const' qualifier from pointer target typ

    This marks the argument 'const' as in all the related functions.

    Fixes: a2d581675d48 ("mm,fs,dax: change ->pmd_fault to ->huge_fault")
    Link: http://lkml.kernel.org/r/20170227203349.3318733-1-arnd@arndb.de
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>