[gpu] drm/i915: avoid potential uninitialized variable use
Message-id: <20171205213234.7258-36-rclark@redhat.com>
Patchwork-id: 201478
O-Subject: [RHEL7 drm 35/37] drm/i915: avoid potential uninitialized variable use
Bugzilla: 1520639
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1520639
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14665752
Upstream: since drm-for-v4.15

commit 83482ca3b4fe7312bf3d1f25c7a4e9ff66585eab

Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Thu Oct 5 14:08:26 2017 +0200
Commit:     Daniel Vetter <daniel.vetter@ffwll.ch>
CommitDate: Thu Oct 5 15:32:15 2017 +0200

    drm/i915: avoid potential uninitialized variable use

    One of the recent changes introduced a warning about
    undefined behavior in the sanity checking:

    drivers/gpu/drm/i915/intel_ddi.c: In function 'intel_ddi_hdmi_level':
    drivers/gpu/drm/i915/intel_ddi.c:654:6: error: 'n_hdmi_entries' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    It seems that the new cnl specific get_buf_trans functions
    can return uninitialized data if the voltage level is set
    to an unexpected value. This changes the code to always return
    '1' in that error case, which seems like the safest choice
    as we use one less than the number as an array index later on.

    Fixes: cc9cabfdec38 ("drm/i915/cnl: Move voltage check into ddi buf trans functions.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    [danvet: shut up gcc comment added.]
    Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
    Link: https://patchwork.freedesktop.org/patch/msgid/20171005120835.437022-1-arnd@arndb.de

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>