[kernel] nvmem: include linux/err.h from header
Message-id: <1512650446-15556-105-git-send-email-jeremymc@redhat.com>
Patchwork-id: 201729
O-Subject: [PATCH RHEL7.5 v3 104/113] nvmem: include linux/err.h from header
Bugzilla: 1172010
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jeremy McNicoll <jeremymc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1172010

commit 42a6e0996084972574e0a2b23e7326b78b0f64c5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 10 13:22:50 2017 +0200

    nvmem: include linux/err.h from header

    The new support for nvmem devices from the rtc layer caused a build
    error in some configurations:

    include/linux/nvmem-provider.h: In function 'nvmem_register':
    include/linux/nvmem-provider.h:51:9: error: implicit declaration of function 'ERR_PTR' [-Werror=implicit-function-declaration]

    This adds the missing include to ensure we can always include
    the header.

    Fixes: 697e5a47aa12 ("rtc: add generic nvmem support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
    Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>

Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>