[wireless] Correct strange error in Makefiles for building modules in separate directories
Message-id: <20191007135317.27379-1-nhorman@redhat.com>
Patchwork-id: 276911
O-Subject: [RHEL7.8 PATCH] Correct strange error in Makefiles for building modules in separate directories
Bugzilla: 1753927
RH-Acked-by: Jan Stancek <jstancek@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

From: Neil Horman <nhorman@hmswarspite.think-freely.org>

Jan Stancek recently reported an error in building the rhel7 kernel with an
out-of-tree destination object directory:

/root/rpmbuild/BUILD/kernel-3.10.0-1095.el7/linux-3.10.0-1095.el7.x86_64

...
/root/rpmbuild/BUILD/kernel-3.10.0-1095.el7/linux-3.10.0-1095.el7.x86_64/drivers/net/wireless/intel/iwlwifi/dvm/main.c:34:29: fatal error: iwl-eeprom-read.h: No such file or directory
 #include "iwl-eeprom-read.h"

The gcc command line revealed that, even though the Makefile included the
directory this header was in, the kernel build scripts stripped the -I option
off that directive, leading the path to not be used, and the header to not get
found.

Its a very strange error, and one that only seems to occur in the iwlwifi/dvm
and mvm directories (other directories have simmilar include directives and get
processed properly)

Upstream seems to have inadvertently fixed the problem, but the build system has
undergone significant changes since RHEL7, and we found that the problem can be
resolved by removing the whitespace between the -I and the path of the include
directive in those makefiles (which other directories also do)

Given the age of RHEL7, its impending move to maintenence mode, the limited use
of this particular use case, and the invasiveness of making any major change to
the build system for RHEL7, I thought it would safer to simply correct this
issue by adjusting the makefiles where the error specifically occurs

BZ: 1753927
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23759193
Testing: Tested by myself and jstancek with good results
Signed-off-by: Jan Stancek <jstancek@redhat.com>