[infiniband] ib/ucm: fix UCM link error
Message-id: <20190103092638.12749-219-kheib@redhat.com>
Patchwork-id: 236656
O-Subject: [PATCH RHEL-7.7 218/233] IB/ucm: fix UCM link error
Bugzilla: 1655920
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1655920

commit 845b397a7771f2d3504beff5521f452be0d22eec
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Aug 21 16:20:44 2018 +0200

    IB/ucm: fix UCM link error

    Building UCM with CONFIG_INFINIBAND_USER_ACCESS=m results in a
    set of link errors including:

    drivers/infiniband/core/ucm.o: In function `ib_ucm_event_handler':
    ucm.c:(.text+0x6dc): undefined reference to `ib_copy_path_rec_to_user'
    drivers/infiniband/core/ucma.o: In function `ucma_event_handler':
    ucma.c:(.text+0xdc0): undefined reference to `ib_copy_ah_attr_to_user'

    To get it to build-test again, this makes the option itself a
    tristate, which lets Kconfig figure out the dependency correctly.

    Fixes: 486edfb1039d ("IB/ucm: Fix compiling ucm.c")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>