[fs] dax: initialize variable pfn before using it
Message-id: <20180518200530.64201-11-sandeen@redhat.com>
Patchwork-id: 216509
O-Subject: [RHEL7 PATCH 10/24] dax: initialize variable pfn before using it
Bugzilla: 1471784
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

From: Nicolas Iooss <nicolas.iooss_linux@m4x.org>

Bug: 1471784 - synchronous fault support for ext4
Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16366286
Testing: local xfstests on ext4 and xfs, with and without -o dax

Upstream commit:

commit 2f52074d35135ecf3fb719f3430d72c17ae07287
Author: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
Date:   Wed Sep 6 16:19:01 2017 -0700

    dax: initialize variable pfn before using it

    dax_pmd_insert_mapping() contains the following code:

            pfn_t pfn;
            if (bdev_dax_pgoff(bdev, sector, size, &pgoff) != 0)
                goto fallback;
            /* ... */
        fallback:
          trace_dax_pmd_insert_mapping_fallback(inode, vmf, length, pfn, ret);

    When the condition in the if statement fails, the function calls
    trace_dax_pmd_insert_mapping_fallback() with an uninitialized pfn value.

    This issue has been found while building the kernel with clang.  The
    compiler reported:

        fs/dax.c:1280:6: error: variable 'pfn' is used uninitialized
        whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
            if (bdev_dax_pgoff(bdev, sector, size, &pgoff) != 0)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        fs/dax.c:1310:60: note: uninitialized use occurs here
          trace_dax_pmd_insert_mapping_fallback(inode, vmf, length, pfn, ret);
                                                                         ^~~

    Link: http://lkml.kernel.org/r/20170903083000.587-1-nicolas.iooss_linux@m4x.org
    Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
    Reviewed-by: Ross Zwisler <ross.zwisler@linux.intel.com>
    Cc: Matthew Wilcox <mawilcox@microsoft.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Eric Sandeen <sandeen@redhat.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>