[tools] perf pmu: Suppress potential format-truncation warning
Message-id: <20190311094227.31342-152-jolsa@redhat.com>
Patchwork-id: 245880
O-Subject: [PATCH RHEL7 BZ1680074 151/170] perf pmu: Suppress potential format-truncation warning
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit 11a64a05dc649815670b1be9fe63d205cb076401
Author: Ben Hutchings <ben@decadent.org.uk>
Date: Sun Nov 11 18:45:24 2018 +0000

description
===========
Depending on which functions are inlined in util/pmu.c, the snprintf()
calls in perf_pmu__parse_{scale,unit,per_pkg,snapshot}() might trigger a
warning:

  util/pmu.c: In function 'pmu_aliases':
  util/pmu.c:178:31: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 0 and 4095 [-Werror=format-truncation=]
    snprintf(path, PATH_MAX, "%s/%s.unit", dir, name);
                               ^~

I found this when trying to build perf from Linux 3.16 with gcc 8.
However I can reproduce the problem in mainline if I force
__perf_pmu__new_alias() to be inlined.

Suppress this by using scnprintf() as has been done elsewhere in perf.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>