[platform] x86: dell-smbios: fix string overflow
Message-id: <20180411191028.58398-27-jarod@redhat.com>
Patchwork-id: 208957
O-Subject: [RHEL7 PATCH 26/35] platform/x86: dell-smbios: fix string overflow
Bugzilla: 1517197
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

commit 54d11736ec3179954b6cdea4b4e1136d6bb39f39
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Nov 8 13:08:39 2017 +0100

    platform/x86: dell-smbios: fix string overflow

    The new sysfs code overwrites two fixed-length character arrays
    that are each one byte shorter than they need to be, to hold
    the trailing \0:

    drivers/platform/x86/dell-smbios.c: In function 'build_tokens_sysfs':
    drivers/platform/x86/dell-smbios.c:494:42: error: 'sprintf' writing a terminating nul past the end of the destination [-Werror=format-overflow=]
       sprintf(buffer_location, "%04x_location",
    drivers/platform/x86/dell-smbios.c:494:3: note: 'sprintf' output 14 bytes into a destination of size 13
    drivers/platform/x86/dell-smbios.c:506:36: error: 'sprintf' writing a terminating nul past the end of the destination [-Werror=format-overflow=]
       sprintf(buffer_value, "%04x_value",
    drivers/platform/x86/dell-smbios.c:506:3: note: 'sprintf' output 11 bytes into a destination of size 10

    This changes it to just use kasprintf(), which always gets it right.

    Discovered with gcc-7.1.1 with the following commit reverted:
    bd664f6b3e disable new gcc-7.1.1 warnings for now

    Fixes: 33b9ca1e53b4 ("platform/x86: dell-smbios: Add a sysfs interface for SMBIOS tokens")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Mario Limonciello <mario.limonciello@dell.com>
    [dvhart: add subject prefix and reproducer details for context]
    Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>