[infiniband] add MMU dependency for user_mem
Message-id: <20180412051314.17576-8-ddutile@redhat.com>
Patchwork-id: 208965
O-Subject: [PATCH RHEL-7.6 v2 007/318] infiniband: add MMU dependency for user_mem
Bugzilla: 1549856
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1549856

commit 9cc12ad6db55d7d902260fead28a91710dd5dbe5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Oct 6 09:13:46 2017 +0200

    infiniband: add MMU dependency for user_mem

    The infiniband subsystem causes a link failure when the umem
    driver is built on MMU-less systems:

    mm/mmu_notifier.o: In function `do_mmu_notifier_register':
    mmu_notifier.c:(.text+0x32): undefined reference to `mm_take_all_locks'
    drivers/infiniband/core/umem.o: In function `ib_umem_get':
    umem.c:(.text+0x132): undefined reference to `can_do_mlock'
    drivers/infiniband/core/umem_odp.o: In function `ib_umem_odp_map_dma_pages':
    umem_odp.c:(.text+0x766): undefined reference to `get_user_pages_remote'

    This bug has existed for a while but only become apparent in ARM
    randconfig builds when the dependency on PCI was lifted, as none
    of the ARM-NOMMU targets support PCI at the moment.

    We could probably get the umem driver to build by providing an
    alternative implementation 'can_do_mlock()' that returns false
    on NOMMU-systems, but then we'd still have a problem with the
    mmu-notifiers required by CONFIG_INFINIBAND_ON_DEMAND_PAGING,
    so simply forbidding umem with NOMMU seems like the simplest
    workaround.

    Fixes: 931bc0d91639 ("IB: Move PCI dependency from root KConfig to HW's KConfigs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>