[netdrv] fm10k: mark PM functions as __maybe_unused
Message-id: <20181130172531.26175-3-nhorman@redhat.com>
Patchwork-id: 234171
O-Subject: [RHEL7.7 PATCH 02/30] fm10k: mark PM functions as __maybe_unused
Bugzilla: 1637728
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Neil Horman <nhorman@redhat.com>

A cleanup of the PM code left an incorrect #ifdef in place, leading
to a harmless build warning:

drivers/net/ethernet/intel/fm10k/fm10k_pci.c:2502:12: error: 'fm10k_suspend' defined but not used [-Werror=unused-function]
drivers/net/ethernet/intel/fm10k/fm10k_pci.c:2475:12: error: 'fm10k_resume' defined but not used [-Werror=unused-function]

It's easier to use __maybe_unused attributes here, since you
can't pick the wrong one.

Fixes: 8249c47c6ba4 ("fm10k: use generic PM hooks instead of legacy PCIe power hooks")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Jacob Keller <jacob.e.keller@intel.com>
Tested-by: Krishneil Singh <krishneil.k.singh@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b200bfd6112a87283e58bcfcc4cb57a5517ae82f)

BZ: 1637728
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19218095
Testing: Tested successfully by Intel
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>