[net] sched: cls_u32: use hash_ptr() for tc_u_hash
Message-id: <20180503220830.1922-11-ivecera@redhat.com>
Patchwork-id: 212461
O-Subject: [RHEL7.6 net PATCH 10/45] net: sched: cls_u32: use hash_ptr() for tc_u_hash
Bugzilla: 1572720
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1572720

Upstream commit(s):
commit d18b4b35e310c5e30a3726309a93db8893cd3251
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Oct 18 10:33:37 2017 +0200

    net: sched: cls_u32: use hash_ptr() for tc_u_hash

    After the change to the tp hash, we now get a build warning
    on 32-bit architectures:

    net/sched/cls_u32.c: In function 'tc_u_hash':
    net/sched/cls_u32.c:338:17: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      return hash_64((u64) tp->chain->block, U32_HASH_SHIFT);

    Using hash_ptr() instead of hash_64() lets us drop the cast
    and fixes the warning while still resulting in the same hash
    value.

    Fixes: 7fa9d974f3c2 ("net: sched: cls_u32: use block instead of q in tc_u_common")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>