[tools] perf tools: Fix syscalltbl build failure
Message-id: <20180419185703.28105-234-jolsa@redhat.com>
Patchwork-id: 210097
O-Subject: [PATCH RHEL7.6 BZ1540862 233/245] perf tools: Fix syscalltbl build failure
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 090657c9fb7094e4c1b05c1713d6c2a12ef43dea
Author: Akemi Yagi <amyagi@gmail.com>
Date: Fri Sep 22 22:11:53 2017 +0000

description
===========
The build of kernel v4.14-rc1 for i686 fails on RHEL 6 with the error
in tools/perf:

  util/syscalltbl.c:157: error: expected ';', ',' or ')' before '__maybe_unused'
  mv: cannot stat `util/.syscalltbl.o.tmp': No such file or directory

Fix it by placing/moving:

  #include <linux/compiler.h>

  outside of #ifdef HAVE_SYSCALL_TABLE block.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>