[thunderbolt] Fix build error in switch.c
Message-id: <1512650446-15556-18-git-send-email-jeremymc@redhat.com>
Patchwork-id: 201649
O-Subject: [PATCH RHEL7.5 v3 017/113] thunderbolt: Fix build error in switch.c
Bugzilla: 1172010
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jeremy McNicoll <jeremymc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1172010

commit 10fefe56bba413fb0525207c65cf50cf2a5afaff
Author: Sachin Kamat <sachin.kamat@samsung.com>
Date:   Fri Jun 20 14:32:30 2014 +0530

    thunderbolt: Fix build error in switch.c

    Fixes the below error:
    drivers/thunderbolt/switch.c:347:2: error: implicit declaration of function kzalloc [-Werror=implicit-function-declaration]
    drivers/thunderbolt/switch.c:381:2: error: implicit declaration of function kcalloc [-Werror=implicit-function-declaration]

    Signed-off-by: Sachin Kamat <sachin.kamat@samsung.com>
    Acked-by: Andreas Noever <andreas.noever@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>