[usb] typec: ucsi: fix tracepoint related build error
Message-id: <1552707357-18587-113-git-send-email-torez@redhat.com>
Patchwork-id: 246559
O-Subject: [RHEL7.7 PATCH BZ1657401 V2 112/378] usb: typec: ucsi: fix tracepoint related build error
Bugzilla: 1657401
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1657401
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20451897
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20625676
Testing: on Dell Whitehaven Precision 7730, HP ZBook 15 G3/80D5 and
         ThinkCentre M910z All-in-One

commit 2f860691c2d2e3af1404ffeb2d22dd5c3dbca811
Author: Tobias Regnery <tobias.regnery@gmail.com>
Date:   Tue Apr 10 10:38:06 2018 +0200

    usb: typec: ucsi: fix tracepoint related build error

    There is the following build error with CONFIG_TYPEC_UCSI=m, CONFIG_FTRACE=y
    and CONFIG_TRACING=n:

    ERROR: "__tracepoint_ucsi_command" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_register_port" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_notify" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_reset_ppm" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_run_command" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_ack" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!
    ERROR: "__tracepoint_ucsi_connector_change" [drivers/usb/typec/ucsi/typec_ucsi.ko] undefined!

    This compination is quite hard to create because CONFIG_TRACING gets selected
    only in rare cases without CONFIG_FTRACE.

    The build failure is caused by conditionally compiling trace.c depending on
    the wrong option CONFIG_FTRACE. Change this to depend on CONFIG_TRACING like
    other users of tracepoints do.

    Fixes: c1b0bc2dabfa ("usb: typec: Add support for UCSI interface")
    Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>
    Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>