[scsi] qedi: fix build regression
Message-id: <1526500291-21143-5-git-send-email-cdupuis@redhat.com>
Patchwork-id: 215376
O-Subject: [PATCH RHEL 7.6 e-stor 4/5] scsi: qedi: fix build regression
Bugzilla: 1566549
RH-Acked-by: Chris Leech <cleech@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

commit edd066a10090773e18a2095455ad793c73d022b4
https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git

A bugfix I did caused a build regression in some other randconfig
builds in a rare combination of options:

In file included from drivers/scsi/qedi/qedi_fw.c:16:
drivers/scsi/qedi/qedi_gbl.h:26:38: error: array type has incomplete element type 'struct qedi_debugfs_ops'
 extern const struct qedi_debugfs_ops qedi_debugfs_ops[];
                                      ^~~~~~~~~~~~~~~~

This removes the useless #ifdef around the declarations in qedi_dbg.h
to make it always build.

Fixes: 779936faf4f1 ("scsi: qedi: fix building with LTO")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>