[netdrv] gve: fix unused variable/label warnings
Message-id: <20190816185420.12540-9-linville@redhat.com>
Patchwork-id: 269286
O-Subject: [RHEL7 08/15] gve: fix unused variable/label warnings
Bugzilla: 1728840
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

From: "John W. Linville" <linville@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1728840
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22991328

On unusual page sizes, we get harmless warnings:

drivers/net/ethernet/google/gve/gve_rx.c:283:6: error: unused variable 'pagecount' [-Werror,-Wunused-variable]
drivers/net/ethernet/google/gve/gve_rx.c:336:1: error: unused label 'have_skb' [-Werror,-Wunused-label]

Change the preprocessor #if to regular if() to avoid this.

Fixes: f5cedc84a30d ("gve: Add transmit and receive support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 0287f9ed1693fff26a2d568a9d3f74c2b198540c)
Signed-off-by: John W. Linville <linville@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>