[netdrv] mlx5: IPSec, Fix 64-bit division on 32-bit builds
Message-id: <1511855648-15797-64-git-send-email-kheib@redhat.com>
Patchwork-id: 200274
O-Subject: [RHEL7.5 PATCH 063/192] net/mlx5: IPSec, Fix 64-bit division on 32-bit builds
Bugzilla: 1456677 1456694
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456694
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456677

commit 5dfd87b67cd98375896890e01437edefeb45a707
Author: Ilan Tayari <ilant@mellanox.com>
Date:   Sun Jul 2 10:57:56 2017 +0300

    net/mlx5: IPSec, Fix 64-bit division on 32-bit builds

    Fix warnings when building 386 kernel:
    >> ERROR: "__udivdi3" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

    Fixes: 2ac9cfe78223 ("net/mlx5e: IPSec, Add Innova IPSec offload TX data path")
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Ilan Tayari <ilant@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>