[scsi] cxlflash: Select IRQ_POLL
Message-id: <1508870554-32230-43-git-send-email-gduarte@redhat.com>
Patchwork-id: 194946
O-Subject: [RHEL7.5 PATCH BZ 1456494 42/67] scsi: cxlflash: Select IRQ_POLL
Bugzilla: 1456494
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

BZ 1456494
Upstream Status: 07cc1ccfb84320582c9ac389a21cd81df82bc123

commit 07cc1ccfb84320582c9ac389a21cd81df82bc123
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Fri May 5 16:31:47 2017 -0700

    scsi: cxlflash: Select IRQ_POLL

    The driver now uses IRQ_POLL and needs to select it to avoid the
    following build error.

    ERROR: ".irq_poll_complete" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
    ERROR: ".irq_poll_sched" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
    ERROR: ".irq_poll_disable" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
    ERROR: ".irq_poll_init" [drivers/scsi/cxlflash/cxlflash.ko] undefined!

    Fixes: cba06e6de403 ("scsi: cxlflash: Implement IRQ polling for RRQ processing")
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Matthew R. Ochs <mrochs@linux.vnet.ibm.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>