[net] export netdev_txq_to_tc to allow sch_mqprio to compile as module
Message-id: <20180517162921.13433-6-ivecera@redhat.com>
Patchwork-id: 215481
O-Subject: [RHEL7.6 net PATCH 5/5] net: export netdev_txq_to_tc to allow sch_mqprio to compile as module
Bugzilla: 1579358
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1579358

Upstream commit(s):
commit 8a5f2166a6288ee4b5a393f1ebc8cfb26b0510f0
Author: Henrik Austad <henrik@austad.us>
Date:   Tue Oct 17 12:10:10 2017 +0200

    net: export netdev_txq_to_tc to allow sch_mqprio to compile as module

    In commit 32302902ff09 ("mqprio: Reserve last 32 classid values for HW
    traffic classes and misc IDs") sch_mqprio started using netdev_txq_to_tc
    to find the correct tc instead of dev->tc_to_txq[]

    However, when mqprio is compiled as a module, it cannot resolve the
    symbol, leading to this error:

         ERROR: "netdev_txq_to_tc" [net/sched/sch_mqprio.ko] undefined!

    This adds an EXPORT_SYMBOL() since the other user in the kernel
    (netif_set_xps_queue) is also EXPORT_SYMBOL() (and not _GPL) or in a
    sysfs-callback.

    Cc: Alexander Duyck <alexander.h.duyck@intel.com>
    Cc: Jesus Sanchez-Palencia <jesus.sanchez-palencia@intel.com>
    Cc: David S. Miller <davem@davemloft.net>
    Signed-off-by: Henrik Austad <haustad@cisco.com>
    Reviewed-by: Eric Dumazet <edumazet@google.com>
    Acked-by: Alexander Duyck <alexander.h.duyck@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>