[kernel] perf, bpf: fix conditional call to bpf_overflow_handler
Message-id: <20180709105913.17980-8-jolsa@redhat.com>
Patchwork-id: 224120
O-Subject: [PATCH RHEL7.6 BZ1593026 07/50] perf, bpf: fix conditional call to bpf_overflow_handler
Bugzilla: 1593026
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1593026
https://bugzilla.redhat.com/show_bug.cgi?id=1593026

upstream
========
commit f1e4ba5b6a6555d1f6b174d4fd0a96a9363bb57f
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Sep 6 15:10:22 2016 +0200

description
===========
The newly added bpf_overflow_handler function is only built of both
CONFIG_EVENT_TRACING and CONFIG_BPF_SYSCALL are enabled, but the caller
only checks the latter:

kernel/events/core.c: In function 'perf_event_alloc':
kernel/events/core.c:9106:27: error: 'bpf_overflow_handler' undeclared (first use in this function)

This changes the caller so we also skip this call if CONFIG_EVENT_TRACING
is disabled entirely.

Fixes: aa6a5f3cb2b2 ("perf, bpf: add perf events core support for BPF_PROG_TYPE_PERF_EVENT programs")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>