[tools] perf tools: Initialize perf_data_file fd field
Message-id: <20190311094227.31342-69-jolsa@redhat.com>
Patchwork-id: 245794
O-Subject: [PATCH RHEL7 BZ1680074 068/170] perf tools: Initialize perf_data_file fd field
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit c04c859f439fb4de9039246370d60a07b9b5bcb5
Author: Jrmie Galarneau <jeremie.galarneau@efficios.com>
Date: Wed Aug 29 16:16:48 2018 -0400

description
===========
Building the perf CTF converter fails with gcc 4.8.4 on Ubuntu 14.04
with the following error:

  error: missing initializer for field fd of struct perf_data_file
  [-Werror=missing-field-initializers]

Per 4b838b0db4e9 ("perf tools: Add compression id into 'struct
kmod_path'") and the ensuing discussion on the mailing list, it appears
that this affects other distributions and gcc versions.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>