[netdrv] vmxnet3: avoid format strint overflow warning
Message-id: <20180313185835.6671-4-nhorman@redhat.com>
Patchwork-id: 206683
O-Subject: [RHEL7.6 PATCH 3/5] vmxnet3: avoid format strint overflow warning
Bugzilla: 1532362
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

From: Neil Horman <nhorman@redhat.com>

gcc-7 notices that "-event-%d" could be more than 11 characters long
if we had larger 'vector' numbers:

drivers/net/vmxnet3/vmxnet3_drv.c: In function 'vmxnet3_activate_dev':
drivers/net/vmxnet3/vmxnet3_drv.c:2095:40: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
sprintf(intr->event_msi_vector_name, "%s-event-%d",
                                     ^~~~~~~~~~~~~
drivers/net/vmxnet3/vmxnet3_drv.c:2095:3: note: 'sprintf' output between 9 and 33 bytes into a destination of size 32

The current code is safe, but making the string a little longer
is harmless and lets gcc see that it's ok.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c7673e4dea9a338e00fa26cdd42d3697e8e22319)

BZ:1532362
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15528349
Testing: Tested by myself with positive results
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>