[s390] Remove VLAIS in ptff() and clear_table()
Message-id: <20190322170128.32748-12-yauheni.kaliuta@redhat.com>
Patchwork-id: 247376
O-Subject: [PATCH RHEL7.7 11/11] s390: Remove VLAIS in ptff() and clear_table()
Bugzilla: 1691710
RH-Acked-by: Hendrik Brueckner <brueckner@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1691710
https://bugzilla.redhat.com/show_bug.cgi?id=1691710

upstream
========
commit 11a247e376669323b0d9f56fbdb5c163c6310112
Author: Michael Holzheu <holzheu@linux.vnet.ibm.com>
Date: Tue Nov 29 13:52:01 2016 +0100

description
===========
The ptff() and clear_table() functions use the gcc extension "variable
length arrays in structures" (VLAIS) to define in the inline assembler
constraints the area of the clobbered memory. This extension will most
likely never be supported by LLVM/Clang.

Since currently BPF programs are compiled with LLVM, this leads to the
following compile errors:

 $ cd samples/bpf
 $ make

 In file included from /root/linux-master/samples/bpf/tracex1_kern.c:8:
 In file included from ./include/linux/netdevice.h:44:
 ...
 In file included from ./arch/s390/include/asm/mmu_context.h:10:
  ./arch/s390/include/asm/pgalloc.h:30:24: error: fields must have a
  constant size: 'variable length array in structure' extension will never
  be supported
         typedef struct { char _[n]; } addrtype;

 In file included from /root/linux-master/samples/bpf/tracex1_kern.c:7:
 In file included from ./include/linux/skbuff.h:18:
 ...
 In file included from ./include/linux/jiffies.h:8:
 In file included from ./include/linux/timex.h:65:
  ./arch/s390/include/asm/timex.h:105:24: error: fields must have a
  constant size: 'variable length array in structure' extension will never
  be supported
        typedef struct { char _[len]; } addrtype;

To fix this do the following:

 - Convert ptff() into a macro that then uses a fixed size array
   when expanded.
 - Convert the clear_table() function and use an inline assembly
   with fixed size array in a loop.
   The runtime performance of the new version is even better than
   the old version (tested with EC12/z13 and gcc 4.8.5/6.2.1 with
   "-march=z196 -O2").

RHEL7
=====
Small context conflicts due to untaken changes.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>