[char] tpm: remove unused variables
Message-id: <20180515154020.12996-37-jsnitsel@redhat.com>
Patchwork-id: 215227
O-Subject: [RHEL7.6 PATCH v2 36/52] tpm: remove unused variables
Bugzilla: 1515099 1578136
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1578136, 1515099
Upstream Status: 68021bf4734d15c9a9ed1c1072b9ebcfda3e39cc
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16284037

commit 68021bf4734d15c9a9ed1c1072b9ebcfda3e39cc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 2 11:38:54 2018 +0100

    tpm: remove unused variables

    The CLKRUN fix caused a few harmless compile-time warnings:

    drivers/char/tpm/tpm_tis.c: In function 'tpm_tis_pnp_remove':
    drivers/char/tpm/tpm_tis.c:274:23: error: unused variable 'priv' [-Werror=unused-variable]
    drivers/char/tpm/tpm_tis.c: In function 'tpm_tis_plat_remove':
    drivers/char/tpm/tpm_tis.c:324:23: error: unused variable 'priv' [-Werror=unused-variable]

    This removes the variables that have now become unused.

    Fixes: 6d0866cbc2d3 ("tpm: Keep CLKRUN enabled throughout the duration of transmit_cmd()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
    Reviewed-by: James Morris <jmorris@namei.org>
    Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>

(imported from commit 68021bf4734d15c9a9ed1c1072b9ebcfda3e39cc)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>