[infiniband] infiniband/core/verbs.c: fix build with gcc-4.4.4
Message-id: <20181129133352.19421-45-kheib@redhat.com>
Patchwork-id: 234017
O-Subject: [PATCH RHEL-7.7 044/141] drivers/infiniband/core/verbs.c: fix build with gcc-4.4.4
Bugzilla: 1641363
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1641363

commit 6ee687735e745eafae9e6b93d1ea70bc52e7ad07
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Tue Mar 13 14:51:57 2018 -0700

    drivers/infiniband/core/verbs.c: fix build with gcc-4.4.4

    gcc-4.4.4 has issues with initialization of anonymous unions.

    drivers/infiniband/core/verbs.c: In function '__ib_drain_sq':
    drivers/infiniband/core/verbs.c:2204: error: unknown field 'wr_cqe' specified in initializer
    drivers/infiniband/core/verbs.c:2204: warning: initialization makes integer from pointer without a cast

    Work around this.

    Fixes: a1ae7d0345edd5 ("RDMA/core: Avoid that ib_drain_qp() triggers an out-of-bounds stack access")
    Cc: Bart Van Assche <bart.vanassche@wdc.com>
    Cc: Steve Wise <swise@opengridcomputing.com>
    Cc: Sagi Grimberg <sagi@grimberg.me>
    Cc: Jason Gunthorpe <jgg@mellanox.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>