[thunderbolt] Make enum tb_drom_entry_type unsigned
Message-id: <1512650446-15556-27-git-send-email-jeremymc@redhat.com>
Patchwork-id: 201647
O-Subject: [PATCH RHEL7.5 v3 026/113] thunderbolt: Make enum tb_drom_entry_type unsigned
Bugzilla: 1172010
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jeremy McNicoll <jeremymc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1172010

commit e7120778a4518a1c8f188ef9865058f7f5a36919
Author: Andreas Noever <andreas.noever@gmail.com>
Date:   Fri Jun 20 21:42:24 2014 +0200

    thunderbolt: Make enum tb_drom_entry_type unsigned

    Force enum tb_drom_entry_type to unsigned to fix the following error:

    drivers/thunderbolt/eeprom.c:202:39: error: dubious one-bit signed bitfield

    Signed-off-by: Andreas Noever <andreas.noever@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>