[net] netfilter: ipset: Fix static checker warning in ip_set_core.c
Message-id: <97e57f7f3f3f5b68367bc613ca381c30f74a9188.1526056798.git.sbrivio@redhat.com>
Patchwork-id: 214582
O-Subject: [RHEL7.6 net 052/149] netfilter: ipset: Fix static checker warning in ip_set_core.c
Bugzilla: 1557599
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1557599
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16136344
Tested:
	- ipset 6.38 test suite with:
		- patch to get match_target tests running on RHEL,
		  http://patchwork.ozlabs.org/patch/910306/
		- RHEL7.5 iptables-1.4.21 patched to include commit 6d9ae2952a44
		  ("xtables: SET target: Add mapping of meta informations
		  (skbinfo ipset extension)"), RPMs available at:
			http://file.rdu.redhat.com/~sbrivio/iptables-1.4.21-ipset_skbinfo/
	- basic iptables functionality tests
	- network CI tests: https://beaker.engineering.redhat.com/jobs/2469259

commit 73e64e1813e9ea45885419d0fff1e628a6ab95d4
Author: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
Date:   Mon Sep 15 20:48:26 2014 +0200

    netfilter: ipset: Fix static checker warning in ip_set_core.c

    Dan Carpenter reported the following static checker warning:

            net/netfilter/ipset/ip_set_core.c:1414 call_ad()
            error: 'nlh->nlmsg_len' from user is not capped properly

    The payload size is limited now by the max size of size_t.

    Signed-off-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>