[infiniband] ib: INFINIBAND should depend on HAS_DMA
Message-id: <20180412051314.17576-27-ddutile@redhat.com>
Patchwork-id: 208989
O-Subject: [PATCH RHEL-7.6 v2 026/318] IB: INFINIBAND should depend on HAS_DMA
Bugzilla: 1549856
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1549856

commit db0acbc475f06c775682ba969ab338e1efa2ae96
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Sun Nov 19 19:58:30 2017 +0100

    IB: INFINIBAND should depend on HAS_DMA

    If NO_DMA=y:

        ERROR: "bad_dma_ops" [net/sunrpc/xprtrdma/rpcrdma.ko] undefined!
        ERROR: "bad_dma_ops" [net/smc/smc.ko] undefined!
        ERROR: "bad_dma_ops" [net/rds/rds_rdma.ko] undefined!
        ERROR: "bad_dma_ops" [net/9p/9pnet_rdma.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/nvme/target/nvmet-rdma.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/nvme/host/nvme-rdma.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/ulp/srpt/ib_srpt.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/ulp/srp/ib_srp.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/ulp/isert/ib_isert.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/ulp/iser/ib_iser.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/ulp/ipoib/ib_ipoib.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/infiniband/core/ib_core.ko] undefined!

    Before, this was handled implicitly by the dependency on PCI.
    Add an explicit dependency on HAS_DMA to fix this.

    Fixes: 931bc0d91639f8fb ("IB: Move PCI dependency from root KConfig to HW's KConfigs")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>