[netdrv] mlxsw: spectrum_router: Fix build when IPv6 isn't enabled
Message-id: <20171013205835.26049-184-ivecera@redhat.com>
Patchwork-id: 193535
O-Subject: [RHEL7.5 PATCH 183/245] mlxsw: spectrum_router: Fix build when IPv6 isn't enabled
Bugzilla: 1486860
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1486860

Upstream commit(s):
commit b5f3e0d430122a551cbc2b88068dae8b2c2c0031
Author: Ido Schimmel <idosch@mellanox.com>
Date:   Mon Jul 24 09:56:00 2017 +0200

    mlxsw: spectrum_router: Fix build when IPv6 isn't enabled

    When IPv6 isn't enabled the following error is generated:

    ERROR: "nd_tbl" [drivers/net/ethernet/mellanox/mlxsw/mlxsw_spectrum.ko]
    undefined!

    Fix it by replacing 'arp_tbl' and 'nd_tbl' with 'tbl->family' wherever
    possible and reference 'nd_tbl' only when IPV6 is enabled.

    Fixes: d5eb89cf68d6 ("mlxsw: spectrum_router: Reflect IPv6 neighbours to the device")
    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>