[iio] hid-sensors: avoid unused function warning
Message-id: <20180711174504.24920-343-tcamuso@redhat.com>
Patchwork-id: 224643
O-Subject: [RHEL7 BZ-1559170 v3 342/373] iio: hid-sensors: avoid unused function warning
Bugzilla: 1559170
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1559170
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17099185

Cherry-picked from the following upstream commit.

commit 2e1f44d8a7724e889f1a4f211aad13320cb80f1f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 26 17:29:35 2016 +0200

    iio: hid-sensors: avoid unused function warning

    A small rework of the PM code in this driver introduced a harmless
    warning when CONFIG_PM_SLEEP is not set:

    drivers/iio/common/hid-sensors/hid-sensor-trigger.c:212:12: error: 'hid_sensor_resume' defined but not used [-Werror=unused-function]

    This removes the #ifdef and instead marks all three PM functions
    as __maybe_unused, which covers all possible cases and is harder
    to get wrong.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 7f6cf7414538 ("iio: hid-sensors: use asynchronous resume")
    Signed-off-by: Jonathan Cameron <jic23@kernel.org>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>