[netdrv] mlx4_en: add a missing <net/ip.h> include
Message-id: <1549457075-6314-470-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240425
O-Subject: [RHEL7.7 BZ 1642498 469/729] net/mlx4_en: add a missing <net/ip.h> include
Bugzilla: 1641912 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Bugzilla: http://bugzilla.redhat.com/1641912
Upstream: v4.20-rc1

commit 3aa8029e1ac4faea2967e36281d93f5d099ed6a9
Author: Eric Dumazet <edumazet@google.com>
Date:   Tue Oct 30 00:18:12 2018 -0700

    net/mlx4_en: add a missing <net/ip.h> include

    Abdul Haleem reported a build error on ppc :

    drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: `struct
    iphdr` declared inside parameter list [enabled by default]
               struct iphdr *iph)
                      ^
    drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: its scope is
    only this definition or declaration, which is probably not what you want
    [enabled by default]
    drivers/net/ethernet/mellanox/mlx4/en_rx.c: In function
    get_fixed_ipv4_csum:
    drivers/net/ethernet/mellanox/mlx4/en_rx.c:586:20: error: dereferencing
    pointer to incomplete type
      __u8 ipproto = iph->protocol;
                        ^

    Fixes: 55469bc6b577 ("drivers: net: remove <net/busy_poll.h> inclusion when not needed")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Reported-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Cc: Jesper Dangaard Brouer <brouer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>