[net] devlink: fix incorrect return statement
Message-id: <264e92e08c4d2d573fa573d8c9508ceef94fc89e.1545039206.git.poros@redhat.com>
Patchwork-id: 235893
O-Subject: [RHEL7.7 net PATCH 08/23] devlink: fix incorrect return statement
Bugzilla: 1653433
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1653433

Upstream commit(s):
commit 22dd149167359981ea6f4afde04026fb78747ddc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 6 14:58:51 2018 +0200

    devlink: fix incorrect return statement

    A newly added dummy helper function tries to return a failure from a "void"
    function:

    In file included from include/net/dsa.h:24,
                     from arch/arm/plat-orion/common.c:21:
    include/net/devlink.h: In function 'devlink_param_value_changed':
    include/net/devlink.h:771:9: error: 'return' with a value, in function returning void [-Werror]
      return -EOPNOTSUPP;

    This fixes it by removing the bogus statement.

    Fixes: ea601e170988 ("devlink: Add devlink notifications support for params")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>