[net] sched: red: work around gcc-4.4.4 anon union initializer issue
Message-id: <20180530152657.20742-4-ivecera@redhat.com>
Patchwork-id: 218281
O-Subject: [RHEL7.6 net PATCH 03/12] net/sched/sch_red.c: work around gcc-4.4.4 anon union initializer issue
Bugzilla: 1583702
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1583702

Upstream commit(s):
commit ee9d3429c0e47a57e3e73b638785cafa33773639
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Fri Nov 10 15:09:53 2017 -0800

    net/sched/sch_red.c: work around gcc-4.4.4 anon union initializer issue

    gcc-4.4.4 (at lest) has issues with initializers and anonymous unions:

    net/sched/sch_red.c: In function 'red_dump_offload':
    net/sched/sch_red.c:282: error: unknown field 'stats' specified in initializer
    net/sched/sch_red.c:282: warning: initialization makes integer from pointer without a cast
    net/sched/sch_red.c:283: error: unknown field 'stats' specified in initializer
    net/sched/sch_red.c:283: warning: initialization makes integer from pointer without a cast
    net/sched/sch_red.c: In function 'red_dump_stats':
    net/sched/sch_red.c:352: error: unknown field 'xstats' specified in initializer
    net/sched/sch_red.c:352: warning: initialization makes integer from pointer without a cast

    Work around this.

    Fixes: 602f3baf2218 ("net_sch: red: Add offload ability to RED qdisc")
    Cc: Nogah Frankel <nogahf@mellanox.com>
    Cc: Jiri Pirko <jiri@mellanox.com>
    Cc: Simon Horman <simon.horman@netronome.com>
    Cc: David S. Miller <davem@davemloft.net>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>