[powerpc] mm: Fix build break with BOOK3S_64=n and MEMORY_HOTPLUG=y
Message-id: <20190430134949.10673-2-lvivier@redhat.com>
Patchwork-id: 251904
O-Subject: [RHEL7.7 virt PATCH 1/3] powerpc/mm: Fix build break with BOOK3S_64=n and MEMORY_HOTPLUG=y
Bugzilla: 1693046
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

From: Michael Ellerman <mpe@ellerman.id.au>

The recently merged HPT (Hash Page Table) resize support broke the build
when BOOK3S_64=n (ie. 32-bit or 64-bit Book3E) and MEMORY_HOTPLUG=y:

  arch/powerpc/mm/mem.o: In function `.arch_add_memory':
  (.text+0x4e4): undefined reference to `.resize_hpt_for_hotplug'

Fix it by adding a dummy version.

Fixes: 438cc81a41e8 ("powerpc/pseries: Automatically resize HPT for memory hot add/remove")
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 36b390fd624a7f3a64bda5de54fa58ebcf956ffc)
Signed-off-by: Laurent Vivier <lvivier@redhat.com>

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693046
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>