[uio] uio_hv_generic: fix type mismatch warnings
Message-id: <1545231234-15987-8-git-send-email-mgamal@redhat.com>
Patchwork-id: 236190
O-Subject: [RHEL7.7 KERNEL PATCH v3 07/27] uio_hv_generic: fix type mismatch warnings
Bugzilla: 1562041
RH-Acked-by: Cathy Avery <cavery@redhat.com>
RH-Acked-by: Vitaly Kuznetsov <vkuznets@redhat.com>

I moved the virt_to_phys() conversion into hv_uio_probe() as part of
a warning fix. Stephen's cleanup to remove the private mmap() function
seems reasonable, but part of it reverted the change that I did to
hide the warnings, so they are back now:

drivers/uio/uio_hv_generic.c: In function 'hv_uio_probe':
drivers/uio/uio_hv_generic.c:123:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
drivers/uio/uio_hv_generic.c:130:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
drivers/uio/uio_hv_generic.c:136:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]

The type mismatch is now the result of the uio_mmap() definition, and
the best way I see from here is to shut them up with a uintptr_t cast.

Fixes: 9c40546c012c ("uio_hv_generic: use standard mmap for resources")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 72d1465789506cdc441cb85271d993aee4ae79fe)

Signed-off-by: Mohammed Gamal <mgamal@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>