[usb] typec: avoid format-overflow warning
Message-id: <1552707357-18587-295-git-send-email-torez@redhat.com>
Patchwork-id: 246731
O-Subject: [RHEL7.7 PATCH BZ1657401 V2 294/378] usb: typec: avoid format-overflow warning
Bugzilla: 1657401
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1657401
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20451897
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20625676
Testing: on Dell Whitehaven Precision 7730, HP ZBook 15 G3/80D5 and
         ThinkCentre M910z All-in-One

commit 8160eac1213fb6d466dee156638647a71da7d7fb
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 6 15:28:32 2018 +0200

    usb: typec: avoid format-overflow warning

    gcc-8 points out that the fix-byte buffer might be too small if
    desc->mode is a three-digit number:

    drivers/usb/typec/class.c: In function 'typec_register_altmode':
    drivers/usb/typec/class.c:502:32: error: '%d' directive writing between 1 and 3 bytes into a region of size 2 [-Werror=format-overflow=]
      sprintf(alt->group_name, "mode%d", desc->mode);
                                    ^~
    drivers/usb/typec/class.c:502:27: note: directive argument in the range [0, 255]
      sprintf(alt->group_name, "mode%d", desc->mode);
                               ^~~~~~~~
    drivers/usb/typec/class.c:502:2: note: 'sprintf' output between 6 and 8 bytes into a destination of size 6
      sprintf(alt->group_name, "mode%d", desc->mode);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    I assume this cannot happen in practice, but we can simply make the
    string long enough to avoid the warning. This uses the two padding
    bytes that already exist after the string.

    Fixes: 4ab8c18d4d67 ("usb: typec: Register a device for every mode")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>