[tools] perf tools: Fix compilation errors on gcc8
Message-id: <20190218130507.16170-184-jolsa@redhat.com>
Patchwork-id: 242206
O-Subject: [PATCH RHEL7 BZ1672893 183/187] perf tools: Fix compilation errors on gcc8
Bugzilla: 1672893
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1672893
https://bugzilla.redhat.com/show_bug.cgi?id=1672893

upstream
========
commit a09603f851045b031e990d2d663958ccb49db525
Author: Jiri Olsa <jolsa@kernel.org>
Date: Mon Jul 2 15:42:01 2018 +0200

description
===========
We are getting following warnings on gcc8 that break compilation:

  $ make
    CC       jvmti/jvmti_agent.o
  jvmti/jvmti_agent.c: In function jvmti_open:
  jvmti/jvmti_agent.c:252:35: error: /jit- directive output may be truncated \
    writing 5 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
    snprintf(dump_path, PATH_MAX, "%s/jit-%i.dump", jit_path, getpid());

There's no point in checking the result of snprintf call in
jvmti_open, the following open call will fail in case the
name is mangled or too long.

Using tools/lib/ function scnprintf that touches the return value from
the snprintf() calls and thus get rid of those warnings.

  $ make DEBUG=1
    CC       arch/x86/util/perf_regs.o
  arch/x86/util/perf_regs.c: In function arch_sdt_arg_parse_op:
  arch/x86/util/perf_regs.c:229:4: error: strncpy output truncated before terminating nul
  copying 2 bytes from a string of the same length [-Werror=stringop-truncation]
    strncpy(prefix, "+0", 2);
    ^~~~~~~~~~~~~~~~~~~~~~~~

Using scnprintf instead of the strncpy (which we know is safe in here)
to get rid of that warning.

Signed-off-by: Jan Stancek <jstancek@redhat.com>