[hid] intel_ish-hid: fix format string for size_t
Message-id: <1510839526-11340-55-git-send-email-gtiwari@redhat.com>
Patchwork-id: 198304
O-Subject: [ PATCH BZ 1475903 54/59] HID: intel_ish-hid: fix format string for size_t
Bugzilla: 1475903
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1475903

commit 318fc2a867bc5bac688cb88f111eb75792675dc2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 18 22:21:43 2017 +0200

    HID: intel_ish-hid: fix format string for size_t

    When building for 32-bit architectures, we get a harmless warning:

    intel-ish-hid/ishtp-hid-client.c: In function 'process_recv':
    intel-ish-hid/ishtp-hid-client.c:139:7: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Werror=format=]

    This changes the format string to print size_t variables using %zu
    instead.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>