[usb] host: xhci: remove #ifdef around PM functions
Message-id: <1526649550-17190-176-git-send-email-torez@redhat.com>
Patchwork-id: 215948
O-Subject: [RHEL7.6 PATCH BZ1540721 175/681] usb: host: xhci: remove #ifdef around PM functions
Bugzilla: 1540721
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1540721
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16352184
Testing: on local desktop and Dell Precision 5510 laptop

Conflicts: Removed changes to files which have been filtered out and not
included in this series. In particular, changes to the following files...
    drivers/usb/host/xhci-plat.c

commit d852ed98f62e0d44f594adb850b3d6cedb5c9292
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 21 23:42:54 2017 +0200

    usb: host: xhci: remove #ifdef around PM functions

    The #ifdef is slightly wrong as it doesn't cover the xhci_priv_resume_quirk()
    function, causing a harmless warning:

    drivers/usb/host/xhci-plat.c:58:12: error: 'xhci_priv_resume_quirk' defined but not used [-Werror=unused-function]
     static int xhci_priv_resume_quirk(struct usb_hcd *hcd)

    A simpler way to do this correctly is to use __maybe_unused annotations
    that let the compiler silently drop the functions when there is no
    reference.

    Fixes: b0c69b4bace3 ("usb: host: plat: Enable xHCI plat runtime PM")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>