[kernel] misc: rtsx: rename SG_END macro
Message-id: <20190305155643.22586-24-rclark@redhat.com>
Patchwork-id: 244583
O-Subject: [RHEL7 drm 23/34] misc: rtsx: rename SG_END macro
Bugzilla: 1655767
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Upstream: since v4.17
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20431428
RHBZ: 1655767

commit f16ee7c7ec0fa5f0322bd64d5ee183a28ed1ec08

Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Thu Mar 1 11:31:28 2018 +0100
Commit:     Jens Axboe <axboe@kernel.dk>
CommitDate: Thu Mar 1 08:33:05 2018 -0700

    misc: rtsx: rename SG_END macro

    A change to the generic scatterlist code caused a conflict with
    the rtsx card reader driver:

    In file included from drivers/misc/cardreader/rtsx_pcr.c:32:
    include/linux/rtsx_pci.h:40: error: "SG_END" redefined [-Werror]

    This changes one instance of the driver to prefix SG_END and
    related constants.

    Fixes: 723fbf563a6a ("lib/scatterlist: Add SG_CHAIN and SG_END macros for LSB encodings")
    Cc: Anshuman Khandual <khandual@linux.vnet.ibm.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>