[netdrv] ath10k: fix build errors with !CONFIG_PM
Message-id: <1516891884-5142-4-git-send-email-sgruszka@redhat.com>
Patchwork-id: 204383
O-Subject: [RHEL7.5 PATCH 3/4] ath10k: fix build errors with !CONFIG_PM
Bugzilla: 1501882
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1501882

Backport of:
commit 20665a9076d48e9abd9a2db13d307f58f7ef6647
Author: Brian Norris <briannorris@chromium.org>
Date:   Thu Oct 19 11:45:19 2017 -0700

    ath10k: fix build errors with !CONFIG_PM

    Build errors have been reported with CONFIG_PM=n:

    drivers/net/wireless/ath/ath10k/pci.c:3416:8: error: implicit
    declaration of function 'ath10k_pci_suspend'
    [-Werror=implicit-function-declaration]

    drivers/net/wireless/ath/ath10k/pci.c:3428:8: error: implicit
    declaration of function 'ath10k_pci_resume'
    [-Werror=implicit-function-declaration]

    These are caused by the combination of the following two commits:

    6af1de2e4ec4 ("ath10k: mark PM functions as __maybe_unused")
    96378bd2c6cd ("ath10k: fix core PCI suspend when WoWLAN is supported but
    disabled")

    Both build fine on their own.

    But now that ath10k_pci_pm_{suspend,resume}() is compiled
    unconditionally, we should also compile ath10k_pci_{suspend,resume}()
    unconditionally.

    And drop the #ifdef around ath10k_pci_hif_{suspend,resume}() too; they
    are trivial (empty), so we're not saving much space by compiling them
    out. And the alternatives would be to sprinkle more __maybe_unused, or
    spread the #ifdef's further.

    Build tested with the following combinations:
    CONFIG_PM=y && CONFIG_PM_SLEEP=y
    CONFIG_PM=y && CONFIG_PM_SLEEP=n
    CONFIG_PM=n

    Fixes: 96378bd2c6cd ("ath10k: fix core PCI suspend when WoWLAN is supported but disabled")
    Fixes: 096ad2a15fd8 ("Merge branch 'ath-next'")
    Signed-off-by: Brian Norris <briannorris@chromium.org>
    Signed-off-by: Kalle Valo <kvalo@qca.qualcomm.com>

Brew:
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15070888

Testing:
Tested on QCA6174 adapter.

Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>