[hid] iio: hid-sensors: avoid unused function warning
Message-id: <1510839526-11340-24-git-send-email-gtiwari@redhat.com>
Patchwork-id: 198272
O-Subject: [ PATCH BZ 1475903 23/59] iio: hid-sensors: avoid unused function warning
Bugzilla: 1475903
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1475903

commit 2e1f44d8a7724e889f1a4f211aad13320cb80f1f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 26 17:29:35 2016 +0200

    iio: hid-sensors: avoid unused function warning

    A small rework of the PM code in this driver introduced a harmless
    warning when CONFIG_PM_SLEEP is not set:

    drivers/iio/common/hid-sensors/hid-sensor-trigger.c:212:12: error: 'hid_sensor_resume' defined but not used [-Werror=unused-function]

    This removes the #ifdef and instead marks all three PM functions
    as __maybe_unused, which covers all possible cases and is harder
    to get wrong.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 7f6cf7414538 ("iio: hid-sensors: use asynchronous resume")
    Signed-off-by: Jonathan Cameron <jic23@kernel.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>