[netdrv] cxgb4: fix thermal configuration dependencies
Message-id: <1548848714-17776-64-git-send-email-avynipad@redhat.com>
Patchwork-id: 239442
O-Subject: [PATCH RHEL7.7 63/80] cxgb4: fix thermal configuration dependencies
Bugzilla: 1642412
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642412

commit e70a57fa59bb7fefe063780a49e063d0d0f61863
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Oct 11 10:57:57 2018 +0200

    cxgb4: fix thermal configuration dependencies

    With CONFIG_THERMAL=m, we get a build error:

    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.c: In function 'cxgb4_thermal_get_trip_type':
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.c:48:11: error: 'struct adapter' has no member named 'ch_thermal'

    Once that is fixed by using IS_ENABLED() checks, we get a link error
    against the thermal subsystem when cxgb4 is built-in:

    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.o: In function `cxgb4_thermal_init':
    cxgb4_thermal.c:(.text+0x180): undefined reference to `thermal_zone_device_register'
    drivers/net/ethernet/chelsio/cxgb4/cxgb4_thermal.o: In function `cxgb4_thermal_remove':
    cxgb4_thermal.c:(.text+0x1e0): undefined reference to `thermal_zone_device_unregister'

    Finally, since CONFIG_THERMAL can be =m, the Makefile fails to pick up the
    extra file into built-in.a, and we get another link failure against the
    cxgb4_thermal_init/cxgb4_thermal_remove files, so the Makefile has to
    be adapted as well to work for both CONFIG_THERMAL=y and =m.

    Fixes: b18719157762 ("cxgb4: Add thermal zone support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: Kamal Heib <kheib@redhat.com>
Cc: Tony Camuso <tcamuso@redhat.com>
Cc: Venkatesh Pottem <vpottem@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>