[linux] include/linux/mmdebug.h: fix VM_WARN(_*)() with CONFIG_DEBUG_VM=n
Message-id: <1521624444-7979-7-git-send-email-crecklin@redhat.com>
Patchwork-id: 7397
O-Subject: [kernel team] [RHEL7.6 BZ 1553005 CVE-2018-7740 V2 PATCH 6/7] include/linux/mmdebug.h: fix VM_WARN[_*]() with CONFIG_DEBUG_VM=n
Bugzilla: 1553005
CVE: CVE-2018-7740
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Joe Lawrence <joe.lawrence@redhat.com>

commit 63eef99e7e340043c26856b6996dba543194075e
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Thu Mar 15 10:44:47 2018 +1100

    include/linux/mmdebug.h: fix VM_WARN[_*]() with CONFIG_DEBUG_VM=n

    These macros cause the build to break when someone uses their return value
    with CONFIG_DEBUG_VM=n:

    	if (VM_WARN(from > to, "%s called with a negative range\n", __func__))
     		return -EINVAL;

    mm/hugetlb.c: In function 'hugetlb_reserve_pages':
    mm/hugetlb.c:4378: error: void value not ignored as it ought to be

    Fix this up.

    Reported-by: Michal Hocko <mhocko@kernel.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>