[net] sched: prio: work around gcc-4.4.4 union initializer issues
Message-id: <20180531082654.12746-3-ivecera@redhat.com>
Patchwork-id: 218422
O-Subject: [RHEL7.6 net PATCH 2/2] net/sched/sch_prio.c: work around gcc-4.4.4 union initializer issues
Bugzilla: 1584297
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1584297

Upstream commit(s):
commit ef58ca38dbda0642e293bcaa2e05edc79677c617
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Thu Jan 18 16:30:49 2018 -0800

    net/sched/sch_prio.c: work around gcc-4.4.4 union initializer issues

    gcc-4.4.4 has problems witn anon union initializers.  Work around this.

    net/sched/sch_prio.c: In function 'prio_dump_offload':
    net/sched/sch_prio.c:260: error: unknown field 'stats' specified in initializer
    net/sched/sch_prio.c:260: warning: initialization makes integer from pointer without a cast
    net/sched/sch_prio.c:261: error: unknown field 'stats' specified in initializer
    net/sched/sch_prio.c:261: warning: initialization makes integer from pointer without a cast

    Fixes: 7fdb61b44c0c95 ("net: sch: prio: Add offload ability to PRIO qdisc")
    Cc: Nogah Frankel <nogahf@mellanox.com>
    Cc: Yuval Mintz <yuvalm@mellanox.com>
    Cc: Jiri Pirko <jiri@mellanox.com>
    Cc: David S. Miller <davem@davemloft.net>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>