[net] {xfrm, pktgen} Fix compiling error when CONFIG_XFRM is not set
Message-id: <20190222213038.10747-11-ivecera@redhat.com>
Patchwork-id: 242982
O-Subject: [RHEL7.7 net PATCH 10/81] {xfrm, pktgen} Fix compiling error when CONFIG_XFRM is not set
Bugzilla: 1680139
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1680139

Upstream commit(s):
commit 6bae919003602729d6f5920315bf71ca78bd9e48
Author: Fan Du <fan.du@windriver.com>
Date:   Fri Jan 10 14:39:13 2014 +0800

    {xfrm,pktgen} Fix compiling error when CONFIG_XFRM is not set

    0-DAY kernel build testing backend reported below error:
    All error/warnings:

       net/core/pktgen.c: In function 'pktgen_if_write':
    >> >> net/core/pktgen.c:1487:10: error: 'struct pktgen_dev' has no member named 'spi'
    >> >> net/core/pktgen.c:1488:43: error: 'struct pktgen_dev' has no member named 'spi'

    Fix this by encapuslating the code with CONFIG_XFRM.

    Cc: Fengguang Wu <fengguang.wu@intel.com>
    Signed-off-by: Fan Du <fan.du@windriver.com>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>