[uio] uio_hv_generic: fix new type mismatch warnings
Message-id: <1545231234-15987-9-git-send-email-mgamal@redhat.com>
Patchwork-id: 236191
O-Subject: [RHEL7.7 KERNEL PATCH v3 08/27] uio_hv_generic: fix new type mismatch warnings
Bugzilla: 1562041
RH-Acked-by: Cathy Avery <cavery@redhat.com>
RH-Acked-by: Vitaly Kuznetsov <vkuznets@redhat.com>

In commit 72d146578950 ("uio_hv_generic: fix type mismatch warnings"),
I addressed some warnings that show up with CONFIG_X86_PAE, now a new
change has added more of the same:

drivers/uio/uio_hv_generic.c: In function 'hv_uio_probe':
drivers/uio/uio_hv_generic.c:205:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
drivers/uio/uio_hv_generic.c:225:5: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]

The fix is the same as before, casting to uintptr_t as an intermediate.

Fixes: e7d214642a19 ("uio_hv_generic: create send and receive buffers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Stephen Hemminger <stephen@networkplumber.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit d6088e9a89f7c6fe9720978196c4d9799fd16c29)

Signed-off-by: Mohammed Gamal <mgamal@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>