[net] mii: report 0 for unknown lp_advertising
Message-id: <20180313171357.11809-3-ivecera@redhat.com>
Patchwork-id: 206672
O-Subject: [RHEL7.6 net PATCH 2/3] net: mii: report 0 for unknown lp_advertising
Bugzilla: 1554965
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1554965

Upstream commit(s):
commit dc0b2c9cb47a2176e1f341bfdc770745d24e072c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Nov 8 14:31:38 2016 +0100

    net: mii: report 0 for unknown lp_advertising

    The newly introduced mii_ethtool_get_link_ksettings function sets
    lp_advertising to an uninitialized value when BMCR_ANENABLE is not
    set:

    drivers/net/mii.c: In function 'mii_ethtool_get_link_ksettings':
    drivers/net/mii.c:224:2: error: 'lp_advertising' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    As documented in include/uapi/linux/ethtool.h, the value is
    expected to be zero when we don't know it, so let's initialize
    it to that.

    Fixes: bc8ee596afe8 ("net: mii: add generic function to support ksetting support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>