[tools] perf test: Fix build of BPF and LLVM on older glibc libraries
Message-id: <20181023074339.20119-34-jolsa@redhat.com>
Patchwork-id: 231406
O-Subject: [PATCH RHEL7.7 BZ1641373 033/294] perf test: Fix build of BPF and LLVM on older glibc libraries
Bugzilla: 1641373
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1641373
https://bugzilla.redhat.com/show_bug.cgi?id=1641373

upstream
========
commit 916d4092a1d2d7bb50630497be71ee4c4c2807fa
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Nov 18 17:38:49 2015 -0300

description
===========
  $ rpm -q glibc
  glibc-2.12-1.166.el6_7.1.x86_64

<SNIP>
    CC       /tmp/build/perf/tests/llvm.o
  cc1: warnings being treated as errors
  tests/llvm.c: In function test_llvm__fetch_bpf_obj:
  tests/llvm.c:53: error: declaration of index shadows a global declaration
  /usr/include/string.h:489: error: shadowed declaration is here
<SNIP>
    CC       /tmp/build/perf/tests/bpf.o
  cc1: warnings being treated as errors
  tests/bpf.c: In function __test__bpf:
  tests/bpf.c:149: error: declaration of index shadows a global declaration
  /usr/include/string.h:489: error: shadowed declaration is here
<SNIP>

Fixes: b31de018a628 ("perf test: Enhance the LLVM test: update basic BPF test program")
Fixes: ba1fae431e74 ("perf test: Add 'perf test BPF'")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>