[uapi] fix linux/tls.h userspace compilation error
Message-id: <20181129183712.19643-4-ivecera@redhat.com>
Patchwork-id: 234128
O-Subject: [RHEL7.7 PATCH 3/5] uapi: fix linux/tls.h userspace compilation error
Bugzilla: 1653376
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1653376

Backport note:
Only hunk(s) for include/uapi/linux/tls.h are included as it is only one
required.

Upstream commit(s):
commit b9f3eb499d84f8d4adcb2f9212ec655700b28228
Author: Dmitry V. Levin <ldv@altlinux.org>
Date:   Tue Nov 14 06:30:11 2017 +0300

    uapi: fix linux/tls.h userspace compilation error

    Move inclusion of a private kernel header <net/tcp.h>
    from uapi/linux/tls.h to its only user - net/tls.h,
    to fix the following linux/tls.h userspace compilation error:

    /usr/include/linux/tls.h:41:21: fatal error: net/tcp.h: No such file or directory

    As to this point uapi/linux/tls.h was totaly unusuable for userspace,
    cleanup this header file further by moving other redundant includes
    to net/tls.h.

    Fixes: 3c4d7559159b ("tls: kernel TLS support")
    Cc: <stable@vger.kernel.org> # v4.13+
    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>