[fs] ovl: select EXPORTFS
Message-id: <1507193066-9748-61-git-send-email-mszeredi@redhat.com>
Patchwork-id: 189178
O-Subject: [RHEL7.5 PATCH 060/111] ovl: select EXPORTFS
Bugzilla: 1485392
RH-Acked-by: David Howells <dhowells@redhat.com>
RH-Acked-by: Ian Kent <ikent@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1485392
Upstream status: Linus
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14171165
Testing: unionmount-testsuite, xfstests, pjd-fstest

commit 72d42504bd7faa6de1c1644b5e46652933e040a6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 11 13:34:29 2017 +0200

    ovl: select EXPORTFS

    We get a link error when EXPORTFS is not enabled:

    ERROR: "exportfs_encode_fh" [fs/overlayfs/overlay.ko] undefined!
    ERROR: "exportfs_decode_fh" [fs/overlayfs/overlay.ko] undefined!

    This adds a Kconfig 'select' statement for overlayfs, the same way that
    it is done for the other users of exportfs.

    Fixes: 3a1e819b4e80 ("ovl: store file handle of lower inode on copy up")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>

Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
---

Signed-off-by: Rafael Aquini <aquini@redhat.com>