[md] raid10: remove VLAIS
Message-id: <1530561984-30263-103-git-send-email-ncroxon@redhat.com>
Patchwork-id: 223389
O-Subject: [RHEL7.6 V3 PATCH 102/136] md: raid10: remove VLAIS
Bugzilla: 1494474
RH-Acked-by: Heinz Mauelshagen <heinzm@redhat.com>
RH-Acked-by: Xiao Ni <xni@redhat.com>

From: Matthias Kaehlcke <mka@chromium.org>

The raid10 driver can't be built with clang since it uses a variable
length array in a structure (VLAIS):

drivers/md/raid10.c:4583:17: error: fields must have a constant size:
  'variable length array in structure' extension will never be supported

Allocate the r10bio struct with kmalloc instead of using the VLAIS
construct.

Shaohua: set the MD_RECOVERY_INTR bit
Neil Brown: use GFP_NOIO

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Shaohua Li <shli@fb.com>
(cherry picked from commit 584ed9fa9532f8b9d5955628ff87ee3b2ab9f5a9)
Signed-off-by: Nigel Croxon <ncroxon@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>