[redhat] configs/s390: Enable CONFIG_SWIOTLB
Message-id: <20190725170542.8007-17-brueckner@redhat.com>
Patchwork-id: 267208
O-Subject: [RHEL7.8 PATCH 16/16] [redhat] configs/s390: Enable CONFIG_SWIOTLB
Bugzilla: 1642860
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

From: Philipp Rudo <prudo@redhat.com>

Bugzilla: 1642860
Depends: 1642859
Upstream Status: RHEL-only
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22721149
Tested: by IBM
Conflicts: None

Disable CONFIG_SWIOTLB for the s390 kdump kernel. When the config is
enabled the build for the kdump kernel fails with

lib/swiotlb.c: In function 'swiotlb_sync_sg':
lib/swiotlb.c:979:11: error: 'struct scatterlist' has no member named 'dma_length'
         sg->dma_length, dir, target);
	            ^

That's because there is an indirect dependency of SWIOTLB on PCI (struct
scatterlist.dma_length -> NEED_SG_DMA_LENGTH -> PCI), which is not set
for the kdump kernel.

Signed-off-by: Philipp Rudo <prudo@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>