[powerpc] kdump: Fix powernv build break when KEXEC_CORE=n
Message-id: <1524858360-4105-3-git-send-email-drosario@redhat.com>
Patchwork-id: 211719
O-Subject: [RHEL-7.6 BZ1559434 PATCH 2/2] powerpc/kdump: Fix powernv build break when KEXEC_CORE=n
Bugzilla: 1559434
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

From: "Desnes A. Nunes do Rosario" <drosario@redhat.com>

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1559434

DESCRIPTION:
------------
This patch is a backport of the following commit: 9109617545
Author: Guenter Roeck <linux@roeck-us.net>
Date: Mon, 12 Feb 2018 14:34:07 -0800

    If KEXEC_CORE is not enabled, powernv builds fail as follows.

      arch/powerpc/platforms/powernv/smp.c: In function 'pnv_smp_cpu_kill_self':
      arch/powerpc/platforms/powernv/smp.c:236:4: error:
            implicit declaration of function 'crash_ipi_callback'

    Add dummy function calls, similar to kdump_in_progress(), to solve the
    problem.

    Fixes: 4145f358644b ("powernv/kdump: Fix cases where the kdump kernel can get HMI's")
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Balbir Singh <bsingharora@gmail.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Desnes A. Nunes do Rosario <desnesn@linux.vnet.ibm.com>

UPSTREAM STATUS:
----------------
commit 910961754572a2f4c83ad7e610d180

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=910961754572a2f4c83ad7e610d180
----------------
Desnes A. Nunes do Rosario

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>