[infiniband] rdma/srpt: Fix RCU debug build error
Message-id: <20180412051314.17576-249-ddutile@redhat.com>
Patchwork-id: 209208
O-Subject: [PATCH RHEL-7.6 v2 248/318] RDMA/srpt: Fix RCU debug build error
Bugzilla: 1549856
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1549856

commit f97f43c9ed1dd9d1f7afc758fc31a619752d08f3
Author: Leon Romanovsky <leonro@mellanox.com>
Date:   Wed Jan 24 08:56:05 2018 +0200

    RDMA/srpt: Fix RCU debug build error

    Combination of CONFIG_DEBUG_OBJECTS_RCU_HEAD=y and
    CONFIG_INFINIBAND_SRPT=m produces the following build error.

    ERROR: "init_rcu_head" [drivers/infiniband/ulp/srpt/ib_srpt.ko] undefined!
    make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1
    make: *** [Makefile:1216: modules] Error 2

    The reason to it that init_rcu_head() is not exported and not supposed
    to be used in modules. It is needed for dynamic initialization of
    statically allocated rcu_head structures.

    Fixes: 795bc112cd5a ("IB/srpt: Make it safe to use RCU for srpt_device.rch_list")
    Fixes: a11253142e6d ("IB/srpt: Rework multi-channel support")
    Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
    Signed-off-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

RHEL-7 NOTE:
Split this backport in two pieces, one to fix backport of 795bc112cd5a
since it breaks a RHEL-7 bisect build.  The second half of this patch
is added after the backport of a11253142e6d to fix the RHEL-7 bisect build
after it.

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>