[tools] perf probe: Add warning message if there is unexpected event name
Message-id: <20181023074339.20119-178-jolsa@redhat.com>
Patchwork-id: 231563
O-Subject: [PATCH RHEL7.7 BZ1641373 177/294] perf probe: Add warning message if there is unexpected event name
Bugzilla: 1641373
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1641373
https://bugzilla.redhat.com/show_bug.cgi?id=1641373

upstream
========
commit 9f5c6d8777a2d962b0eeacb2a16f37da6bea545b
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Sat Dec 9 01:26:46 2017 +0900

description
===========
This improve the error message so that user can know event-name error
before writing new events to kprobe-events interface.

E.g.
   ======
   #./perf probe -x /lib64/libc-2.25.so malloc_get_state*
   Internal error: "malloc_get_state@GLIBC_2" is an invalid event name.
     Error: Failed to add events.
   ======

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>