[netdrv] cxgb4: enable ZLIB_DEFLATE when building cxgb4
Message-id: <1524289424-31421-60-git-send-email-avynipad@redhat.com>
Patchwork-id: 210524
O-Subject: [RHEL7.6 PATCH v2 059/110] cxgb4: enable ZLIB_DEFLATE when building cxgb4
Bugzilla: 1523208 1523151
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1523151
Bugzilla: http://bugzilla.redhat.com/1523208

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>

Conflicts:
Minor conflict in Makefile because upstream cxgb4_fcoe feature
is not present in RHEL7 kernel(84a200b 'cxgb4: add cxgb4_fcoe.c for FCoE')

commit a1cf9c9ffe652a4f109eb2cd8e69d8fcdb855d00
Author: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
Date:   Wed Jan 24 13:31:04 2018 +0530

    cxgb4: enable ZLIB_DEFLATE when building cxgb4

    Fixes:
    drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.c:39:5: error:
    redefinition of 'cudbg_compress_buff'
        int cudbg_compress_buff(struct cudbg_init *pdbg_init,
            ^~~~~~~~~~~~~~~~~~~
       In file included from
    drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.c:23:0:
       drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.h:45:19: note: previous
    definition of 'cudbg_compress_buff' was here
        static inline int cudbg_compress_buff(struct cudbg_init *pdbg_init,
                          ^~~~~~~~~~~~~~~~~~~

    Fixes: 91c1953de387 ("cxgb4: use zlib deflate to compress firmware dump")
    Signed-off-by: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
    Signed-off-by: Ganesh Goudar <ganeshgr@chelsio.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Don Dutile <ddutile@redhat.com