[netdrv] mlx5e: fix TLS dependency
Message-id: <1549457075-6314-242-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240198
O-Subject: [RHEL7.7 BZ 1642498 241/729] net/mlx5e: fix TLS dependency
Bugzilla: 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Upstream: v4.18-rc1

commit c3cd281e2bc8da18f225f1191e9751d771411933
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri May 25 23:36:06 2018 +0200

    net/mlx5e: fix TLS dependency

    With CONFIG_TLS=m and MLX5_CORE_EN=y, we get a link failure:

    drivers/net/ethernet/mellanox/mlx5/core/en_accel/tls_rxtx.o: In function `mlx5e_tls_handle_ooo':
    tls_rxtx.c:(.text+0x24c): undefined reference to `tls_get_record'
    drivers/net/ethernet/mellanox/mlx5/core/en_accel/tls_rxtx.o: In function `mlx5e_tls_handle_tx_skb':
    tls_rxtx.c:(.text+0x9a8): undefined reference to `tls_device_sk_destruct'

    This narrows down the dependency to only allow the configurations
    that will actually work. The existing dependency on TLS_DEVICE is
    not sufficient here since MLX5_EN_TLS is a 'bool' symbol.

    Fixes: c83294b9efa5 ("net/mlx5e: TLS, Add Innova TLS TX support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Acked-by: Boris Pismenny <borisp@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Cc: Jesper Dangaard Brouer <brouer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>