[netdrv] mlx5e: E-Switch, Add peer miss rules
Message-id: <1549457075-6314-684-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240637
O-Subject: [RHEL7.7 BZ 1642498 683/729] net/mlx5e: E-Switch, Add peer miss rules
Bugzilla: 1642355 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Bugzilla: http://bugzilla.redhat.com/1642355
Upstream: v5.0-rc1
Backport notes:
 - Saw same compilation error as in upstream when HEAD points to this patch:
   drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads.c:566:13: error: struct <anonymous> has no member named vhca_id_valid
   So, in order to fix incremental build, I took a hunk from commit:
   04de7dda7394 ("net/mlx5e: Infrastructure for duplicated offloading of TC flows")
   vhca_id_valid was replaced by flags.

commit ac004b8321281b9da7d9a99674241e60e49ffc8a
Author: Roi Dayan <roid@mellanox.com>
Date:   Sun Nov 11 17:50:16 2018 +0200

    net/mlx5e: E-Switch, Add peer miss rules

    In the sriov offloads mode, packets that are not matched by any
    other rule are sent towards the e-switch vport manager for further
    processing.

    Under upcoming patches (e.g for uplink LAG), packets sent from VF
    vports belonging to esw0 (e-switch related to PF0) might end up in
    esw1 (e-switch related to PF1) due to muxing logic applied by the
    FW.

    In such a case we still want the missed packet to be sent to the
    "base" esw manager vport in order to present the control plane a
    consistent view of the source (VF reresentor) port.

    Signed-off-by: Roi Dayan <roid@mellanox.com>
    Signed-off-by: Aviv Heller <avivh@mellanox.com>
    Signed-off-by: Shahar Klein <shahark@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>