[fs] xfs: avoid harmless gcc-7 warnings
Message-id: <20180521171030.115571-104-bfoster@redhat.com>
Patchwork-id: 216707
O-Subject: [RHEL7.6 PATCH 103/136] xfs: avoid harmless gcc-7 warnings
Bugzilla: 1579873
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

commit 0cbe48cc5814ae26e4058c5d666914c86a4a6b5d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jun 14 21:35:34 2017 -0700

    xfs: avoid harmless gcc-7 warnings

    gcc-7 flags the use of integer math inside of a condition
    as a potential bug:

    fs/xfs/xfs_bmap_util.c: In function 'xfs_swap_extents_check_format':
    fs/xfs/xfs_bmap_util.c:1619:8: error: '<<' in boolean context, did you mean '<' ? [-Werror=int-in-bool-context]
    fs/xfs/xfs_bmap_util.c:1629:8: error: '<<' in boolean context, did you mean '<' ? [-Werror=int-in-bool-context]

    There is already a helper function for testing the di_forkoff
    field for zero, so let's use that instead to shut up the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>