[infiniband] ib/mlx4: Potential buffer overflow in _mlx4_set_path()
Message-id: <1524752069-32403-17-git-send-email-ealfasi@redhat.com>
Patchwork-id: 211579
O-Subject: [RHEL7.6 PATCH v2 16/29] IB/mlx4: Potential buffer overflow in _mlx4_set_path()
Bugzilla: 1520295
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1520295

commit 54a6d63f14bdb4e899bbb4128d32717074d13862
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Tue Dec 5 17:39:23 2017 +0300

    IB/mlx4: Potential buffer overflow in _mlx4_set_path()

    Smatch complains about this code:

        drivers/infiniband/hw/mlx4/qp.c:1827 _mlx4_set_path()
        error: buffer overflow 'dev->dev->caps.gid_table_len' 3 <= 255

    The mlx4_ib_gid_index_to_real_index() does check that "port" is within
    bounds, but we don't check the return value for errors.  It seems simple
    enough to add a check for that.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Erez Alfasi <ealfasi@redhat.com>

Cc: Don Dutile <ddutile@redhat.com>
Cc: Erez Alfasi <ealfasi@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>