[crypto] qat - reduce stack size with KASAN
Message-id: <20180522163832.24772-10-nhorman@redhat.com>
Patchwork-id: 216827
O-Subject: [RHEL7.6 PATCH 09/13] crypto: qat - reduce stack size with KASAN
Bugzilla: 1546163
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Neil Horman <nhorman@redhat.com>

Passing the register value by reference here leads a large amount of stack being
used when CONFIG_KASAN is enabled:

drivers/crypto/qat/qat_common/qat_hal.c: In function 'qat_hal_exec_micro_inst.constprop':
drivers/crypto/qat/qat_common/qat_hal.c:963:1: error: the frame size of 1792 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

Changing the register-read function to return the value instead reduces the stack
size to around 800 bytes, most of which is for the 'savuwords' array. The function
now no longer returns an error code, but nothing ever evaluated that anyway.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 8c9478a400b7efdeab89797cfb77e4e845fb34fb)

BZ: 1546163
Testing: Tested by Intel and myself
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15983539
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>