[kernel] bpf_trace: Make dependent on PERF_EVENTS
Message-id: <20180612134439.10359-67-jolsa@redhat.com>
Patchwork-id: 221294
O-Subject: [PATCH RHEL7.6 BZ1311586 66/71] bpf_trace: Make dependent on PERF_EVENTS
Bugzilla: 1311586
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit a31d82d85afdcbdb8c4128dfd6146992dc6b3576
Author: Steven Rostedt <rostedt@goodmis.org>
Date:   Tue Nov 10 15:28:17 2015 -0500

description
===========
Arnd Bergmann reported:

  In my ARM randconfig tests, I'm getting a build error for
  newly added code in bpf_perf_event_read and bpf_perf_event_output
  whenever CONFIG_PERF_EVENTS is disabled:

  kernel/trace/bpf_trace.c: In function 'bpf_perf_event_read':
  kernel/trace/bpf_trace.c:203:11: error: 'struct perf_event' has no member named 'oncpu'
  if (event->oncpu != smp_processor_id() ||
           ^
  kernel/trace/bpf_trace.c:204:11: error: 'struct perf_event' has no member named 'pmu'
        event->pmu->count)

  This can happen when UPROBE_EVENT is enabled but KPROBE_EVENT
  is disabled. I'm not sure if that is a configuration we care
  about, otherwise we could prevent this case from occuring by
  adding Kconfig dependencies.

Looking at this further, it's really that UPROBE_EVENT enables PERF_EVENTS.
By just having BPF_EVENTS depend on PERF_EVENTS, then all is fine.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>