[usb] usb: catc: constify usb_device_id and fix space before '[' error
Message-id: <1526649550-17190-344-git-send-email-torez@redhat.com>
Patchwork-id: 216121
O-Subject: [RHEL7.6 PATCH BZ1540721 343/681] net: usb: catc: constify usb_device_id and fix space before '[' error
Bugzilla: 1540721
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1540721
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16352184
Testing: on local desktop and Dell Precision 5510 laptop

commit 2f622c4951aade21d9d8c66dc9d6276012a1d8b5
Author: Arvind Yadav <arvind.yadav.cs@gmail.com>
Date:   Tue Aug 8 21:28:01 2017 +0530

    net: usb: catc: constify usb_device_id and fix space before '[' error

    usb_device_id are not supposed to change at runtime. All functions
    working with usb_device_id provided by <linux/usb.h> work with
    const usb_device_id. So mark the non-const structs as const.

    Fix checkpatch.pl error:
    ERROR: space prohibited before open square bracket '['.

    Signed-off-by: Arvind Yadav <arvind.yadav.cs@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>