[netdrv] mlxsw: include explicitly linux/if.h to avoid build failure
Message-id: <20171222131006.18481-1-ivecera@redhat.com>
Patchwork-id: 202693
O-Subject: [RHEL7.5 PATCH 1/2] mlxsw: include explicitly linux/if.h to avoid build failure
Bugzilla: 1525606
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1525606

Description:
The lack of upstream commit 1fe8e0f074c7 ("include/uapi/linux/if_tunnel.h:
include linux/if.h, linux/ip.h and linux/in6.h") causes a build failure
of mlxsw driver:
<snip>
In file included from include/linux/if_tunnel.h:6:0,
                 from include/net/ip_tunnels.h:4,
                 from drivers/net/ethernet/mellanox/mlxsw/spectrum_ipip.c:35:
include/uapi/linux/if_tunnel.h:36:14: error: 'IFNAMSIZ' undeclared here (not in a function)
  char   name[IFNAMSIZ];
</snip>

The mentioned commit was backported to RHEL7 but caused of build failure
of the systemd package due to incompatibility between several UAPI
headers and their glibc's counterparts. To solve this mlxsw build failure
we need to include linux/if.h in spectrum_ipip.c explicitly.

Test status:
Build only - kernel was built fine as well as systemd.

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>