[hid] intel-ish-hid: format 32-bit integers with %X
Message-id: <1510839526-11340-50-git-send-email-gtiwari@redhat.com>
Patchwork-id: 198297
O-Subject: [ PATCH BZ 1475903 49/59] HID: intel-ish-hid: format 32-bit integers with %X
Bugzilla: 1475903
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1475903

commit 5299a92a3b98b91b7230662b8b9b6c64bcf8cae6
Author: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
Date:   Thu Dec 22 11:09:10 2016 +0100

    HID: intel-ish-hid: format 32-bit integers with %X

    In ishtp_hid_probe(), use %04X instead of %04hX to format __u32 values,
    in order to silent a format error reported by clang:

        drivers/hid/intel-ish-hid/ishtp-hid.c:212:3: error: format specifies
        type 'unsigned short' but the argument has type '__u32' (aka
        'unsigned int') [-Werror,-Wformat]
                        hid->vendor, hid->product);
                        ^~~~~~~~~~~
        drivers/hid/intel-ish-hid/ishtp-hid.c:212:16: error: format
        specifies type 'unsigned short' but the argument has type '__u32'
        (aka 'unsigned int') [-Werror,-Wformat]
                        hid->vendor, hid->product);
                                     ^~~~~~~~~~~~

    Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>