[tools] perf record: Fix documentation for a inexistent option '-l'
Message-id: <20180419185703.28105-241-jolsa@redhat.com>
Patchwork-id: 210107
O-Subject: [PATCH RHEL7.6 BZ1540862 240/245] perf record: Fix documentation for a inexistent option '-l'
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 3f50f614d61f91ad30b1947c429d1f235493a7f9
Author: Taeung Song <treeze.taeung@gmail.com>
Date: Sat Oct 14 00:10:12 2017 +0900

description
===========
'perf record' had a '-l' option that meant "scale counter values" a very
long time ago, but it currently belongs to 'perf stat' as '-c'.  So
remove it. I found this problem in the below case.

    $ perf record -e cycles -l sleep 3
      Error: unknown switch `l

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>