[netdrv] net/mlx5e: reduce stack usage in mlx5_eswitch_termtbl_create
Message-id: <20190808155519.15358-14-ahleihel@redhat.com>
Patchwork-id: 268571
O-Subject: [RHEL7.8 BZ 1737464 13/49] net/mlx5e: reduce stack usage in mlx5_eswitch_termtbl_create
Bugzilla: 1737464 1676558
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1676558
Bugzilla: http://bugzilla.redhat.com/1737464
Upstream: v5.3-rc1

Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/fs_core.c
   Context diff due to missing commit:
   bb0ee7dcc4ec ("net/mlx5: Add flow context for flow tag")
   ---> Also alloc_fte and add_rule_fg still take match_value (instead of
        struct mlx5_flow_spec) which should be changed to const as well.

commit 5233794b179136d597b84188c1285148f07012e6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jun 18 13:15:06 2019 +0200

    net/mlx5e: reduce stack usage in mlx5_eswitch_termtbl_create

    Putting an empty 'mlx5_flow_spec' structure on the stack is a bit
    wasteful and causes a warning on 32-bit architectures when building
    with clang -fsanitize-coverage:

    drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads_termtbl.c: In function 'mlx5_eswitch_termtbl_create':
    drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads_termtbl.c:90:1: error: the frame size of 1032 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Since the structure is never written to, we can statically allocate
    it to avoid the stack usage. To be on the safe side, mark all
    subsequent function arguments that we pass it into as 'const'
    as well.

    Fixes: 10caabdaad5a ("net/mlx5e: Use termination table for VLAN push actions")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Acked-by: Mark Bloch <markb@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>