[thunderbolt] Fix build error in eeprom.c
Message-id: <1512650446-15556-17-git-send-email-jeremymc@redhat.com>
Patchwork-id: 201640
O-Subject: [PATCH RHEL7.5 v3 016/113] thunderbolt: Fix build error in eeprom.c
Bugzilla: 1172010
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jeremy McNicoll <jeremymc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1172010

commit 2b35404ef7762af15ce138281c91b4cc0e2d0124
Author: Sachin Kamat <sachin.kamat@samsung.com>
Date:   Fri Jun 20 14:32:29 2014 +0530

    thunderbolt: Fix build error in eeprom.c

    Fixes the below error:
    drivers/thunderbolt/eeprom.c:407:2: error: implicit declaration of function kzalloc [-Werror=implicit-function-declaration]
    drivers/thunderbolt/eeprom.c:444:2: error: implicit declaration of function kfree [-Werror=implicit-function-declaration]

    Signed-off-by: Sachin Kamat <sachin.kamat@samsung.com>
    Acked-by: Andreas Noever <andreas.noever@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>