[powerpc] pseries: Fix build break for SPLPAR=n and CPU hotplug
Message-id: <1533137315-25603-7-git-send-email-gduarte@redhat.com>
Patchwork-id: 225859
O-Subject: [RHEL7.6 PATCH BZ 1544437 6/6] powerpc/pseries: Fix build break for SPLPAR=n and CPU hotplug
Bugzilla: 1544437
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: Serhii Popovych <spopovyc@redhat.com>

BZ 1544437
Upstream Status: 82343484a2d4c97a03bfd81303b5493c65f05c50

commit 82343484a2d4c97a03bfd81303b5493c65f05c50
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Mon Feb 12 14:34:08 2018 -0800

    powerpc/pseries: Fix build break for SPLPAR=n and CPU hotplug

    Commit e67e02a544e9 ("powerpc/pseries: Fix cpu hotplug crash with
    memoryless nodes") adds an unconditional call to
    find_and_online_cpu_nid(), which is only declared if CONFIG_PPC_SPLPAR
    is enabled. This results in the following build error if this is not
    the case.

      arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_online_cpu':
      arch/powerpc/platforms/pseries/hotplug-cpu.c:369:
      			undefined reference to `.find_and_online_cpu_nid'

    Follow the guideline provided by similar functions and provide a dummy
    function if CONFIG_PPC_SPLPAR is not enabled. This also moves the
    external function declaration into an include file where it should be.

    Fixes: e67e02a544e9 ("powerpc/pseries: Fix cpu hotplug crash with memoryless nodes")
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    [mpe: Change subject to emphasise the build fix]
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>