[pci] msi: Silence compiler warning about unused variable on s390x
Message-id: <1511260817-1538-8-git-send-email-thuth@redhat.com>
Patchwork-id: 199682
O-Subject: [RHEL7.5 BZ 1500170 v2 PATCH 07/11] pci/msi: Silence compiler warning about unused variable on s390x
Bugzilla: 1500170
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>

Upstream Status: downstream only

GCC complains on s390x:

drivers/pci/msi.c: In function free_msi_irqs:
drivers/pci/msi.c:344:6: error: unused variable i [-Werror=unused-variable]
  int i, count = 0;

Move the variable into the #ifdef block where it is needed.

Signed-off-by: Thomas Huth <thuth@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>