[infiniband] rdma/iw_cxgb4: Fix the unchecked ep dereference
Message-id: <1548854283-20896-25-git-send-email-avynipad@redhat.com>
Patchwork-id: 239485
O-Subject: [RHEL7.7 BZ 1642419 24/25] RDMA/iw_cxgb4: Fix the unchecked ep dereference
Bugzilla: 1642419
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642419
Upstream info: rdma tree->for-next branch

commit 3352976c892301fd576a2e9ff0ac7337b2e2ca48
Author: Raju Rangoju <rajur@chelsio.com>
Date:   Fri Jan 11 20:27:18 2019 +0530

    RDMA/iw_cxgb4: Fix the unchecked ep dereference

    The patch 944661dd97f4: "RDMA/iw_cxgb4: atomically lookup ep and get a
    reference" from May 6, 2016, leads to the following Smatch complaint:

        drivers/infiniband/hw/cxgb4/cm.c:2953 terminate()
        error: we previously assumed 'ep' could be null (see line 2945)

    Fixes: 944661dd97f4 ("RDMA/iw_cxgb4: atomically lookup ep and get a reference")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Raju Rangoju <rajur@chelsio.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Cc: Kamal Heib <kheib@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>