[infiniband] infiniband: avoid overflow warning
Message-id: <20171116210913.11180-187-ddutile@redhat.com>
Patchwork-id: 198766
O-Subject: [PATCH RHEL-7.5 186/372] infiniband: avoid overflow warning
Bugzilla: 1499364 1456704
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

commit 5f8a4db715ca21c3195b5eea24e26574c0f5acfa
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 31 08:50:05 2017 +0200

    infiniband: avoid overflow warning

    A sockaddr_in structure on the stack getting passed into rdma_ip2gid
    triggers this warning, since we memcpy into a larger sockaddr_in6
    structure:

    In function 'memcpy',
        inlined from 'rdma_ip2gid' at include/rdma/ib_addr.h:175:3,
        inlined from 'addr_event.isra.4.constprop' at drivers/infiniband/core/roce_gid_mgmt.c:693:2,
        inlined from 'inetaddr_event' at drivers/infiniband/core/roce_gid_mgmt.c:716:9:
    include/linux/string.h:305:4: error: call to '__read_overflow2' declared with attribute error: detected read beyond size of object passed as 2nd parameter

    The warning seems appropriate here, but the code is also clearly
    correct, so we really just want to shut up this instance of the
    output.

    The best way I found so far is to avoid the memcpy() call and instead
    replace it with a struct assignment.

    Fixes: 6974f0c4555e ("include/linux/string.h: add the option of fortified string.h functions")
    Cc: Daniel Micay <danielmicay@gmail.com>
    Cc: Kees Cook <keescook@chromium.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>