[scsi] scsi: qla2xxx: Fix code indentation for qla27xx_fwdt_entry
Message-id: <20190801155618.12650-25-hmadhani@redhat.com>
Patchwork-id: 267811
O-Subject: [RHEL 7.8 e-stor PATCH 024/118] scsi: qla2xxx: Fix code indentation for qla27xx_fwdt_entry
Bugzilla: 1729270
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Himanshu Madhani <hmadhani@marvell.com>

Bugzilla 1729270

This patch fixes following checkpatch ERROR

 ERROR: space prohibited before that ',' (ctx:WxW)

No change is functionality due to this patch.

Signed-off-by: Himanshu Madhani <hmadhani@marvell.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 5241f7ca62b35e582c3b94aea62a0ac42df369c7)
Signed-off-by: Himanshu Madhani <hmadhani@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>