[tools] perf tests: Add valid callback for parse-events test
Message-id: <20190218130507.16170-163-jolsa@redhat.com>
Patchwork-id: 242154
O-Subject: [PATCH RHEL7 BZ1672893 162/187] perf tests: Add valid callback for parse-events test
Bugzilla: 1672893
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1672893
https://bugzilla.redhat.com/show_bug.cgi?id=1672893

upstream
========
commit 16ddcfbf7f3d07aa781e26b39f2c28636a4ed2fd
Author: Jiri Olsa <jolsa@kernel.org>
Date: Mon Jun 11 11:34:22 2018 +0200

description
===========
Adding optional 'valid' callback for events tests in parse-events
object, so we don't try to parse PMUs, which are not supported.

Following line is displayed for skipped test:

  running test 52 'intel_pt//u'... SKIP

Committer note:

Use named initializers in the struct evlist_test variable to avoid
breaking the build on centos:5, 6 and others with a similar gcc:

  cc1: warnings being treated as errors
  tests/parse-events.c: In function 'test_pmu_events':
  tests/parse-events.c:1817: error: missing initializer
  tests/parse-events.c:1817: error: (near initialization for 'e.type')

Signed-off-by: Jan Stancek <jstancek@redhat.com>