[crypto] qat - avoid an uninitialized variable warning
Message-id: <20171117200718.23930-17-nhorman@redhat.com>
Patchwork-id: 199081
O-Subject: [RHEL 7.4 v3 PATCH 16/21] crypto: qat - avoid an uninitialized variable warning
Bugzilla: 1475478
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: Neil Horman <nhorman@redhat.com>

After commit 9e442aa6a753 ("x86: remove DMA_ERROR_CODE"), the inlining
decisions in the qat driver changed slightly, introducing a new false-positive
warning:

drivers/crypto/qat/qat_common/qat_algs.c: In function 'qat_alg_sgl_to_bufl.isra.6':
include/linux/dma-mapping.h:228:2: error: 'sz_out' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/crypto/qat/qat_common/qat_algs.c:676:9: note: 'sz_out' was declared here

The patch that introduced this is correct, so let's just avoid the
warning in this driver by rearranging the unwinding after an error
to make it more obvious to the compiler what is going on.

The problem here is the 'if (unlikely(dma_mapping_error(dev, blp)))'
check, in which the 'unlikely' causes gcc to forget what it knew about
the state of the variables. Cleaning up the dma state in the reverse
order it was created means we can simplify the logic so it doesn't have
to know about that state, and also makes it easier to understand.

Cc: Christoph Hellwig <hch@lst.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit 72eed063767e131831fa10a0909c39a0254836ec)

Note: Had to do some more const removal here to avoid compiler warnings
as well as rename some gotos due to previously skipped backports

BZ: 1475478
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14328583
Testing: Tested by myself with good results
Signed-off-by: Rafael Aquini <aquini@redhat.com>