[netdrv] mlx5e: hide an unused variable
Message-id: <1529396089-5899-6-git-send-email-ahleihel@redhat.com>
Patchwork-id: 222363
O-Subject: [RHEL7.6 BZ 1588530 v2 05/15] net/mlx5e: hide an unused variable
Bugzilla: 1591249
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Ken Cox <jkc@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1591249

commit 74bd5d56bfcb857abb5ae7d9f47933be9d288cbd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 3 23:40:11 2018 +0100

    net/mlx5e: hide an unused variable

    The uplink_rpriv variable was added at the start of the function but
    only used inside of an #ifdef:

    drivers/net/ethernet/mellanox/mlx5/core/en_tc.c: In function 'mlx5e_route_lookup_ipv6':
    drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:1549:25: error: unused variable 'uplink_rpriv' [-Werror=unused-variable]

    This moves the declaration into that #ifdef as well.

    Fixes: 5ed99fb421d4 ("net/mlx5e: Move ethernet representors data into separate struct")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Cc: Don Dutile <ddutile@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>