[netdrv] mlxsw: spectrum: Add bridge dependency for spectrum
Message-id: <20171013205835.26049-120-ivecera@redhat.com>
Patchwork-id: 193469
O-Subject: [RHEL7.5 PATCH 119/245] mlxsw: spectrum: Add bridge dependency for spectrum
Bugzilla: 1486860
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1486860

Upstream commit(s):
commit 0266f79778de0afadd070941aae493c28529d974
Author: Ido Schimmel <idosch@mellanox.com>
Date:   Wed May 31 21:33:42 2017 +0300

    mlxsw: spectrum: Add bridge dependency for spectrum

    When BRIDGE is a loadable module, MLXSW_SPECTRUM mustn't be built-in:

    drivers/built-in.o: In function `mlxsw_sp_bridge_device_create':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_switchdev.c:145: undefined reference to `br_vlan_enabled'
    drivers/net/ethernet/mellanox/mlxsw/spectrum_switchdev.c:158: undefined reference to `br_multicast_enabled'
    drivers/built-in.o: In function `mlxsw_sp_dev_rif_type':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:2972: undefined reference to `br_vlan_enabled'
    drivers/built-in.o: In function `mlxsw_sp_inetaddr_vlan_event':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:3310: undefined reference to `br_vlan_enabled'

    Add Kconfig dependency to enforce usable configurations.

    Fixes: c57529e1d5d8 ("mlxsw: spectrum: Replace vPorts with Port-VLAN")
    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Reported-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
    Tested-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>