cpu/speculation: Add prototype for cpu_show_srbds()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2090249
CVE: CVE-2022-21123
CVE: CVE-2022-21125
CVE: CVE-2022-21166
Conflicts: as documented on the backport notes section.

This patch is a backport of the following upstream commit:
commit 2accfa69050c2a0d6fc6106f609208b3e9622b26
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Wed Jun 17 07:14:10 2020 -0700

    cpu/speculation: Add prototype for cpu_show_srbds()

    0-day is not happy that there is no prototype for cpu_show_srbds():

      drivers/base/cpu.c:565:16: error: no previous prototype for 'cpu_show_srbds'

    Fixes: 7e5b3c267d25 ("x86/speculation: Add Special Register Buffer Data Sampling (SRBDS) mitigation")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20200617141410.93338-1-linux@roeck-us.net

RHEL BACKPORT NOTES:
* minor context difference due to RHEL7 missing upstream commit
  8db148606514 ("include, lib: add __printf attributes to several function prototypes")

Signed-off-by: Rafael Aquini <aquini@redhat.com>