[infiniband] infiniband/ulp/srpt/ib_srpt.c: fix build with gcc-4.4.4
Message-id: <20181129133352.19421-46-kheib@redhat.com>
Patchwork-id: 234048
O-Subject: [PATCH RHEL-7.7 045/141] drivers/infiniband/ulp/srpt/ib_srpt.c: fix build with gcc-4.4.4
Bugzilla: 1641363
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1641363

commit 06892cc190550807d332c95a0114c7e175584012
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Tue Mar 13 15:06:45 2018 -0700

    drivers/infiniband/ulp/srpt/ib_srpt.c: fix build with gcc-4.4.4

    gcc-4.4.4 has issues with initialization of anonymous unions:

    drivers/infiniband/ulp/srpt/ib_srpt.c: In function 'srpt_zerolength_write':
    drivers/infiniband/ulp/srpt/ib_srpt.c:854: error: unknown field 'wr_cqe' specified in initializer
    drivers/infiniband/ulp/srpt/ib_srpt.c:854: warning: initialization makes integer from pointer without a cast

    Work aound this.

    Fixes: 2a78cb4db487 ("IB/srpt: Fix an out-of-bounds stack access in srpt_zerolength_write()")
    Cc: Bart Van Assche <bart.vanassche@wdc.com>
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Jason Gunthorpe <jgg@mellanox.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>