[scsi] qedf: fix LTO-enabled build
Message-id: <1526913544-30231-4-git-send-email-cdupuis@redhat.com>
Patchwork-id: 216574
O-Subject: [PATCH RHEL 7.6 e-stor 03/23] scsi: qedf: fix LTO-enabled build
Bugzilla: 1566547
RH-Acked-by: Chris Leech <cleech@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

commit d9ea463a1cc7f0a6254cbd8228e1948c345a4acd
https://kernel.googlesource.com/pub/scm/linux/kernel/git/jejb/scsi.git

The prototype for qedf_dbg_fops/qedf_debugfs_ops doesn't match the definition,
which causes the final link to fail with link-time optimizations:

drivers/scsi/qedf/qedf_main.c:34: error: type of 'qedf_dbg_fops' does not match original declaration [-Werror=lto-type-mismatch]
 extern struct file_operations qedf_dbg_fops;

drivers/scsi/qedf/qedf_debugfs.c:443: note: 'qedf_dbg_fops' was previously declared here
 const struct file_operations qedf_dbg_fops[] = {

drivers/scsi/qedf/qedf_main.c:33: error: type of 'qedf_debugfs_ops' does not match original declaration [-Werror=lto-type-mismatch]
 extern struct qedf_debugfs_ops qedf_debugfs_ops;

drivers/scsi/qedf/qedf_debugfs.c:102: note: 'qedf_debugfs_ops' was previously declared here
 struct qedf_debugfs_ops qedf_debugfs_ops[] = {

This corrects the prototype and moves it into a shared header file where it
belongs. The file operations can also be marked 'const' like the
qedf_debugfs_ops.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Chad Dupuis <chad.dupuis@cavium.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>