[netdrv] bnxt_en: avoid string overflow for record->system_name
Message-id: <709fcdd1ba4ed2cff5a11121939c9757394eb881.1549483148.git.jtoppins@redhat.com>
Patchwork-id: 240815
O-Subject: [RHEL7.7 PATCH 051/133] bnxt_en: avoid string overflow for record->system_name
Bugzilla: 1643317
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

The utsname()->nodename string may be 64 bytes long, and it gets
copied without the trailing nul byte into the shorter record->system_name,
as gcc now warns:

In file included from include/linux/bitmap.h:9,
                 from include/linux/ethtool.h:16,
                 from drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:13:
In function 'strncpy',
    inlined from 'bnxt_fill_coredump_record' at drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:2863:2:
include/linux/string.h:254:9: error: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]

Using strlcpy() at least avoids overflowing the destination buffer
and adds proper nul-termination. It may still truncate long names
though, which probably can't be solved here.

Fixes: 6c5657d085ae ("bnxt_en: Add support for ethtool get dump.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Michael Chan <michael.chan@broadcom.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 3d46eee5a5f2f22ca04e2139e8c9a16b81d16073)
Bugzilla: 1643317
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20065938
Tested: basic boot test as well as partner testing
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>