[fs] block, dax: use correct format string in bdev_dax_supported
Message-id: <20171121145952.29691-62-jmoyer@redhat.com>
Patchwork-id: 199763
O-Subject: [RHEL7.5 PATCH 061/138] block, dax: use correct format string in bdev_dax_supported
Bugzilla: 1457559
RH-Acked-by: Al Stone <ahs3@redhat.com>
RH-Acked-by: Ming Lei <ming.lei@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1457559
Brew: 14590444

commit 67fd38973513c341c84654ae2f819089b840a39b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Apr 27 16:30:41 2017 +0200

    block, dax: use correct format string in bdev_dax_supported

    The new message has an incorrect format string, causing a warning in some
    configurations:

    fs/block_dev.c: In function 'bdev_dax_supported':
    fs/block_dev.c:779:5: error: format '%d' expects argument of type 'int', but argument 2 has type 'long int' [-Werror=format=]
         "error: dax access failed (%d)", len);

    This changes it to use the correct %ld instead of %d.

    Fixes: 2093f2e9dfec ("block, dax: convert bdev_dax_supported() to dax_direct_access()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>