[scsi] qla2xxx: Fix smatch warning in qla25xx_delete_ rsp|req _que
Message-id: <20180509135614.21599-66-hmadhani@redhat.com>
Patchwork-id: 214107
O-Subject: [RHEL 7.6 e-stor PATCH 065/143] scsi: qla2xxx: Fix smatch warning in qla25xx_delete_{rsp|req}_que
Bugzilla: 1547714
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Himanshu Madhani <himanshu.madhani@cavium.com>

commit 62aa281470fdb7c0796d63a1cc918a8c1f02dde2

This patch fixes following warnings reported by smatch:

drivers/scsi/qla2xxx/qla_mid.c:586 qla25xx_delete_req_que()
error: we previously assumed 'req' could be null (see line 580)

drivers/scsi/qla2xxx/qla_mid.c:602 qla25xx_delete_rsp_que()
error: we previously assumed 'rsp' could be null (see line 596)

Fixes: 7867b98dceb7 ("scsi: qla2xxx: Fix memory leak in dual/target mode")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Himanshu Madhani <himanshu.madhani@cavium.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 62aa281470fdb7c0796d63a1cc918a8c1f02dde2)
Signed-off-by: Himanshu Madhani <hmadhani@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>