[kernel] bpf: Add CONFIG_BPF_EVENTS into Kconfig
Message-id: <20180612134439.10359-59-jolsa@redhat.com>
Patchwork-id: 221303
O-Subject: [PATCH RHEL7.6 BZ1311586 58/71] bpf: Add CONFIG_BPF_EVENTS into Kconfig
Bugzilla: 1311586
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit e1abf2cc8d5d80b41c4419368ec743ccadbb131e
Author: Ingo Molnar <mingo@kernel.org>
Date:   Thu Apr 2 15:51:39 2015 +0200

description
===========
bpf: Fix the build on BPF_SYSCALL=y && !CONFIG_TRACING kernels, make it more configurable

So bpf_tracing.o depends on CONFIG_BPF_SYSCALL - but that's not its only
dependency, it also depends on the tracing infrastructure and on kprobes,
without which it will fail to build with:

  In file included from kernel/trace/bpf_trace.c:14:0:
  kernel/trace/trace.h: In function trace_test_and_set_recursion:
  kernel/trace/trace.h:491:28: error: struct task_struct has no member named trace_recursion
    unsigned int val = current->trace_recursion;
  [...]

It took quite some time to trigger this build failure, because right now
BPF_SYSCALL is very obscure, depends on CONFIG_EXPERT. So also make BPF_SYSCALL
more configurable, not just under CONFIG_EXPERT.

If BPF_SYSCALL, tracing and kprobes are enabled then enable the bpf_tracing
gateway as well.

We might want to make this an interactive option later on, although
I'd not complicate it unnecessarily: enabling BPF_SYSCALL is enough of
an indicator that the user wants BPF support.

RHEL7
=====
Adding only Kconfig hunks.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>