[tools] lib/subcmd/pager.c: do not alias select() params
Message-id: <20180620110202.6887-2-yauheni.kaliuta@redhat.com>
Patchwork-id: 222577
O-Subject: [PATCH RHEL7 RFC 1/4] tools/lib/subcmd/pager.c: do not alias select() params
Bugzilla: 1593432
RH-Acked-by: Bruno Eduardo de Oliveira Meneguele <bmeneg@redhat.com>
RH-Acked-by: Josh Poimboeuf <jpoimboe@redhat.com>

From: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>

Use a separate fd set for select()-s exception fds param to fix the
following gcc warning:

  pager.c:36:12: error: passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
    select(1, &in, NULL, &in, NULL);
              ^~~        ~~~

Link: http://lkml.kernel.org/r/20180101105626.7168-1-sergey.senozhatsky@gmail.com
Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit ad343a98e74e85aa91d844310e797f96fee6983b)
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>