[iio] always select ANON_INODES
Message-id: <20180711174504.24920-146-tcamuso@redhat.com>
Patchwork-id: 224646
O-Subject: [RHEL7 BZ-1559170 v3 145/373] iio: always select ANON_INODES
Bugzilla: 1559170
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1559170
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17099185

Conflicts
    Leave GENERIC_HARDIRQS there for now.

Cherry-picked from the following upstream commit.

commit cc8b49fa26f57cc0096e702d3e7c3f7c3e263300
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Aug 5 15:56:00 2014 +0100

    iio: always select ANON_INODES

    Without ANON_INODES, we get this build error:

    drivers/built-in.o: In function `iio_event_getfd':
    :(.text+0x14bf18): undefined reference to `anon_inode_getfd'

    All other users explicitly select this symbol, so we should
    do the same thing here.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Jonathan Cameron <jic23@kernel.org>
    Cc: linux-iio@vger.kernel.org
    Signed-off-by: Jonathan Cameron <jic23@kernel.org>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>