[mm] lib: move strncpy_from_unsafe() into mm/maccess.c
Message-id: <20180612134439.10359-28-jolsa@redhat.com>
Patchwork-id: 221291
O-Subject: [PATCH RHEL7.6 BZ1311586 27/71] lib: move strncpy_from_unsafe() into mm/maccess.c
Bugzilla: 1311586
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit dbb7ee0e474cc8221de55583f516275693c5b552
Author: Alexei Starovoitov <ast@plumgrid.com>
Date:   Mon Aug 31 08:57:10 2015 -0700

description
===========
To fix build errors:
kernel/built-in.o: In function `bpf_trace_printk':
bpf_trace.c:(.text+0x11a254): undefined reference to `strncpy_from_unsafe'
kernel/built-in.o: In function `fetch_memory_string':
trace_kprobe.c:(.text+0x11acf8): undefined reference to `strncpy_from_unsafe'

move strncpy_from_unsafe() next to probe_kernel_read/write()
which use the same memory access style.

Fixes: 1a6877b9c0c2 ("lib: introduce strncpy_from_unsafe()")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>