[kernel] bpf/tracing: fix kernel/events/core.c compilation error
Message-id: <20180709105913.17980-41-jolsa@redhat.com>
Patchwork-id: 224091
O-Subject: [PATCH RHEL7.6 BZ1593026 40/50] bpf/tracing: fix kernel/events/core.c compilation error
Bugzilla: 1593026
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1593026
https://bugzilla.redhat.com/show_bug.cgi?id=1593026

upstream
========
commit f4e2298e63d24bb7f5cf0f56f72867973cb7e652
Author: Yonghong Song <yhs@fb.com>
Date:   Wed Dec 13 10:35:37 2017 -0800

description
===========
Commit f371b304f12e ("bpf/tracing: allow user space to
query prog array on the same tp") introduced a perf
ioctl command to query prog array attached to the
same perf tracepoint. The commit introduced a
compilation error under certain config conditions, e.g.,
  (1). CONFIG_BPF_SYSCALL is not defined, or
  (2). CONFIG_TRACING is defined but neither CONFIG_UPROBE_EVENTS
       nor CONFIG_KPROBE_EVENTS is defined.

Error message:
  kernel/events/core.o: In function `perf_ioctl':
  core.c:(.text+0x98c4): undefined reference to `bpf_event_query_prog_array'

This patch fixed this error by guarding the real definition under
CONFIG_BPF_EVENTS and provided static inline dummy function
if CONFIG_BPF_EVENTS was not defined.
It renamed the function from bpf_event_query_prog_array to
perf_event_query_prog_array and moved the definition from linux/bpf.h
to linux/trace_events.h so the definition is in proximity to
other prog_array related functions.

Fixes: f371b304f12e ("bpf/tracing: allow user space to query prog array on the same tp")

RHEL7
=====
Making changes in ftrace_event.h (RHEL7) instead of trace_events.h (upstream).

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>