[tools] tools include uapi asm-generic: Grab a copy of fcntl.h
Message-id: <20180419185703.28105-31-jolsa@redhat.com>
Patchwork-id: 209966
O-Subject: [PATCH RHEL7.6 BZ1540862 030/245] tools include uapi asm-generic: Grab a copy of fcntl.h
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 84d1d8a12df33a3e707866b9a1f9872058c3d1fb
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Jul 18 17:09:21 2017 -0300

description
===========
We'll need defines for beautifying fcntl arguments that are not
available in older distros, these:

  trace/beauty/fcntl.c: In function 'syscall_arg__scnprintf_fcntl_arg':
  trace/beauty/fcntl.c:93: error: 'F_OFD_SETLK' undeclared (first use in this function)
  trace/beauty/fcntl.c:93: error: (Each undeclared identifier is reported only once
  trace/beauty/fcntl.c:93: error: for each function it appears in.)
  trace/beauty/fcntl.c:93: error: 'F_OFD_SETLKW' undeclared (first use in this function)
  trace/beauty/fcntl.c:93: error: 'F_OFD_GETLK' undeclared (first use in this function)
  trace/beauty/fcntl.c:94: error: 'F_GETOWN_EX' undeclared (first use in this function)
  trace/beauty/fcntl.c:94: error: 'F_SETOWN_EX' undeclared (first use in this function)

RHEL7
=====
Using RHEL7 copy of the file.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>