[netdrv] mlx5: Build wq.o even if MLX5_CORE_EN is not selected
Message-id: <1511855648-15797-67-git-send-email-kheib@redhat.com>
Patchwork-id: 200282
O-Subject: [RHEL7.5 PATCH 066/192] net/mlx5: Build wq.o even if MLX5_CORE_EN is not selected
Bugzilla: 1456677 1456694
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456694
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1456677

commit 111a676367699dc8e3bc567ab17ab573ade54f0d
Author: Ilan Tayari <ilant@mellanox.com>
Date:   Mon Jul 3 10:01:19 2017 +0300

    net/mlx5: Build wq.o even if MLX5_CORE_EN is not selected

    Both the ethernet and FPGA portions of MLX5 now require the wq functions,
    and we get a link error when CONFIG_MLX5_CORE_EN is disabled:

    drivers/net/ethernet/mellanox/mlx5/core/fpga/conn.o: In function `mlx5_fpga_conn_create_cq':
    conn.c:(.text+0x10b3): undefined reference to `mlx5_cqwq_create'
    conn.c:(.text+0x10c6): undefined reference to `mlx5_cqwq_get_size'
    conn.c:(.text+0x12bc): undefined reference to `mlx5_cqwq_destroy'

    Build wq.o even if MLX5_CORE_EN is not selected.

    Fixes: 537a50574175 ("net/mlx5: FPGA, Add high-speed connection routines")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ilan Tayari <ilant@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>