[input] synaptics-rmi4 - fix F03 build error when serio is module
Message-id: <20180417141301.4870-57-benjamin.tissoires@redhat.com>
Patchwork-id: 209688
O-Subject: [PATCH RHEL7.6 056/141] Input: synaptics-rmi4 - fix F03 build error when serio is module
Bugzilla: 1554926
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Aristeu Rozanski <aris@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1554926
Upstream: since v4.10
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15808598
Test: by me on a t450s, X280 and the IT folks on the X1 Carbon 6 and T480

commit d7ddad0acc4add42567f7879b116a0b9eea31860
Author: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Date:   Tue Dec 27 11:32:55 2016 -0800

    Input: synaptics-rmi4 - fix F03 build error when serio is module

    Since F03 is a boolean, "depends" on symbols that can be modules
    do not work quite right. We can enable F03 if SERIO is built-in or
    if both RMI core and SERIO core are modules. If SERIO core is module,
    but RMI is built-in, we'll get:

    drivers/built-in.o: In function `rmi_f03_attention':
    rmi_f03.c:(.text+0xf8ef8): undefined reference to `serio_interrupt'
    rmi_f03.c:(.text+0xf8fbd): undefined reference to `serio_interrupt'
    drivers/built-in.o: In function `rmi_f03_remove':
    rmi_f03.c:(.text+0xf9082): undefined reference to `serio_unregister_port'
    drivers/built-in.o: In function `rmi_f03_probe':
    rmi_f03.c:(.text+0xf9260): undefined reference to `__serio_register_port'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reviewed-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>