[hwtracing] stm class: Select CONFIG_SRCU
Message-id: <20190311092113.21814-8-jolsa@redhat.com>
Patchwork-id: 245610
O-Subject: [PATCH RHEL7 BZ1514700 007/125] stm class: Select CONFIG_SRCU
Bugzilla: 1514700
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1514700
https://bugzilla.redhat.com/show_bug.cgi?id=1514700

upstream
========
commit 042d4460b5b4379a12f375045ff9065cf6758735
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Dec 22 17:25:17 2015 +0200

description
===========
The newly added STM code uses SRCU, but does not ensure that
this code is part of the kernel:

drivers/built-in.o: In function `stm_source_link_show':
include/linux/srcu.h:221: undefined reference to `__srcu_read_lock'
include/linux/srcu.h:238: undefined reference to `__srcu_read_unlock'
drivers/built-in.o: In function `stm_source_link_drop':
include/linux/srcu.h:221: undefined reference to `__srcu_read_lock'
include/linux/srcu.h:238: undefined reference to `__srcu_read_unlock'

This adds a Kconfig 'select' statement like all the other SRCU using
drivers have.

Fixes: 7bd1d4093c2f ("stm class: Introduce an abstraction for System Trace Module devices")
Signed-off-by: Jan Stancek <jstancek@redhat.com>