[kernel] cpumask: Add helper cpumask_available()
Message-id: <a97ee22a0b3345bde3582e0dfdf8270ce31179cb.1548943340.git.poros@redhat.com>
Patchwork-id: 239759
O-Subject: [RHEL7.7 net PATCH 1/3] cpumask: Add helper cpumask_available()
Bugzilla: 1671092
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1671092

Upstream commit(s):
commit f7e30f01a9e221067bb4b579e3cfc25cd2617467
Author: Matthias Kaehlcke <mka@chromium.org>
Date:   Wed Apr 12 11:20:29 2017 -0700

    cpumask: Add helper cpumask_available()

    With CONFIG_CPUMASK_OFFSTACK=y cpumask_var_t is a struct cpumask
    pointer, otherwise a struct cpumask array with a single element.

    Some code dealing with cpumasks needs to validate that a cpumask_var_t
    is not a NULL pointer when CONFIG_CPUMASK_OFFSTACK=y. This is typically
    done by performing the check always, regardless of the underlying type
    of cpumask_var_t. This works in both cases, however clang raises a
    warning like this when CONFIG_CPUMASK_OFFSTACK=n:

    kernel/irq/manage.c:839:28: error: address of array
    'desc->irq_common_data.affinity' will always evaluate to 'true'
    [-Werror,-Wpointer-bool-conversion]

    Add the inline helper cpumask_available() which only performs the
    pointer check if CONFIG_CPUMASK_OFFSTACK=y.

    Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
    Cc: Grant Grundler <grundler@chromium.org>
    Cc: Rusty Russell <rusty@rustcorp.com.au>
    Cc: Greg Hackmann <ghackmann@google.com>
    Cc: Michael Davidson <md@google.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Link: http://lkml.kernel.org/r/20170412182030.83657-1-mka@chromium.org
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>