[watchdog] fix checkpatch warnings and error
Message-id: <1541446078-3457-3-git-send-email-darcari@redhat.com>
Patchwork-id: 232511
O-Subject: [RHEL7.7 BZ 1645537 02/15] watchdog: fix checkpatch warnings and error
Bugzilla: 1645537
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1645537
Conflicts: limited to iTCO_wdt.c

commit 5f5e19093b2fa592720810154f15ffe51aa9277f
Author: Jingoo Han <jg1.han@samsung.com>
Date:   Thu Feb 27 14:41:42 2014 +0900

    watchdog: fix checkpatch warnings and error

    Fix the following checkpatch warnings and error:
      WARNING: quoted string split across lines
      WARNING: braces {} are not necessary for single statement blocks
      WARNING: __initdata should be placed after ibmasr_id_table[]
      WARNING: please, no space before tabs
      ERROR: do not initialise statics to 0 or NULL

    Signed-off-by: Jingoo Han <jg1.han@samsung.com>
    Reviewed-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Wim Van Sebroeck <wim@iguana.be>

Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>