[fs] dax: fix FS_DAX=n BLOCK=y compilation
Message-id: <20180314211019.13435-6-jmoyer@redhat.com>
Patchwork-id: 206775
O-Subject: [RHEL7.6 PATCH 5/6] dax: fix FS_DAX=n BLOCK=y compilation
Bugzilla: 1526252
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Brian Foster <bfoster@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1526252
Brew: 15552120

commit 26f2f4de0bd93cbe891e11307d9e4906253bfda8
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Sun Sep 3 10:17:53 2017 -0700

    dax: fix FS_DAX=n BLOCK=y compilation

    The 0day kbuild robot reports:

    >> drivers//dax/super.c:64:20: error: redefinition of 'fs_dax_get_by_bdev'
        struct dax_device *fs_dax_get_by_bdev(struct block_device *bdev)
                           ^~~~~~~~~~~~~~~~~~
       In file included from drivers//dax/super.c:22:0:
       include/linux/dax.h:76:34: note: previous definition of 'fs_dax_get_by_bdev' was here
        static inline struct dax_device *fs_dax_get_by_bdev(struct block_device *bdev)
                                         ^~~~~~~~~~~~~~~~~~

    Protect the definition of fs_dax_get_by_bdev() in drivers/dax/super.c
    with an ifdef.

    Fixes: 78f354735081 ("dax: introduce a fs_dax_get_by_bdev() helper")
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Darrick J. Wong <darrick.wong@oracle.com>
    Reviewed-by: Jan Kara <jack@suse.cz>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>