[redhat] redhat: spec: select python version explicitly on rhel8+
Message-id: <0adf83d7dc8f5a35bb152b92645fbe87917cbfe1.1587484645.git.jstancek@redhat.com>
Patchwork-id: 304468
Patchwork-instance: patchwork
O-Subject: [RHEL-7.9 PATCH] redhat: spec: select python version explicitly on rhel8+
Bugzilla:
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>

Bugzilla: INTERNAL
Upstream status: RHEL only
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28084878 (F31)
      https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28092284 (rhel8)
      https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28092270 (rhel7)
Tested: compile only in brew with SRPMs create on RHEL7/8 and F31

rh-srpm fails on RHEL8+ or recent Fedoras with:
  error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
  error: Macro %debuginfo_args failed to expand
  error: line 542: %{expand:%%global debuginfo_args %{?debuginfo_args} -p '.*%%{python_sitearch}/perf.so(\.debug)?|XXX' -o python-perf-debuginfo.list}

There's no unversioned Python in RHEL8+. Select one explicitly
so that it's possible at least 'make rh-srpm' and build SRPM in brew.

Fedora may also need symlink for platform-python, which show-kabi
depends on:
  # ln -s /usr/bin/python /usr/libexec/platform-python

Reported-by: Gustavo Duarte <gduarte@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>