[tools] tools include linux: Guard against redefinition of some macros
Message-id: <20180419185703.28105-222-jolsa@redhat.com>
Patchwork-id: 210115
O-Subject: [PATCH RHEL7.6 BZ1540862 221/245] tools include linux: Guard against redefinition of some macros
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 259d40775ee11dbeba022514815df08c57994ef3
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Sep 5 10:52:02 2017 -0300

description
===========
When cross building to android r15c (and older versions) on Fedora 26
we notice these:

/opt/android-ndk-r15c/platforms/android-24/arch-arm/usr/include/sys/cdefs.h:332:0: note: this is the location of the previous definition

For __aligned, __packed and __noreturn, so guard those with ifdefs to
avoid drowning useful warnings in these.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>