[netdrv] mlxsw: add psample dependency for spectrum
Message-id: <20171013205835.26049-9-ivecera@redhat.com>
Patchwork-id: 193364
O-Subject: [RHEL7.5 PATCH 008/245] mlxsw: add psample dependency for spectrum
Bugzilla: 1486860
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ#1486860

Upstream commit(s):
commit 8d1fb01df8f64af14c833805dcbd05bf4582e028
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 6 17:26:30 2017 +0100

    mlxsw: add psample dependency for spectrum

    When PSAMPLE is a loadable module, spectrum must not be built-in:

    drivers/net/built-in.o: In function `mlxsw_sp_rx_listener_sample_func':
    spectrum.c:(.text+0xe357e): undefined reference to `psample_sample_packet'

    This adds a Kconfig dependency to enforce usable configurations.

    Fixes: 98d0f7b9acda ("mlxsw: spectrum: Add packet sample offloading support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Yotam Gigi <yotamg@mellanox.com>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>