[tools] perf tools: Fix tracing_path_mount proper path
Message-id: <20190218130507.16170-188-jolsa@redhat.com>
Patchwork-id: 242211
O-Subject: [PATCH RHEL7 BZ1672893 187/187] perf tools: Fix tracing_path_mount proper path
Bugzilla: 1672893
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1672893
https://bugzilla.redhat.com/show_bug.cgi?id=1672893

upstream
========
commit c458a6206d2a8600934617ccf88ba7d3a030faba
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Tue Oct 16 13:48:18 2018 +0200

description
===========
If there's no tracefs (RHEL7) support the tracing_path_mount
returns debugfs path which results in following fail:

  # perf probe sys_write
  kprobe_events file does not exist - please rebuild kernel with CONFIG_KPROBE_EVENTS.
  Error: Failed to add events.

In tracing_path_debugfs_mount function we need to return the
'tracing' path instead of just the mount to make it work:

  # perf probe sys_write
  Added new event:
    probe:sys_write      (on sys_write)

  You can now use it in all perf tools, such as:

          perf record -e probe:sys_write -aR sleep 1

Adding the 'return tracing_path;' also to tracing_path_tracefs_mount
function just for consistency with tracing_path_debugfs_mount.

Upstream keeps working, because it has the tracefs support.

Signed-off-by: Jan Stancek <jstancek@redhat.com>