[tools] perf tools: Fix maps__find_symbol_by_name()
Message-id: <20190226093100.17420-99-jolsa@redhat.com>
Patchwork-id: 243242
O-Subject: [PATCH RHEL7 BZ1680072 098/111] perf tools: Fix maps__find_symbol_by_name()
Bugzilla: 1680072
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1680072
https://bugzilla.redhat.com/show_bug.cgi?id=1680072

upstream
========
commit 03db8b583d1c3c84963e08e2abf6c79081da5c31
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Sep 7 11:51:16 2018 +0300

description
===========
Commit 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry
trampolines") revealed a problem with maps__find_symbol_by_name() that
resulted in probes not being found e.g.

	$ sudo perf probe xsk_mmap
	xsk_mmap is out of .text, skip it.
	Probe point 'xsk_mmap' not found.
	   Error: Failed to add events.

maps__find_symbol_by_name() can optionally return the map of the found
symbol. It can get the map wrong because, in fact, the symbol is found
on the map's dso, not allowing for the possibility that the dso has more
than one map. Fix by always checking the map contains the symbol.

Fixes: 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry trampolines")
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>