[netdrv] mlx4_en: Fix build break when CONFIG_INET is off
Message-id: <1549457075-6314-625-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240591
O-Subject: [RHEL7.7 BZ 1642498 624/729] net/mlx4_en: Fix build break when CONFIG_INET is off
Bugzilla: 1641912 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Bugzilla: http://bugzilla.redhat.com/1641912
Upstream: v4.20-rc6

commit 1b603f9e4313348608f256b564ed6e3d9e67f377
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Sun Dec 2 14:34:37 2018 +0200

    net/mlx4_en: Fix build break when CONFIG_INET is off

    MLX4_EN depends on NETDEVICES, ETHERNET and INET Kconfigs.
    Make sure they are listed in MLX4_EN Kconfig dependencies.

    This fixes the following build break:

    drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: struct iphdr declared inside parameter list [enabled by default]
    struct iphdr *iph)
    ^
    drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
    drivers/net/ethernet/mellanox/mlx4/en_rx.c: In function get_fixed_ipv4_csum:
    drivers/net/ethernet/mellanox/mlx4/en_rx.c:586:20: error: dereferencing pointer to incomplete type
    _u8 ipproto = iph->protocol;

    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: Tariq Toukan <tariqt@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>