[i2c] core: Export bus recovery functions
Message-id: <1512018377-6838-26-git-send-email-gtiwari@redhat.com>
Patchwork-id: 200595
O-Subject: [RHEL-7.5 V4 BZ 1456705 25/75] i2c: core: Export bus recovery functions
Bugzilla: 1456705
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1456705

commit c1c21f4e60ed4523292f1a89ff45a208bddd3849
Author: Mark Brown <broonie@kernel.org>
Date:   Wed Apr 15 19:18:39 2015 +0100

    i2c: core: Export bus recovery functions

    Current -next fails to link an ARM allmodconfig because drivers that use
    the core recovery functions can be built as modules but those functions
    are not exported:

    ERROR: "i2c_generic_gpio_recovery" [drivers/i2c/busses/i2c-davinci.ko] undefined!
    ERROR: "i2c_generic_scl_recovery" [drivers/i2c/busses/i2c-davinci.ko] undefined!
    ERROR: "i2c_recover_bus" [drivers/i2c/busses/i2c-davinci.ko] undefined!

    Add exports to fix this.

    Fixes: 5f9296ba21b3c (i2c: Add bus recovery infrastructure)
    Signed-off-by: Mark Brown <broonie@kernel.org>
    Signed-off-by: Wolfram Sang <wsa@the-dreams.de>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>