[usb] get rid of some ReST doc build errors
Message-id: <1526649550-17190-163-git-send-email-torez@redhat.com>
Patchwork-id: 215939
O-Subject: [RHEL7.6 PATCH BZ1540721 162/681] usb: get rid of some ReST doc build errors
Bugzilla: 1540721
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1540721
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16352184
Testing: on local desktop and Dell Precision 5510 laptop

Conflicts: Removed changes to files which have been filtered out and not
included in this series. In particular, changes to the following files...
    include/linux/usb/composite.h

commit e0c34e900611a58c93adf463d096c5843eb1967a
Author: Mauro Carvalho Chehab <mchehab@s-opensource.com>
Date:   Wed Apr 5 10:23:12 2017 -0300

    usb: get rid of some ReST doc build errors

    We need an space before a numbered list to avoid those warnings:

    ./drivers/usb/core/message.c:478: ERROR: Unexpected indentation.
    ./drivers/usb/core/message.c:479: WARNING: Block quote ends without a blank line; unexpected unindent.
    ./include/linux/usb/composite.h:455: ERROR: Unexpected indentation.
    ./include/linux/usb/composite.h:456: WARNING: Block quote ends without a blank line; unexpected unindent.

    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>
    Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Jonathan Corbet <corbet@lwn.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>