[gpu] drm/nouveau: nouveau: use larger buffer in nvif_vmm_map
Message-id: <20180531214039.20828-26-rclark@redhat.com>
Patchwork-id: 219222
O-Subject: [RHEL7 drm 025/190] drm/nouveau: nouveau: use larger buffer in nvif_vmm_map
Bugzilla: 1519691 1515623 1457161
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>
RH-Acked-by: Lyude Paul <lyude@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1457161
Upstream: since nouveau-for-4.18

commit 9dfbd7319909a948146f5c3438f7bd86c2c53cb6

Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Fri Feb 2 16:27:31 2018 +0100
Commit:     Ben Skeggs <bskeggs@redhat.com>
CommitDate: Fri May 18 15:01:19 2018 +1000

    drm/nouveau: nouveau: use larger buffer in nvif_vmm_map

    gcc points out a buffer that is clearly too small to be used
    in a meaningful way, as the 'sizeof(*args) + argc > sizeof(stack)'
    will always fail:

    In function 'memcpy',
        inlined from 'nvif_vmm_map' at drivers/gpu/drm/nouveau/nvif/vmm.c:55:2:
    include/linux/string.h:353:9: error: '__builtin_memcpy' offset 40 is out of the bounds [0, 16] of object 'stack' with type 'u8[16]' {aka 'unsigned char[16]'} [-Werror=array-bounds]
      return __builtin_memcpy(p, q, size);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/nouveau/nvif/vmm.c: In function 'nvif_vmm_map':
    drivers/gpu/drm/nouveau/nvif/vmm.c:40:5: note: 'stack' declared here

    This makes the buffer large enough so it should serve the purpose
    that the author presumably had in mind. Alternatively we could
    just get rid of it completely and simplify the code at the cost
    of always doing the kmalloc (as we do in the current version).

    Fixes: 920d2b5ef215 ("drm/nouveau/mmu: define user interfaces to mmu vmm opertaions")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ben Skeggs <bskeggs@redhat.com>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>