[dax] device-dax: Tell kbuild DEV_DAX_PMEM depends on DEV_DAX
Message-id: <20180629205942.12191-37-jmoyer@redhat.com>
Patchwork-id: 223242
O-Subject: [RHEL7.6 PATCH, v2 36/55] [dax] device-dax: Tell kbuild DEV_DAX_PMEM depends on DEV_DAX
Bugzilla: 1515085
RH-Acked-by: Ming Lei <ming.lei@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>

From: Mike Galbraith <efault@gmx.de>

BZ: 1515085 1585122
Brew: 16606803

commit 74d71a01abef37f71d914f2105a4cb8712a2beb8
Author: Mike Galbraith <efault@gmx.de>
Date:   Sat May 6 06:14:43 2017 +0200

    device-dax: Tell kbuild DEV_DAX_PMEM depends on DEV_DAX

    ERROR: "devm_create_dev_dax" [drivers/dax/dax_pmem.ko] undefined!
    ERROR: "alloc_dax_region" [drivers/dax/dax_pmem.ko] undefined!
    ERROR: "dax_region_put" [drivers/dax/dax_pmem.ko] undefined!

    Signed-off-by: Mike Galbraith <efault@gmx.de>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>