[tools] perf tools: Free 'printk' string in parse_ftrace_printk()
Message-id: <20190311094227.31342-84-jolsa@redhat.com>
Patchwork-id: 245813
O-Subject: [PATCH RHEL7 BZ1680074 083/170] perf tools: Free 'printk' string in parse_ftrace_printk()
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit 9c8a182e5a73e01afd11742a2ab887bf338fdafd
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:12 2018 -0400

description
===========
parse_ftrace_printk() tokenizes and parses a line, calling strdup() each
iteration.  Add code to free this temporary format string duplicate.

Fixes the following coverity complaints:

  Error: RESOURCE_LEAK (CWE-772):
  tools/perf/util/trace-event-parse.c:158: overwrite_var: Overwriting
  "printk" in "printk = strdup(fmt + 1)" leaks the storage that "printk"
  points to.

  tools/perf/util/trace-event-parse.c:162: leaked_storage: Variable
  "printk" going out of scope leaks the storage it points to.

RHEL7
=====
Small context conflict with not backported traceevent API rename.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>