[watchdog] hpwdt: fix unused variable warning
Message-id: <1526068460-17717-4-git-send-email-jszczype@redhat.com>
Patchwork-id: 214701
O-Subject: [RHEL7.6 PATCH V3 3/7] watchdog: hpwdt: fix unused variable warning
Bugzilla: 1555073
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1555073

The new hpwdt_my_nmi() function is used conditionally, which produces
a harmless warning in some configurations:

drivers/watchdog/hpwdt.c:478:12: error: 'hpwdt_my_nmi' defined but not used [-Werror=unused-function]

This moves it inside of the #ifdef that protects its caller, to silence
the warning.

Fixes: 621174a92851 ("watchdog: hpwdt: Check source of NMI")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Jerry Hoemann <jerry.hoemann@hpe.com>
Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
(cherry picked from commit aeebc6ba88ba3758ad95467ff6191fabf2074c13)
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>