[tools] tools include uapi: Grab a copy of asm-generic/ioctls.h
Message-id: <20180419185703.28105-138-jolsa@redhat.com>
Patchwork-id: 210187
O-Subject: [PATCH RHEL7.6 BZ1540862 137/245] tools include uapi: Grab a copy of asm-generic/ioctls.h
Bugzilla: 1540862
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jiri Olsa <jolsa@kernel.org>

Bugzilla: 1540862
https://bugzilla.redhat.com/show_bug.cgi?id=1540862

upstream
========
commit 6375f0abeea886ec718d8b0aaf99818c7505de14
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Jul 31 22:52:28 2017 -0300

description
===========
So that we can build on older systems where otherwise we would end up
with:

    CC       /tmp/build/perf/trace/beauty/ioctl.o
  trace/beauty/ioctl.c: In function 'ioctl__scnprintf_tty_cmd':
  trace/beauty/ioctl.c:25:17: error: 'TIOCGEXCL' undeclared (first use in this function)
  trace/beauty/ioctl.c:25:17: note: each undeclared identifier is reported only once for each function it appears in
  trace/beauty/ioctl.c:25:2: error: array index in initializer not of integer type
  trace/beauty/ioctl.c:25:2: error: (near initialization for 'ioctl_tty_cmd')

This way we can build a tool on an older system and it will still be
capable of processing perf.data files generated on newer systems.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>