[net] pktgen: use dynamic allocation for debug print buffer
Message-id: <20190222213038.10747-78-ivecera@redhat.com>
Patchwork-id: 243042
O-Subject: [RHEL7.7 net PATCH 77/81] pktgen: use dynamic allocation for debug print buffer
Bugzilla: 1680139
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1680139

Upstream commit(s):
commit a870a02cc963de35452bbed932560ed69725c4f2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 13 21:58:39 2018 +0100

    pktgen: use dynamic allocation for debug print buffer

    After the removal of the VLA, we get a harmless warning about a large
    stack frame:

    net/core/pktgen.c: In function 'pktgen_if_write':
    net/core/pktgen.c:1710:1: error: the frame size of 1076 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    The function was previously shown to be safe despite hitting
    the 1024 bye warning level. To get rid of the annoyging warning,
    while keeping it readable, this changes it to use strndup_user().

    Obviously this is not a fast path, so the kmalloc() overhead
    can be disregarded.

    Fixes: 35951393bbff ("pktgen: Remove VLA usage")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>