[nvdimm] libnvdimm, dax: fix 1GB-aligned namespaces vs physical misalignment
Message-id: <20180629205942.12191-20-jmoyer@redhat.com>
Patchwork-id: 223241
O-Subject: [RHEL7.6 PATCH, v2 19/55] [nvdimm] libnvdimm, dax: fix 1GB-aligned namespaces vs physical misalignment
Bugzilla: 1526926 1515085
RH-Acked-by: Ming Lei <ming.lei@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>

From: Dan Williams <dan.j.williams@intel.com>

BZ: 1515085 1526926
Brew: 16606803

Conflicts: Minor contextual difference.  We have a different
region_intersects api from upstream.

commit 41fce90f26333c4fa82e8e43b9ace86c4e8a0120
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Mon Dec 4 14:07:43 2017 -0800

    libnvdimm, dax: fix 1GB-aligned namespaces vs physical misalignment

    The following namespace configuration attempt:

        # ndctl create-namespace -e namespace0.0 -m devdax -a 1G -f
        libndctl: ndctl_dax_enable: dax0.1: failed to enable
          Error: namespace0.0: failed to enable

        failed to reconfigure namespace: No such device or address

    ...fails when the backing memory range is not physically aligned to 1G:

        # cat /proc/iomem | grep Persistent
        210000000-30fffffff : Persistent Memory (legacy)

    In the above example the 4G persistent memory range starts and ends on a
    256MB boundary.

    We handle this case correctly when needing to handle cases that violate
    section alignment (128MB) collisions against "System RAM", and we simply
    need to extend that padding/truncation for the 1GB alignment use case.

    Cc: <stable@vger.kernel.org>
    Fixes: 315c562536c4 ("libnvdimm, pfn: add 'align' attribute...")
    Reported-and-tested-by: Jane Chu <jane.chu@oracle.com>
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>