[net] ipv4: Return error for RTA_VIA attribute
Message-id: <3c5d112f6009c8a25b3b197ec8a9af024aba49f9.1568221629.git.sbrivio@redhat.com>
Patchwork-id: 271233
O-Subject: [RHEL7.8 net] ipv4: Return error for RTA_VIA attribute
Bugzilla: 1751301
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Guillaume Nault <gnault@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1751301
Tested: with steps from commit message

commit b6e9e5df4ecf100f6a10ab2ade8e46d47a4b9779
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Feb 26 09:00:02 2019 -0800

    ipv4: Return error for RTA_VIA attribute

    IPv4 currently does not support nexthops outside of the AF_INET family.
    Specifically, it does not handle RTA_VIA attribute. If it is passed
    in a route add request, the actual route added only uses the device
    which is clearly not what the user intended:

      $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
      $ ip ro ls
      ...
      172.16.1.0/24 dev eth0

    Catch this and fail the route add:
      $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
      Error: IPv4 does not support RTA_VIA attribute.

    Fixes: 03c0566542f4c ("mpls: Netlink commands to add, remove, and dump routes")
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>