[tools] bpftool: Fix prog dump by tag
Message-id: <20190704104222.26554-1-jolsa@redhat.com>
Patchwork-id: 266372
O-Subject: [PATCH RHEL7 BZ1697240] bpftool: Fix prog dump by tag
Bugzilla: 1697240
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1697240
https://bugzilla.redhat.com/show_bug.cgi?id=1697240
brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22490250

upstream
========
commit 752bcf80f5549c9901b2e8bc77b2138de55b1026
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Fri Jan 18 13:58:17 2019 +0100

description
===========
Lance reported an issue with bpftool not being able to
dump program if there are more programs loaded and you
want to dump any but the first program, like:

  # bpftool prog
  28: kprobe  name trace_req_start  tag 1dfc28ba8b3dd597  gpl
  	loaded_at 2019-01-18T17:02:40+1100  uid 0
  	xlated 112B  jited 109B  memlock 4096B  map_ids 13
  29: kprobe  name trace_req_compl  tag 5b6a5ecc6030a683  gpl
  	loaded_at 2019-01-18T17:02:40+1100  uid 0
  	xlated 928B  jited 575B  memlock 4096B  map_ids 13,14
  #  bpftool prog dum jited tag 1dfc28ba8b3dd597
   0:	push   %rbp
   1:	mov    %rsp,%rbp
  ...

  #  bpftool prog dum jited tag 5b6a5ecc6030a683
  Error: can't get prog info (29): Bad address

The problem is in the prog_fd_by_tag function not cleaning
the struct bpf_prog_info before another request, so the
previous program length is still in there and kernel assumes
it needs to dump the program, which fails because there's no
user pointer set.

Moving the struct bpf_prog_info declaration into the loop,
so it gets cleaned before each query.

Fixes: 71bb428fe2c1 ("tools: bpf: add bpftool")
Signed-off-by: Jan Stancek <jstancek@redhat.com>