[acpi] nfit: Fix COMPLETION_INITIALIZER_ONSTACK() abuse
Message-id: <20171121145952.29691-131-jmoyer@redhat.com>
Patchwork-id: 199793
O-Subject: [RHEL7.5 PATCH 130/138] acpi/nfit: Fix COMPLETION_INITIALIZER_ONSTACK() abuse
Bugzilla: 1455958
RH-Acked-by: Al Stone <ahs3@redhat.com>
RH-Acked-by: Ming Lei <ming.lei@redhat.com>

From: Boqun Feng <boqun.feng@gmail.com>

BZ: 1455958
Brew: 14590444

commit 1c322ac06d9af7ea259098ae5dc977855207d335
Author: Boqun Feng <boqun.feng@gmail.com>
Date:   Thu Aug 24 22:22:36 2017 +0800

    acpi/nfit: Fix COMPLETION_INITIALIZER_ONSTACK() abuse

    COMPLETION_INITIALIZER_ONSTACK() is supposed to be used as an initializer,
    in other words, it should only be used in assignment expressions or
    compound literals. So the usage in drivers/acpi/nfit/core.c:

            COMPLETION_INITIALIZER_ONSTACK(flush.cmp);

    ... is inappropriate.

    Besides, this usage could also break the build for another fix that
    reduces stack sizes caused by COMPLETION_INITIALIZER_ONSTACK(), because
    that fix changes COMPLETION_INITIALIZER_ONSTACK() from rvalue to lvalue,
    and usage as above will report the following error:

            drivers/acpi/nfit/core.c: In function 'acpi_nfit_flush_probe':
            include/linux/completion.h:77:3: error: value computed is not used [-Werror=unused-value]
              (*({ init_completion(&work); &work; }))

    This patch fixes this by replacing COMPLETION_INITIALIZER_ONSTACK()
    with init_completion() in acpi_nfit_flush_probe(), which does the
    same initialization without any other problems.

    Signed-off-by: Boqun Feng <boqun.feng@gmail.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Dan Williams <dan.j.williams@intel.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Byungchul Park <byungchul.park@lge.com>
    Cc: Len Brown <lenb@kernel.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Nicholas Piggin <npiggin@gmail.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rafael J. Wysocki <rjw@rjwysocki.net>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: walken@google.com
    Cc: willy@infradead.org
    Link: http://lkml.kernel.org/r/20170824142239.15178-1-boqun.feng@gmail.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>