[sound] alsa: usb-audio: Fix multiple definitions in AU0828_DEVICE() macro
Message-id: <15517824857704096-134-patchset-jkysela@redhat.com>
Patchwork-id: 244201
O-Subject: [RHEL 7.7 PATCH 133/467] ALSA: usb-audio: Fix multiple definitions in AU0828_DEVICE() macro
Bugzilla: 1657855
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

AU0828_DEVICE() macro in quirks-table.h uses USB_DEVICE_VENDOR_SPEC()
for expanding idVendor and idProduct fields.  However, the latter
macro adds also match_flags and bInterfaceClass, which are different
from the values AU0828_DEVICE() macro sets after that.

For fixing them, just expand idVendor and idProduct fields manually in
AU0828_DEVICE().

This fixes sparse warnings like:
  sound/usb/quirks-table.h:2892:1: warning: Initializer entry defined twice

Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit bd1cd0eb2ce9141100628d476ead4de485501b29)
Bugzilla: 1657855
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>