[netdrv] rdma/bnxt_re: add DCB dependency
Message-id: <54adc556d5a9231743bb67bff536be1be7e66996.1510964611.git.jtoppins@redhat.com>
Patchwork-id: 199207
O-Subject: [RHEL7.5 104/105] RDMA/bnxt_re: add DCB dependency
Bugzilla: 1459659
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

When CONFIG_DCB is disabled, we get a link error:

drivers/infiniband/built-in.o: In function `bnxt_re_setup_qos':
trace.c:(.text+0x155774): undefined reference to `dcb_ieee_getapp_mask'
trace.c:(.text+0x155774): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `dcb_ieee_getapp_mask'
trace.c:(.text+0x155794): undefined reference to `dcb_ieee_getapp_mask'
trace.c:(.text+0x155794): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `dcb_ieee_getapp_mask'

Like the other drivers that use this function, a Kconfig dependency is
the correct fix.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit e57f774db1fef3d983fd77db0f48f3f39875c65f)
Bugzilla: 1459659
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14573628
Tested: basic testing further testing being done by Broadcom and myself
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>