[kernel] /proc/module: fix building without kallsyms
Message-id: <20180612134439.10359-5-jolsa@redhat.com>
Patchwork-id: 221273
O-Subject: [PATCH RHEL7.6 BZ1311586 04/71] /proc/module: fix building without kallsyms
Bugzilla: 1311586
RH-Acked-by: Eugene Syromiatnikov <esyr@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: 1311586
https://bugzilla.redhat.com/show_bug.cgi?id=1311586

upstream
========
commit e4a8ca3baa5557fa54557d42b5910ed0d3316922
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 13 17:51:00 2017 +0100

description
===========
As reported by kernelci and other build bots, we now get a link
failure without CONFIG_KALLSYMS:

  module.c:(.text+0xf2c): undefined reference to `kallsyms_show_value'

This adds a dummy helper with the same name that can be used
for compilation. It's not entirely clear to me what this
should return for !CONFIG_KALLSYMS, I picked an unconditional
'false', which leads to the module address being unavailable
to user space.

RHEL7
=====
Small conflict with different context.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>