[kernel] rcu: Export init_rcu_head() and destroy_rcu_head() to GPL modules
Message-id: <20190305155643.22586-29-rclark@redhat.com>
Patchwork-id: 244565
O-Subject: [RHEL7 drm 28/34] rcu: Export init_rcu_head() and destroy_rcu_head() to GPL modules
Bugzilla: 1655767
RH-Acked-by: Jerome Glisse <jglisse@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Upstream: since v4.16
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20431428
RHBZ: 1655767

commit 156baec39732f025dc778e00da95fc10d6e45885

Author:     Paul E. McKenney <paulmck@linux.vnet.ibm.com>
AuthorDate: Thu Dec 7 09:40:38 2017 -0800
Commit:     Martin K. Petersen <martin.petersen@oracle.com>
CommitDate: Thu Dec 7 19:51:49 2017 -0500

    rcu: Export init_rcu_head() and destroy_rcu_head() to GPL modules

    Use of init_rcu_head() and destroy_rcu_head() from modules results in
    the following build-time error with CONFIG_DEBUG_OBJECTS_RCU_HEAD=y:

            ERROR: "init_rcu_head" [drivers/scsi/scsi_mod.ko] undefined!
            ERROR: "destroy_rcu_head" [drivers/scsi/scsi_mod.ko] undefined!

    This commit therefore adds EXPORT_SYMBOL_GPL() for each to allow them to
    be used by GPL-licensed kernel modules.

    Reported-by: Bart Van Assche <Bart.VanAssche@wdc.com>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Rob Clark <rclark@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>