[tools] perf tools: Avoid double free in read_event_file()
Message-id: <20190311094227.31342-85-jolsa@redhat.com>
Patchwork-id: 245816
O-Subject: [PATCH RHEL7 BZ1680074 084/170] perf tools: Avoid double free in read_event_file()
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit 470c8f7c88de013d266e1b61044efe8937728b7f
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:13 2018 -0400

description
===========
The temporary 'buf' buffer allocated in read_event_file() may be freed
twice.  Move the free() call to the common function exit point.

Fixes the following coverity complaints:

  Error: USE_AFTER_FREE (CWE-825):
  tools/perf/util/trace-event-read.c:309: double_free: Calling "free"
  frees pointer "buf" which has already been freed.

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>