[thunderbolt] efi: Fix Kconfig dependencies
Message-id: <1512650446-15556-41-git-send-email-jeremymc@redhat.com>
Patchwork-id: 201666
O-Subject: [PATCH RHEL7.5 v3 040/113] thunderbolt, efi: Fix Kconfig dependencies
Bugzilla: 1172010
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jeremy McNicoll <jeremymc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1172010

commit 79f9cd35b05e3e91ccf9b4038a8b74b9362b5da7
Author: Lukas Wunner <lukas@wunner.de>
Date:   Mon Nov 14 16:10:33 2016 +0100

    thunderbolt, efi: Fix Kconfig dependencies

    Fix this EFI build failure on certain (rand)configs:

      drivers/firmware/efi/apple-properties.c:149:9: error: implicit declaration of function ???efi_get_device_by_path??? [-Werror=implicit-function-declaration]

    which is due to:

      warning: (THUNDERBOLT) selects APPLE_PROPERTIES which has unmet direct dependencies (EFI && EFI_STUB && X86)

    Signed-off-by: Lukas Wunner <lukas@wunner.de>
    Cc: Andreas Noever <andreas.noever@gmail.com>
    Cc: Ard Biesheuvel <ard.biesheuvel@linaro.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Matt Fleming <matt@codeblueprint.co.uk>
    Cc: Pedro Vilaa <reverser@put.as>
    Cc: Peter Jones <pjones@redhat.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Pierre Moreau <pierre.morrow@free.fr> [MacBookPro11,3]
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: linux-efi@vger.kernel.org
    Link: http://lkml.kernel.org/r/20161114151033.GA10141@wunner.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>