[infiniband] mlx5: fix build errors when INFINIBAND_USER_ACCESS=m
Message-id: <1549457075-6314-143-git-send-email-ahleihel@redhat.com>
Patchwork-id: 240099
O-Subject: [RHEL7.7 BZ 1642498 142/729] infiniband: mlx5: fix build errors when INFINIBAND_USER_ACCESS=m
Bugzilla: 1642498
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1642498
Upstream: v4.17

commit b3fe6c62bc66868c45b5bb16050e6bcb333af337
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Mon Apr 16 18:51:50 2018 -0700

    infiniband: mlx5: fix build errors when INFINIBAND_USER_ACCESS=m

    Fix build errors when INFINIBAND_USER_ACCESS=m and MLX5_INFINIBAND=y.
    The build error occurs when the mlx5 driver code attempts to use
    USER_ACCESS interfaces, which are built as a loadable module.

    Fixes these build errors:

    drivers/infiniband/hw/mlx5/main.o: In function `populate_specs_root':
    ../drivers/infiniband/hw/mlx5/main.c:4982: undefined reference to `uverbs_default_get_objects'
    ../drivers/infiniband/hw/mlx5/main.c:4994: undefined reference to `uverbs_alloc_spec_tree'
    drivers/infiniband/hw/mlx5/main.o: In function `depopulate_specs_root':
    ../drivers/infiniband/hw/mlx5/main.c:5001: undefined reference to `uverbs_free_spec_tree'

    Build-tested with multiple config combinations.

    Fixes: 8c84660bb437 ("IB/mlx5: Initialize the parsing tree root without the help of uverbs")
    Cc: stable@vger.kernel.org # reported against 4.16
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Don Dutile <ddutile@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>