[tools] perf tools: Cleanup trace-event-info 'tdata' leak
Message-id: <20190311094227.31342-83-jolsa@redhat.com>
Patchwork-id: 245814
O-Subject: [PATCH RHEL7 BZ1680074 082/170] perf tools: Cleanup trace-event-info 'tdata' leak
Bugzilla: 1680074
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1680074
https://bugzilla.redhat.com/show_bug.cgi?id=1680074

upstream
========
commit faedbf3fd19f2511a39397f76359e4cc6ee93072
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:11 2018 -0400

description
===========
Free tracing_data structure in tracing_data_get() error paths.

Fixes the following coverity complaint:

  Error: RESOURCE_LEAK (CWE-772):
  leaked_storage: Variable "tdata" going out of scope leaks the storage

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>