[netdrv] liquidio: fix timespec64_to_ns typo
Message-id: <20171113214216.GA16370@felix-thinkpad.cavium.com>
Patchwork-id: 197863
O-Subject: [PATCH RHEL7.5 06/18] liquidio: fix timespec64_to_ns typo
Bugzilla: 1510590
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

BZ 1510590
Upstream Status: net-next.git

commit e7ad97938eaccb5a9ff4534167b1abafb507935c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Oct 12 11:48:31 2017 +0200

    liquidio: fix timespec64_to_ns typo

    While experimenting with changes to the timekeeping code, I
    ran into a build error in the liquidio driver:

    drivers/net/ethernet/cavium/liquidio/lio_main.c: In function 'liquidio_ptp_settime':
    drivers/net/ethernet/cavium/liquidio/lio_main.c:1850:22: error: passing argument 1 of 'timespec_to_ns' from incompatible pointer type [-Werror=incompatible-pointer-types]

    The driver had a type mismatch since it was first merged, but
    this never caused problems because it is only built on 64-bit
    architectures that define timespec and timespec64 to the same
    type.

    If we ever want to compile-test the driver on 32-bit or change
    the way that 64-bit timespec64 is defined, we need to fix it,
    so let's just do it now.

    Fixes: f21fb3ed364b ("Add support of Cavium Liquidio ethernet adapters")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Felix Manlunas <felix.manlunas@cavium.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Felix Manlunas <fmanluna@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>