[net] sched: cls_u32: fix cls_u32 on filter replace
Message-id: <20180209131255.17543-1-ivecera@redhat.com>
Patchwork-id: 205567
O-Subject: [RHEL7.5 net PATCH] net/sched: cls_u32: fix cls_u32 on filter replace
Bugzilla: 1542013
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1542013

Backport note:
- Context conflict due to missing commit 4b981dbc2272 ("net: sched: cls_u32:
  add extack support")

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15253901

Test status:
Tested by myself using BZ reproducer.

Upstream commit(s):
commit eb53f7af6f15285e2f6ada97285395343ce9f433
Author: Ivan Vecera <ivecera@redhat.com>
Date:   Thu Feb 8 16:10:39 2018 +0100

    net/sched: cls_u32: fix cls_u32 on filter replace

    The following sequence is currently broken:

     # tc qdisc add dev foo ingress
     # tc filter replace dev foo protocol all ingress \
       u32 match u8 0 0 action mirred egress mirror dev bar1
     # tc filter replace dev foo protocol all ingress \
       handle 800::800 pref 49152 \
       u32 match u8 0 0 action mirred egress mirror dev bar2
     Error: cls_u32: Key node flags do not match passed flags.
     We have an error talking to the kernel, -1

    The error comes from u32_change() when comparing new and
    existing flags. The existing ones always contains one of
    TCA_CLS_FLAGS_{,NOT}_IN_HW flag depending on offloading state.
    These flags cannot be passed from userspace so the condition
    (n->flags != flags) in u32_change() always fails.

    Fix the condition so the flags TCA_CLS_FLAGS_NOT_IN_HW and
    TCA_CLS_FLAGS_IN_HW are not taken into account.

    Fixes: 24d3dc6d27ea ("net/sched: cls_u32: Reflect HW offload status")
    Signed-off-by: Ivan Vecera <ivecera@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>