[hid] iio: common: hid-sensors: use tab for indention
Message-id: <1510839526-11340-22-git-send-email-gtiwari@redhat.com>
Patchwork-id: 198270
O-Subject: [ PATCH BZ 1475903 21/59] iio: common: hid-sensors: use tab for indention
Bugzilla: 1475903
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1475903

commit d23057e0cadc465911968a4d3f8b0b556f545b6e
Author: Slawomir Stepien <sst@poczta.fm>
Date:   Thu Apr 14 21:36:40 2016 +0200

    iio: common: hid-sensors: use tab for indention

    This fixes the error reported by checkpatch.pl:

    ERROR: code indent should use tabs where possible

    Signed-off-by: Slawomir Stepien <sst@poczta.fm>
    Signed-off-by: Jonathan Cameron <jic23@kernel.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jeremy McNicoll <jeremymc@redhat.com>
Signed-off-by: Rafael Aquini <aquini@redhat.com>