[netdrv] mlxsw: spectrum_kvdl: use div_u64() for 64-bit division
Message-id: <20180601184800.22484-174-ivecera@redhat.com>
Patchwork-id: 220141
O-Subject: [RHEL7.6 PATCH 172/224] mlxsw: spectrum_kvdl: use div_u64() for 64-bit division
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Upstream commit(s):
commit b89c7695b14f58686ac89d5add861f1f6d3fd4da
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 23 14:15:31 2018 +0100

    mlxsw: spectrum_kvdl: use div_u64() for 64-bit division

    Calculating the number of entries now uses 64-bit arithmetic that
    causes a link error on 32-bit architectures:

    drivers/net/ethernet/mellanox/mlxsw/spectrum_kvdl.o: In function `mlxsw_sp_kvdl_init':
    spectrum_kvdl.c:(.text+0x51c): undefined reference to `__aeabi_uldivmod'

    We could probably use a 32-bit division here as before, but since this is
    not in a performance critical path, div_u64() seems cleaner here.

    Fixes: 887839e6960d ("mlxsw: spectrum_kvdl: Add support for dynamic partition set")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Arkadi Sharshevsky <arkadis@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>