[mmc] test: reduce stack usage in mmc_test_nonblock_transfer
Message-id: <1528141166-25634-76-git-send-email-gtiwari@redhat.com>
Patchwork-id: 220477
O-Subject: [RHEL7.6 V4 BZ 1456570 075/151] mmc: test: reduce stack usage in mmc_test_nonblock_transfer
Bugzilla: 1456570
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1456570

commit 098dc66adeba4aaa8797124c10c2a77fd2e89584
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Aug 15 17:11:58 2017 +0200

    mmc: test: reduce stack usage in mmc_test_nonblock_transfer

    The new lockdep annotations for completions cause a warning in the
    mmc test module, in a function that now has four 150 byte structures
    on the stack:

    drivers/mmc/core/mmc_test.c: In function 'mmc_test_nonblock_transfer.constprop':
    drivers/mmc/core/mmc_test.c:892:1: error: the frame size of 1360 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    The mmc_test_ongoing_transfer function evidently had a similar problem,
    and worked around it by using dynamic allocation.

    This generalizes the approach used by mmc_test_ongoing_transfer() and
    applies it to mmc_test_nonblock_transfer() as well.

    Fixes: cd8084f91c02 ("locking/lockdep: Apply crossrelease to completions")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Adrian Hunter <adrian.hunter@intel.com>
    Tested-by: Adrian Hunter <adrian.hunter@intel.com>
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>