[kernel] perf/core: Remove unused perf_cgroup_event_cgrp_time() function
Message-id: <20180219120557.28358-5-jolsa@redhat.com>
Patchwork-id: 205812
O-Subject: [PATCH RHEL7.6 BZ1532861 04/98] perf/core: Remove unused perf_cgroup_event_cgrp_time() function
Bugzilla: 1532861
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1532861
https://bugzilla.redhat.com/show_bug.cgi?id=1532861

upstream
========
commit d0fabd1cb8b70073a0f44f1cf8b663b5e7241c74
Author: Matthias Kaehlcke <mka@chromium.org>
Date: Tue May 23 14:51:32 2017 -0700

description
===========
The function was added by commit e5d1367f17ba ("perf: Add cgroup
support") in 2011 and hasn't been used since then. Removing it fixes the
following warning when building with Clang:

    kernel/events/core.c:696:19: error: unused function 'perf_cgroup_event_cgrp_time' [-Werror,-Wunused-function]

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>