[netdrv] mlxsw: spectrum_kvdl: avoid uninitialized variable warning
Message-id: <20180601184800.22484-175-ivecera@redhat.com>
Patchwork-id: 220133
O-Subject: [RHEL7.6 PATCH 173/224] mlxsw: spectrum_kvdl: avoid uninitialized variable warning
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Upstream commit(s):
commit ed2da6270ed9ea37d39e9ab597fc5b3b4215ae2a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 23 14:15:32 2018 +0100

    mlxsw: spectrum_kvdl: avoid uninitialized variable warning

    gcc warns that 'resource_id' is not initialized if we don't come though
    any of the three 'case' statements before:

    drivers/net/ethernet/mellanox/mlxsw/spectrum_kvdl.c: In function 'mlxsw_sp_kvdl_part_init':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_kvdl.c:275:8: error: 'resource_id' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    In the current code, that won't happen, but it's more robust to explicitly
    handle this by returning a failure from mlxsw_sp_kvdl_part_init.

    Fixes: 887839e6960d ("mlxsw: spectrum_kvdl: Add support for dynamic partition set")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Arkadi Sharshevsky <arkadis@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>