[net] geneve: ICMP error lookup handler
Message-id: <a487c51fb5d0f7fb3d88cfd6dcde690ec37b2295.1542735071.git.sbrivio@redhat.com>
Patchwork-id: 233468
O-Subject: [RHEL7.7 net 4/5] geneve: ICMP error lookup handler
Bugzilla: 1511372
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1511372
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19234873
Tested: with reproducer at https://bugzilla.redhat.com/show_bug.cgi?id=1511372#c7

Backport Notes: this is a backport of two commits. Commit 8a962c4aa1e6
	needs to be backported to avoid a (bogus) warning occurring with
	gcc 4.8. Note that a proper GNU C89 initialiser for struct in6_addr
	struct is either { { { 0 } } } or IN6ADDR_ANY_INIT, but I gave up
	discussing this upstream. I'm squashing them in a single commit to
	preserve bisectability.

Upstream Status: net-next.git commits a07966447f39, 8a962c4aa1e6

commit a07966447f39fe43e37d05c9bfc92b1493267a59
Author: Stefano Brivio <sbrivio@redhat.com>
Date:   Thu Nov 8 12:19:18 2018 +0100

    geneve: ICMP error lookup handler

    Export an encap_err_lookup() operation to match an ICMP error against a
    valid VNI.

    Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
    Reviewed-by: Sabrina Dubroca <sd@queasysnail.net>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 8a962c4aa1e6c0836985a5843f44d74fe3cced12
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Fri Nov 16 18:36:27 2018 -0700

    geneve: Initialize addr6 with memset

    Clang warns:

    drivers/net/geneve.c:428:29: error: suggest braces around initialization
    of subobject [-Werror,-Wmissing-braces]
                    struct in6_addr addr6 = { 0 };
                                              ^
                                              {}

    Rather than trying to appease the various compilers that support the
    kernel, use memset, which is unambiguous.

    Fixes: a07966447f39 ("geneve: ICMP error lookup handler")
    Suggested-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>