[edac] EDAC, skx, i10nm: Make skx_common.c a pure library
Message-id: <20191104184651.379188391@redhat.com>
Patchwork-id: 282619
Patchwork-instance: patchwork
O-Subject: [RHEL7 PATCH 17/21] EDAC, skx, i10nm: Make skx_common.c a pure library
Bugzilla: 1514705
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

BZ#1514705
brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24341497
Tested: sanity only: we only have one type of this system in beaker and EINJ doesn't work. Tested on machines with skx_edac to make sure existing functionality didn't break after split

commit fe783516e3016652b74ac92fb8b3fc2b1c0e9d5b
Author: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
Date:   Thu Mar 21 15:13:39 2019 -0700

    EDAC, skx, i10nm: Make skx_common.c a pure library

    The following Kconfig constellations fail randconfig builds:

      CONFIG_ACPI_NFIT=y
      CONFIG_EDAC_DEBUG=y
      CONFIG_EDAC_SKX=m
      CONFIG_EDAC_I10NM=y

    or

      CONFIG_ACPI_NFIT=y
      CONFIG_EDAC_DEBUG=y
      CONFIG_EDAC_SKX=y
      CONFIG_EDAC_I10NM=m

    with:
      ...
      CC [M]  drivers/edac/skx_common.o
      ...
      .../skx_common.o:.../skx_common.c:672: undefined reference to `__this_module'

    That is because if one of the two drivers - skx_edac or i10nm_edac - is
    built-in and the other one is a module, the shared file skx_common.c
    gets linked into a module object by kbuild. Therefore, when linking that
    same file into vmlinux, the '__this_module' symbol used in debugfs isn't
    defined, leading to the above error.

    Fix it by moving all debugfs code from skx_common.c to both skx_base.c
    and i10nm_base.c respectively. Thus, skx_common.c doesn't refer to the
    '__this_module' symbol anymore.

    Clarify skx_common.c's purpose at the top of the file for future
    reference, while at it.

     [ bp: Make text more readable. ]

    Fixes: d4dc89d069aa ("EDAC, i10nm: Add a driver for Intel 10nm server processors")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
    Signed-off-by: Tony Luck <tony.luck@intel.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: James Morse <james.morse@arm.com>
    Cc: Mauro Carvalho Chehab <mchehab@kernel.org>
    Cc: linux-edac <linux-edac@vger.kernel.org>
    Link: https://lkml.kernel.org/r/20190321221339.GA32323@agluck-desk

Signed-off-by: Jan Stancek <jstancek@redhat.com>