[netdrv] mlxsw: spectrum_router: Return extack message on abort due to fib rules
Message-id: <20180601184800.22484-74-ivecera@redhat.com>
Patchwork-id: 220030
O-Subject: [RHEL7.6 PATCH 072/224] mlxsw: spectrum_router: Return extack message on abort due to fib rules
Bugzilla: 1520304
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1520304

Backport note:
- Using dev_err() instead of NL_SET_ERR_MSG() due to absence of extack
  support in RHEL

Upstream commit(s):
commit 1f279233affe115dd3f65c89716a4f4315bb4cfe
Author: David Ahern <dsahern@gmail.com>
Date:   Fri Oct 27 17:37:14 2017 -0700

    mlxsw: spectrum_router: Return extack message on abort due to fib rules

    Adding a FIB rule on a spectrum platform silently aborts FIB offload:
        $ ip ru add pref 99 from all to 192.168.1.1 table 10
        $ dmesg -c
        [  623.144736] mlxsw_spectrum 0000:03:00.0: FIB abort triggered. Note that FIB entries are no longer being offloaded to this device.

    This patch reworks FIB rule handling to return a message to the user:
        $ ip ru add pref 99 from all to 8.8.8.8 table 11
        Error: spectrum: FIB rules not supported. Aborting offload.

    spectrum currently only checks whether the fib rule is a default rule or
    an l3mdev rule, both of which it knows how to handle. Any other it aborts
    FIB offload. Move the processing to check the rule type inline with the
    user request. If the rule is an unsupported one, then a work queue entry
    is used to abort the offload. Change the rule delete handling to just
    return since it does nothing at the moment.

    Signed-off-by: David Ahern <dsahern@gmail.com>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>