[infiniband] rdma/bnxt_re: qplib_fp: fix pointer cast
Message-id: <1523437443-19278-23-git-send-email-sxavier@redhat.com>
Patchwork-id: 208885
O-Subject: [RHEL 7.6 PATCH BZ 1550629 22/24] RDMA/bnxt_re: qplib_fp: fix pointer cast
Bugzilla: 1550629
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1550629
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15718765
Upstream Status: commit 5388a508479d8b7e6d24fe5ca2645806d8e3d0f1
Test info: https://bugzilla.redhat.com/show_bug.cgi?id=1550629 for
details

commit 5388a508479d8b7e6d24fe5ca2645806d8e3d0f1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 20 21:56:26 2018 +0100

    infiniband: qplib_fp: fix pointer cast

    Building for a 32-bit target results in a couple of warnings from casting
    between a 32-bit pointer and a 64-bit integer:

    drivers/infiniband/hw/bnxt_re/qplib_fp.c: In function 'bnxt_qplib_service_nq':
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:333:23: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
        bnxt_qplib_arm_srq((struct bnxt_qplib_srq *)q_handle,
                           ^
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:336:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
                (struct bnxt_qplib_srq *)q_handle,
                ^
    In file included from include/linux/byteorder/little_endian.h:5,
                     from arch/arm/include/uapi/asm/byteorder.h:22,
                     from include/asm-generic/bitops/le.h:6,
                     from arch/arm/include/asm/bitops.h:342,
                     from include/linux/bitops.h:38,
                     from include/linux/kernel.h:11,
                     from include/linux/interrupt.h:6,
                     from drivers/infiniband/hw/bnxt_re/qplib_fp.c:39:
    drivers/infiniband/hw/bnxt_re/qplib_fp.c: In function 'bnxt_qplib_create_srq':
    include/uapi/linux/byteorder/little_endian.h:31:43: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     #define __cpu_to_le64(x) ((__force __le64)(__u64)(x))
                                               ^
    include/linux/byteorder/generic.h:86:21: note: in expansion of macro '__cpu_to_le64'
     #define cpu_to_le64 __cpu_to_le64
                         ^~~~~~~~~~~~~
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:569:19: note: in expansion of macro 'cpu_to_le64'
      req.srq_handle = cpu_to_le64(srq);

    Using a uintptr_t as an intermediate works on all architectures.

    Fixes: 37cb11acf1f7 ("RDMA/bnxt_re: Add SRQ support for Broadcom adapters")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Selvin Xavier <sxavier@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>