[netdrv] mlx5e: Fix compilation warning in en_tc.c
Message-id: <20190417135957.11804-12-ahleihel@redhat.com>
Patchwork-id: 250258
O-Subject: [RHEL7.7 BZ 1695493 11/31] net/mlx5e: Fix compilation warning in en_tc.c
Bugzilla: 1695493
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1695493
Upstream: net-next/master

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>

Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/eswitch.h
   Small context conflict due to the following missing patch
   5ae5162066d8 ("net/mlx5: E-Switch, Assign a different position for uplink rep and vport")

commit ee576ec1c1c66ec1cd0c4735bb12bc08f675f530
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Thu Mar 21 15:51:33 2019 -0700

    net/mlx5e: Fix compilation warning in en_tc.c

    Amazingly a mlx5e_tc function is being called from the eswitch layer,
    which is by itself very terrible! The function was declared locally in
    eswitch_offloads.c so it could be used there, which caused the following
    compilation warning, fix that.

    drivers/.../mlx5/core/en_tc.c:3242:6: [-Werror=missing-prototypes]
    error: no previous prototype for mlx5e_tc_clean_fdb_peer_flows

    Fixes: 04de7dda7394 ("net/mlx5e: Infrastructure for duplicated offloading of TC flows")
    Reviewed-by: Roi Dayan <roid@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>

Cc: Erez Alfasi <ealfasi@redhat.com>
Cc: Alaa Hleihel <ahleihel@redhat.com>