[iio] common: hid-sensors: use tab for indention
Message-id: <20180711174504.24920-330-tcamuso@redhat.com>
Patchwork-id: 224709
O-Subject: [RHEL7 BZ-1559170 v3 329/373] iio: common: hid-sensors: use tab for indention
Bugzilla: 1559170
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1559170
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17099185

Cherry-picked from the following upstream commit.

commit d23057e0cadc465911968a4d3f8b0b556f545b6e
Author: Slawomir Stepien <sst@poczta.fm>
Date:   Thu Apr 14 21:36:40 2016 +0200

    iio: common: hid-sensors: use tab for indention

    This fixes the error reported by checkpatch.pl:

    ERROR: code indent should use tabs where possible

    Signed-off-by: Slawomir Stepien <sst@poczta.fm>
    Signed-off-by: Jonathan Cameron <jic23@kernel.org>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>