[powerpc] livepatch: Fix build error with kprobes disabled
Message-id: <20190228145933.10003-2-joe.lawrence@redhat.com>
Patchwork-id: 243613
O-Subject: [RHEL-7.7 PATCH 1/6] powerpc/livepatch: Fix build error with kprobes disabled.
Bugzilla: 1658435
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Artem Savkov <asavkov@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1658435
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20392297

commit 5e3f0d15ae5f95bdde8d092a0884d2defe27d448
Author: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
Date:   Tue May 22 14:38:20 2018 +0530

    powerpc/livepatch: Fix build error with kprobes disabled.

    arch/powerpc/kernel/stacktrace.c: In function save_stack_trace_tsk_reliable:
    arch/powerpc/kernel/stacktrace.c:176:28: error: kretprobe_trampoline undeclared
       if (ip == (unsigned long)kretprobe_trampoline)
                                ^~~~~~~~~~~~~~~~~~~~

    Fixes: df78d3f61480 ("powerpc/livepatch: Implement reliable stack tracing for the consistency model")
    Signed-off-by: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>