[netdrv] ath10k: mark PM functions as __maybe_unused
Message-id: <1511444696-7036-14-git-send-email-sgruszka@redhat.com>
Patchwork-id: 199887
O-Subject: [RHEL7.5 PATCH 13/29] ath10k: mark PM functions as __maybe_unused
Bugzilla: 1501877
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Torez Smith <torez@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

BZ#1501877

Backport of:
commit 6af1de2e4ec49635905aaed31d073a0d92c8d3bf
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 6 14:58:53 2017 +0200

    ath10k: mark PM functions as __maybe_unused

    When CONFIG_PM_SLEEP is disabled, we get a compile-time
    warning:

    drivers/net/wireless/ath/ath10k/pci.c:3417:12: error: 'ath10k_pci_pm_resume' defined but not used [-Werror=unused-function]
     static int ath10k_pci_pm_resume(struct device *dev)
                ^~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/ath/ath10k/pci.c:3401:12: error: 'ath10k_pci_pm_suspend' defined but not used [-Werror=unused-function]
     static int ath10k_pci_pm_suspend(struct device *dev)

    Rather than fixing the #ifdef, this just marks both functions
    as __maybe_unused, which is a more robust way to do this.

    Fixes: 32faa3f0ee50 ("ath10k: add the PCI PM core suspend/resume ops")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@qca.qualcomm.com>

Brew:
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14593787

Testing:
Tested on QCA9377.

Signed-off-by: Rafael Aquini <aquini@redhat.com>