[tools] perf tools: Add '\n' at the end of parse-options error messages
Message-id: <20190211232742.16489-246-jolsa@redhat.com>
Patchwork-id: 241634
O-Subject: [PATCH RHEL7 BZ1672651 245/271] perf tools: Add '\n' at the end of parse-options error messages
Bugzilla: 1672651
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1672651
https://bugzilla.redhat.com/show_bug.cgi?id=1672651

upstream
========
commit 66f5a0779af2a4f28b1832f6c20bc9d3b1ab1886
Author: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
Date: Tue Apr 17 09:43:44 2018 +0530

description
===========
Few error messages does not have '\n' at the end and thus next prompt
gets printed in the same line. Ex,

  linux~$ perf buildid-cache -verbose --add ./a.out
   Error: did you mean `--verbose` (with two dashes ?)linux~$

Fix it.

Signed-off-by: Jan Stancek <jstancek@redhat.com>