[acpi] acpi / watchdog: properly initialize resources
Message-id: <1547664170-144848-4-git-send-email-darcari@redhat.com>
Patchwork-id: 237440
O-Subject: [RHEL7.7 BZ 1666393 3/6] ACPI / watchdog: properly initialize resources
Bugzilla: 1666393
RH-Acked-by: Al Stone <ahs3@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1666393

commit 6ce14f6416c84bd9c81777edf899b57ac5000c87
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 19 01:49:02 2017 +0200

    ACPI / watchdog: properly initialize resources

    We copy a local resource structure into a list, but only
    initialize some of its members, as pointed out by gcc-4.4:

    drivers/acpi/acpi_watchdog.c: In function 'acpi_watchdog_init':
    drivers/acpi/acpi_watchdog.c:105: error: 'res.child' may be used uninitialized in this function
    drivers/acpi/acpi_watchdog.c:105: error: 'res.sibling' may be used uninitialized in this function
    drivers/acpi/acpi_watchdog.c:105: error: 'res.parent' may be used uninitialized in this function
    drivers/acpi/acpi_watchdog.c:105: error: 'res.desc' may be used uninitialized in this function
    drivers/acpi/acpi_watchdog.c:105: error: 'res.name' may be used uninitialized in this function

    Newer compilers can presumably optimize the uninitialized access
    away entirely and don't warn at all, but rely on the kzalloc()
    to zero the structure first. This adds an explicit initialization
    to force consistent behavior.

    Fixes: 058dfc767008 (ACPI / watchdog: Add support for WDAT hardware watchdog)
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Mika Westerberg <mika.westerberg@linux.intel.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Cc: Al Stone <ahs3@redhat.com>
Cc: Lenny Szubowicz <lszubowi@redhat.com>
Cc: Prarit Bhargava <prarit@redhat.com>
Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>