[powerpc] pseries: Add empty update_numa_cpu_lookup_table() for NUMA=n
Message-id: <1533214317-22722-1-git-send-email-gduarte@redhat.com>
Patchwork-id: 225939
O-Subject: [RHEL7.6 PATCH BZ 1544437 7/6] powerpc/pseries: Add empty update_numa_cpu_lookup_table() for NUMA=n
Bugzilla: 1544437
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

BZ 1544437
Upstream Status: c1e150ceb61e4a585bad156da15c33bfe89f5858
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=17517101
Tested: I boot tested on ppc64 lpar and ppc64le kvm guest.

commit c1e150ceb61e4a585bad156da15c33bfe89f5858
Author: Corentin Labbe <clabbe@baylibre.com>
Date:   Wed Feb 14 12:17:47 2018 +0000

    powerpc/pseries: Add empty update_numa_cpu_lookup_table() for NUMA=n

    When CONFIG_NUMA is not set, the build fails with:

      arch/powerpc/platforms/pseries/hotplug-cpu.c:335:4:
      error: dclaration implicite de la fonction update_numa_cpu_lookup_table

    So we have to add update_numa_cpu_lookup_table() as an empty function
    when CONFIG_NUMA is not set.

    Fixes: 1d9a090783be ("powerpc/numa: Invalidate numa_cpu_lookup_table on cpu remove")
    Signed-off-by: Corentin Labbe <clabbe@baylibre.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>