[fs] cifs: hide unused functions
Message-id: <20180515031237.30955-2-lsahlber@redhat.com>
Patchwork-id: 215026
O-Subject: [RHEL7.6 fs BZ 1578183 01/13] cifs: hide unused functions
Bugzilla: 1578183
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: 1578183
Build: 16284542

The newly added SMB2+ attribute support causes unused function
warnings when CONFIG_CIFS_XATTR is disabled:

fs/cifs/smb2ops.c:563:1: error: 'smb2_set_ea' defined but not used [-Werror=unused-function]
 smb2_set_ea(const unsigned int xid, struct cifs_tcon *tcon,
fs/cifs/smb2ops.c:513:1: error: 'smb2_query_eas' defined but not used [-Werror=unused-function]
 smb2_query_eas(const unsigned int xid, struct cifs_tcon *tcon,

This adds another #ifdef around the affected functions.

Fixes: 5517554e4313 ("cifs: Add support for writing attributes on SMB2+")
Fixes: 95907fea4fd8 ("cifs: Add support for reading attributes on SMB2+")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit 1368f155a972eab037f81b5dea82afd544227552)
Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
---

Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>