[netdrv] bnxt_en: include bnxt_vfr.c code under CONFIG_BNXT_SRIOV switch
Message-id: <20958baf0ab122967ed3d3c439be9db37e8225fe.1510964611.git.jtoppins@redhat.com>
Patchwork-id: 199152
O-Subject: [RHEL7.5 060/105] bnxt_en: include bnxt_vfr.c code under CONFIG_BNXT_SRIOV switch
Bugzilla: 1459659
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

And define empty functions in bnxt_vfr.h when CONFIG_BNXT_SRIOV is not
defined.

This fixes build error when CONFIG_BNXT_SRIOV is switched off:
>> drivers/net/ethernet/broadcom/bnxt/bnxt_vfr.c:165:16: error: 'struct
>> bnxt' has no member named 'sriov_lock'

Reported-by: kbuild test robot <lkp@intel.com>
Fixes: 4ab0c6a8ffd7 ("bnxt_en: add support to enable VF-representors")
Signed-off-by: Sathya Perla <sathya.perla@broadcom.com>
Signed-off-by: Michael Chan <michael.chan@broadcom.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d3e3becedc43adc8b8fb12e7507dd4e5aae4d17d)
Bugzilla: 1459659
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14573628
Tested: basic testing further testing being done by Broadcom and myself
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>

Signed-off-by: Rafael Aquini <aquini@redhat.com>