[kernel] linux/genalloc.h: spinlock_t needs spinlock_types.h
Message-id: <20190318190100.22707-50-jmoyer@redhat.com>
Patchwork-id: 246897
O-Subject: [RHEL7.7 PATCH 49/86] include/linux/genalloc.h: spinlock_t needs spinlock_types.h
Bugzilla: 1662226
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

From: Shawn Guo <shawn.guo@linaro.org>

BZ: 1662226
Brew: 20606686

commit b30afea019a4548ee77b73e83f03104e0e3a0556
Author: Shawn Guo <shawn.guo@linaro.org>
Date:   Thu Jan 23 15:53:18 2014 -0800

    include/linux/genalloc.h: spinlock_t needs spinlock_types.h

    Compiling a C file which includes genalloc.h but without
    spinlock_types.h being included before, we will see the compile error
    below.

     include/linux/genalloc.h:54:2: error: unknown type name `spinlock_t'

    Include spinlock_types.h from genalloc.h to fix the problem.

    Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>