[net] netfilter: don't pull include/linux/netfilter.h from netns headers
Message-id: <20190110173336.22294-3-fbl@redhat.com>
Patchwork-id: 237196
O-Subject: [RHEL7.7 net PATCH v2 02/28] netfilter: don't pull include/linux/netfilter.h from netns headers
Bugzilla: 1554261
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1554261
Build Info:
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19734802
Tested:
- network-qe tests passed
https://beaker.engineering.redhat.com/jobs/3282496
- LNST tests passed
https://beaker.engineering.redhat.com/jobs/3282114
- ebtables-tests passed
https://github.com/fleitner/ebtables-tests/
- verified with a local reproducer

Only minor conflicts.

commit a263653ed798216c0069922d7b5237ca49436007
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Wed Jun 17 10:28:27 2015 -0500

    netfilter: don't pull include/linux/netfilter.h from netns headers

    This pulls the full hook netfilter definitions from all those that include
    net_namespace.h.

    Instead let's just include the bare minimum required in the new
    linux/netfilter_defs.h file, and use it from the netfilter netns header files.

    I also needed to include in.h and in6.h from linux/netfilter.h otherwise we hit
    this compilation error:

    In file included from include/linux/netfilter_defs.h:4:0,
                     from include/net/netns/netfilter.h:4,
                     from include/net/net_namespace.h:22,
                     from include/linux/netdevice.h:43,
                     from net/netfilter/nfnetlink_queue_core.c:23:
    include/uapi/linux/netfilter.h:76:17: error: field 'in' has incomplete type struct in_addr in;

    And also explicit include linux/netfilter.h in several spots.

    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
    Signed-off-by: Eric W. Biederman <ebiederm@xmission.com>

Signed-off-by: Flavio Leitner <fbl@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>