[infiniband] rdma/cxgb4: Add a sanity check in process_work()
Message-id: <1525782904-18307-18-git-send-email-avynipad@redhat.com>
Patchwork-id: 213228
O-Subject: [RHEL7.6 PATCH BZ 1523154 17/22] RDMA/cxgb4: Add a sanity check in process_work()
Bugzilla: 1523154
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1523154

commit ccc04cdd55d8cfa7376ba96a037ba0f1b3df33c7
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Tue Dec 5 17:36:54 2017 +0300

    RDMA/cxgb4: Add a sanity check in process_work()

    The story is that Smatch marks skb->data as untrusted so it generates
    a warning message here:

        drivers/infiniband/hw/cxgb4/cm.c:4100 process_work()
        error: buffer overflow 'work_handlers' 241 <= 255

    In other places which handle this such as t4_uld_rx_handler() there is
    some checking to make sure that the function pointer is not NULL.  I
    have added bounds checking and a check for NULL here as well.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Steve Wise <swise@opengridcomputing.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Cc: Don Dutile <ddutile@redhat.com>
Cc: Arjun Vynipadath <avynipad@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>