[netdrv] bnxt_en: Uninitialized variable in bnxt_tc_parse_actions()
Message-id: <3478e15db839ce9dad4a018e062dc6ff48cf5ff4.1515089705.git.jtoppins@redhat.com>
Patchwork-id: 203195
O-Subject: [RHEL7.5 8/9] bnxt_en: Uninitialized variable in bnxt_tc_parse_actions()
Bugzilla: 1522743
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Smatch warns that:

    drivers/net/ethernet/broadcom/bnxt/bnxt_tc.c:160 bnxt_tc_parse_actions()
    error: uninitialized symbol 'rc'.

"rc" is either uninitialized or set to zero here so we can just remove
the check.

Fixes: 8c95f773b4a3 ("bnxt_en: add support for Flower based vxlan encap/decap offload")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Acked-by: Michael Chan <michael.chan@broadcom.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 92425c40676d498efccae6fecdb8f8e4dcf7e4a4)
Bugzilla: 1522743
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14867211
Tested: build test only
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>

Signed-off-by: Bruno E. O. Meneguele <brdeoliv@redhat.com>