[fs] cifs: hide unused functions
Message-id: <20180315061427.501-3-lsahlber@redhat.com>
Patchwork-id: 206796
O-Subject: [RHEL 7.6 BZ 155076 FS 2/7] cifs: hide unused functions
Bugzilla: 1555076
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: 1555076
Build: 15555219

Some functions are only referenced under an #ifdef, causing a harmless
warning:

fs/cifs/smb2ops.c:1374:1: error: 'get_smb2_acl' defined but not used [-Werror=unused-function]

We could mark them __maybe_unused or add another #ifdef, I picked
the second approach here.

Fixes: b3fdda4d1e1b ("cifs: Use smb 2 - 3 and cifsacl mount options getacl functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit 84908426f2097d5c6e254c73ffcb6923a355dbda)
Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>