[netdrv] ixgbevf: fix unused variable warning
Message-id: <9f189f8a9a4f584bd957a37df2eb20f6e707fa05.1527273942.git.jkc@redhat.com>
Patchwork-id: 217700
O-Subject: [RHEL7.6 BZ 1518094 25/31] ixgbevf: fix unused variable warning
Bugzilla: 1520661 1518094
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1518094
Bugzilla: http://bugzilla.redhat.com/1520661
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=16464513
Tested: lnst tests: vlan, 3_vlans, bridge_vlan, vlan_bridge, vxlan
Tested: vxlan_remote, iperf, multicast-all, ping, simple_macsec

commit 954b54dea0ebfd2ead48e6bb12a165025227f4b3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Mar 1 00:17:36 2018 +0100

    ixgbevf: fix unused variable warning

    The new ixgbevf_set_rx_buffer_len() function causes a harmless warnings
    in configurations with large page size:

    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c: In function 'ixgbevf_set_rx_buffer_len':
    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c:1758:15: error: unused variable 'max_frame' [-Werror=unused-variable]

    This rephrases the code so that the compiler can see the use of that
    variable, making it slightly easier to read in the process.

    Fixes: f15c5ba5b6cd ("ixgbevf: add support for using order 1 pages to receive large frames")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
    Acked-by: Alexander Duyck <alexander.h.duyck@intel.com>
    Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>

Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Cc: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>